# HH18

In [23]:
import pandas as pd

# Import HH18 Household Data
df_HH = pd.read_csv('HH18.csv', sep=";")

# Delete columns that are not needed
df_HH = df_HH.drop(columns=['JAHR', 'BIK', 'REGION', 'KREIS', 'GEMEINDE', 'EWZahl', 'WETTER', 'UMZUG', 'EINKO', 'PKWpriv1', 'PKWpriv2'
                     , 'PKWpriv3', 'PKWnutz1', 'PKWnutz2', 'PKWnutz3', 'PARKGAR', 'PARKPROB',
                      'HALTBUS', 'HALTBUSZ', 'HALTSTR', 'HALTSTRZ', 'HALTU', 'HALTUZ', 'HALTS', 'HALTSZ', 'HALTZUG', 
                     'HALTZUGZ', 'OEFFZUF', 'EINK1', 'EINK1KM', 'EINK2', 'EINK2KM', 'KNEIPE', 'KNEIPEKM', 'KINO', 'KINOKM', 
                     'SPORT', 'SPORTKM', 'ZWEITW', 'ZWEITWKM', 'CARSHAR', 'HANDY', 'PC', 'PCWEB', 'KOHORTE', 'CONTACT', 
                      'HHPMETHOD', 'EINK1_ENTF', 'EINK2_ENTF', 'KNEIPE_ENTF', 'KINO_ENTF', 'SPORT_ENTF', 'IDREGIOSTAR2', 
                      'IDREGIOSTAR7', 'IDREGIOSTARGEM5'])
df_HH

,ID,RAUMTYP,PLZ,GKZ,LAGE,HHTYP,HHGRO,P0_10,PKWHH,PARKSTR1,PARKSTR2,PARKSTR3,GEWHHWO
0,4501022118,1,235,1003,2.0,2,2,0,1,2.0,NaN,NaN,13896.2
1,4501022122,3,237,1055,3.0,1,1,0,2,2.0,2.0,NaN,24293.8
2,4501022123,1,254,1056,3.0,2,1,0,1,2.0,NaN,NaN,13856.9
3,4501022126,1,214,1062,2.0,2,1,0,0,NaN,NaN,NaN,30091.7
4,4501022143,2,309,3241,5.0,2,1,0,1,2.0,NaN,NaN,13856.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1840,8911045519,2,182,13072,5.0,2,1,0,0,NaN,NaN,NaN,27553.0
1841,8911045555,1,124,11200,1.0,1,1,0,0,NaN,NaN,NaN,82655.1
1842,8911046133,1,141,11100,2.0,2,1,0,1,1.0,NaN,NaN,15247.1
1843,8911046150,1,133,11100,1.0,2,1,0,0,NaN,NaN,NaN,22099.8
1844,8911046177,2,92,14522,5.0,1,2,0,2,2.0,2.0,NaN,9218.3

In [24]:
# Analyze column PARKSTR 
print(df_HH["PARKSTR1"].value_counts(normalize=False))
print(df_HH["PARKSTR2"].value_counts(normalize=False))
print(df_HH["PARKSTR3"].value_counts(normalize=False))
print('_____________________')

# PKWHH = 0 delete, delete all households without a car 
print(df_HH.groupby('PKWHH').count())
df_HH.shape # 1845 rows
df_HH = df_HH.loc[df_HH["PKWHH"] != 0]
df_HH.shape # 1525 rows

print(df_HH.groupby('PKWHH').count())

2.0    1247
1.0     276
Name: PARKSTR1, dtype: int64
2.0    489
1.0    122
Name: PARKSTR2, dtype: int64
2.0    109
1.0     27
Name: PARKSTR3, dtype: int64
_____________________
        ID  RAUMTYP  PLZ  GKZ  LAGE  HHTYP  HHGRO  P0_10  PARKSTR1  PARKSTR2  \
PKWHH
0      320      320  320  320   320    320    320    320         0         0
1      910      910  910  910   907    910    910    910       910         0
2      478      478  478  478   478    478    478    478       476       474
3      107      107  107  107   107    107    107    107       107       107
4       21       21   21   21    21     21     21     21        21        21
5        8        8    8    8     8      8      8      8         8         8
6        1        1    1    1     1      1      1      1         1         1

       PARKSTR3  GEWHHWO
PKWHH
0             0      320
1             0      910
2             0      478
3           106      107
4            21       21
5             8        8
6             1        1
        ID  RAUMTYP  PLZ  GKZ  LAGE  HHTYP  HHGRO  P0_10  PARKSTR1  PARKSTR2  \
PKWHH
1      910      910  910  910   907    910    910    910       910         0
2      478      478  478  478   478    478    478    478       476       474
3      107      107  107  107   107    107    107    107       107       107
4       21       21   21   21    21     21     21     21        21        21
5        8        8    8    8     8      8      8      8         8         8
6        1        1    1    1     1      1      1      1         1         1

       PARKSTR3  GEWHHWO
PKWHH
1             0      910
2             0      478
3           106      107
4            21       21
5             8        8
6             1        1

* ID = Household ID
* RAUMTYP = Population of Region, 1 = >100,000, 5 = <5,000
* PLZ = Postcode
* GKZ = State, 8 = BW
* LAGE = Location of apartment, 1 = city center, 6 = rural
* HHTYP = Type of Household, 1/2 = 1-2 p., 3/4 = +3 p.
* HHGRO = Number of people in household
* HHGRONEW = Number of people in household age >10
* P0_10 = Of that, Number of children under 10
* PKWHH = Number of cars
* PARKSTR1 = Type of parking lot, 2 = private Garage, 1 = Street/Public, for Car 1
* PARKSTR2 = Type of parking lot, 2 = private Garage, 1 = Street/Public, for Car 2
* PARKSTR3 = Type of parking lot, 2 = private Garage, 1 = Street/Public, for Car 3
* GEWHHWO = Projection Factor

In [25]:
# Calculate household without children and drop children
df_HH['HHGRONEW'] = df_HH['HHGRO'] - df_HH['P0_10']
df_HH = df_HH.sort_values(by=['HHGRO'], ascending=False)
df_HH = df_HH[['ID', 'RAUMTYP', 'PLZ', 'GKZ', 'LAGE', 'HHTYP', 'HHGRO', 'P0_10', 'HHGRONEW', 'PKWHH', 'PARKSTR1', 'PARKSTR2', 
        'PARKSTR3', 'GEWHHWO']]
df_HH = df_HH.drop(columns=['HHGRO', 'P0_10'])
df_HH

C:\Users\joey_\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,ID,RAUMTYP,PLZ,GKZ,LAGE,HHTYP,HHGRONEW,PKWHH,PARKSTR1,PARKSTR2,PARKSTR3,GEWHHWO
430,4701032696,1,890,8421,2.0,3,2,2,2.0,1.0,NaN,12357.8
913,4901043164,4,264,3455,5.0,3,2,1,2.0,NaN,NaN,40380.7
1629,8711031162,1,126,11200,2.0,3,4,3,1.0,1.0,1.0,9631.1
743,4711030651,1,229,1062,2.0,3,2,1,2.0,NaN,NaN,18776.1
1144,4901045692,5,552,7331,6.0,3,3,3,2.0,2.0,2.0,22136.0
...,...,...,...,...,...,...,...,...,...,...,...,...
557,4701034083,1,341,6611,2.0,2,1,1,2.0,NaN,NaN,11178.5
1289,4911041414,2,823,9188,3.0,1,1,1,2.0,NaN,NaN,25256.9
1288,4911041410,3,867,9779,5.0,2,1,1,1.0,NaN,NaN,47251.1
1286,4911041369,1,408,5158,4.0,1,1,1,2.0,NaN,NaN,94463.0
910,4901043156,2,212,3353,4.0,2,1,1,2.0,NaN,NaN,25256.9

In [26]:
import math

df_HH.describe()

# LAGE NaN -> fill with mean value 4
df_HH.LAGE = df_HH.LAGE.fillna(math.ceil(df_HH.LAGE.mean()))

In [27]:
# Check lage mean value
print(df_HH.LAGE.mean())
print(math.ceil(df_HH.LAGE.mean()))

df_HH.info()

3.8485245901639344
4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1525 entries, 430 to 910
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        1525 non-null   int64
 1   RAUMTYP   1525 non-null   int64
 2   PLZ       1525 non-null   int64
 3   GKZ       1525 non-null   int64
 4   LAGE      1525 non-null   float64
 5   HHTYP     1525 non-null   int64
 6   HHGRONEW  1525 non-null   int64
 7   PKWHH     1525 non-null   int64
 8   PARKSTR1  1523 non-null   float64
 9   PARKSTR2  611 non-null    float64
 10  PARKSTR3  136 non-null    float64
 11  GEWHHWO   1525 non-null   float64
dtypes: float64(5), int64(7)
memory usage: 154.9 KB

In [33]:
df_HH

              ID  RAUMTYP  PLZ    GKZ  LAGE  HHGRONEW  PKWHH  GEWHHWO
430   4701032696        1  890   8421   2.0         2      2  12357.8
913   4901043164        4  264   3455   5.0         2      1  40380.7
1629  8711031162        1  126  11200   2.0         4      3   9631.1
743   4711030651        1  229   1062   2.0         2      1  18776.1
1144  4901045692        5  552   7331   6.0         3      3  22136.0
...          ...      ...  ...    ...   ...       ...    ...      ...
557   4701034083        1  341   6611   2.0         1      1  11178.5
1289  4911041414        2  823   9188   3.0         1      1  25256.9
1288  4911041410        3  867   9779   5.0         1      1  47251.1
1286  4911041369        1  408   5158   4.0         1      1  94463.0
910   4901043156        2  212   3353   4.0         1      1  25256.9

[1525 rows x 8 columns]

# TANK19

In [10]:
# Import TANK19 Vehicle Data
df_TANK = pd.read_csv('TANK19_UTF.csv', sep=";")
df_TANK

# Delete columns that are not needed
df_TANK = df_TANK.drop(columns=['JAHR', 'PKWORDNR', 'PRIVPKW', 'NUTZUNG', 'TANKINH', 'STRART', 'NORMAL', 'NORMAL1', 'NORMAL2', 
                     'NORMAL3', 'ANORMA', 'ANORME', 'DATANF', 'KMANF', 'INHANF', 'DATEND', 'KMEND', 'INHEND', 
                     'ANZTANK', 'GESLITER', 'FFAHRL', 'HUB_ALT', 'GEWICHT', 'BESCHAFFUNG', 'ANZNUTZER', 'HAUPTNUTZER', 
                     'METHOD', 'AKKU', 'KWH', 'REICHWEITE', 'Lade_anf', 'Lade_end', 'ANZLADEN'])

pd.set_option('display.max_columns', 100)

df_TANK = df_TANK.drop(df_TANK.iloc[:, 15:145], axis = 1)
df_TANK

,IDHH,PKWNR,ANZBUCH,HHGRO,ANZKIND,PKWHH,RAUMTYP,HHTYP,MARKE,TYP,BAUJAHR,HUBRAUM,PS,BENZIN,KMJAHR,ANZTAGE,GESKM,VERB,HUB_KLAS,ALT_KLAS,SEGMENT,ANTRIEB
0,4501022118,1,1,2,0,1,1,2.0,2,Golf 2 l - TDI,2007,2000.0,140.0,NaN,16000.0,61,2228,7.50,4.0,4,3.0,1
1,4501022122,1,1,1,0,2,3,1.0,4,180C Kompressor,2004,1796.0,143.0,NaN,7145.0,61,815,9.00,3.0,4,4.0,2
2,4501022143,1,1,1,0,1,2,2.0,24,Civic,2007,1799.0,140.0,NaN,1800.0,61,388,9.12,3.0,4,3.0,2
3,4501022157,1,1,2,0,1,3,2.0,2,Tiguan,2018,1968.0,150.0,NaN,NaN,61,2101,6.07,3.0,1,7.0,1
4,4501022161,1,1,2,0,1,3,1.0,3,E39 Touring,2002,3000.0,218.0,NaN,30000.0,61,4250,7.05,4.0,4,5.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1661,8911042284,2,2,4,1,2,1,3.0,2,Tiguan,2018,1498.0,110.0,NaN,NaN,61,3123,8.30,2.0,1,7.0,2
1662,8911042421,1,1,3,1,1,1,3.0,14,"Note Accenta 1,2",2016,1198.0,80.0,NaN,9000.0,61,2613,6.05,1.0,1,3.0,2
1663,8911044932,1,1,1,0,1,1,2.0,14,Micra K12,2009,1240.0,65.0,NaN,8000.0,61,707,6.10,1.0,4,2.0,2
1664,8911045497,1,1,2,0,1,1,2.0,31,Venga,2017,1200.0,125.0,NaN,8500.0,61,925,8.82,1.0,1,9.0,2
1665,8911046133,1,1,1,0,1,1,2.0,16,5,2006,1999.0,146.0,NaN,12000.0,61,2627,9.52,3.0,4,10.0,2

In [11]:
# Drop unnecessary columns
df_TANK = df_TANK.drop(columns=['ANZBUCH', 'BAUJAHR', 'HUBRAUM', 'BENZIN'])

# Calculate household without children and drop children
df_TANK['HHGRONEW'] = df_TANK['HHGRO'] - df_TANK['ANZKIND']
df_TANK = df_TANK.sort_values(by=['HHGRO'], ascending=False)
df_TANK = df_TANK[['IDHH', 'PKWNR', 'HHGRO', 'ANZKIND', 'HHGRONEW', 'PKWHH', 'RAUMTYP', 'HHTYP','KMJAHR', 'GESKM', 'SEGMENT']]
df_TANK = df_TANK.drop(columns=['HHGRO', 'ANZKIND'])
df_TANK

,IDHH,PKWNR,HHGRONEW,PKWHH,RAUMTYP,HHTYP,KMJAHR,GESKM,SEGMENT
431,4701032844,4,4,4,5,3.0,10000.0,1953,3.0
651,4701035397,1,5,4,5,4.0,NaN,3406,2.0
1327,4911045423,1,5,4,4,4.0,36000.0,6582,13.0
1629,8911040902,1,2,1,1,3.0,12000.0,1853,10.0
1328,4911045423,2,5,4,4,4.0,10000.0,823,7.0
...,...,...,...,...,...,...,...,...,...
873,4901043298,2,1,2,1,2.0,3000.0,1490,8.0
872,4901043298,1,1,2,1,2.0,12000.0,2000,13.0
867,4901043263,1,1,1,1,1.0,1500.0,389,2.0
862,4901043240,1,1,1,2,2.0,2500.0,680,1.0
1665,8911046133,1,1,1,1,2.0,12000.0,2627,10.0

In [12]:
import math

# HHTYP NaN -> fill with mean value 2
df_TANK.HHTYP = df_TANK.HHTYP.fillna(math.floor(df_TANK.HHTYP.mean()))

# KMJAHR NaN -> fill with mean value 12608
df_TANK.KMJAHR = df_TANK.KMJAHR.fillna(math.floor(df_TANK.KMJAHR.mean()))

# SEGMENT NaN -> fill with mean value 5
df_TANK.SEGMENT = df_TANK.SEGMENT.fillna(math.floor(df_TANK.SEGMENT.mean()))

df_TANK.describe()

,IDHH,PKWNR,HHGRONEW,PKWHH,RAUMTYP,HHTYP,KMJAHR,GESKM,SEGMENT
count,1.666000e+03,1666.000000,1666.000000,1666.000000,1666.000000,1666.000000,1666.000000,1666.000000,1666.000000
mean,5.526377e+09,1.327731,2.024010,1.777311,2.161465,2.103842,12608.308523,2156.567227,5.150660
std,1.606089e+09,0.598827,0.767602,0.858234,1.178273,1.064027,7958.229215,1492.127381,3.760326
min,4.501022e+09,1.000000,1.000000,1.000000,1.000000,1.000000,150.000000,0.000000,1.000000
25%,4.701033e+09,1.000000,2.000000,1.000000,1.000000,1.000000,7500.000000,1074.500000,2.000000
50%,4.901043e+09,1.000000,2.000000,2.000000,2.000000,2.000000,12000.000000,1844.500000,3.000000
75%,4.911042e+09,2.000000,2.000000,2.000000,3.000000,3.000000,15000.000000,2868.000000,8.000000
max,8.911046e+09,6.000000,5.000000,6.000000,5.000000,4.000000,80000.000000,9787.000000,13.000000

In [13]:
# Calculate driven KM per day, per week
df_TANK['DAYKM'] = df_TANK['GESKM'] / 61
df_TANK['WEEKKM'] = df_TANK['DAYKM'] * 7

df_TANK = df_TANK[['IDHH', 'PKWNR', 'HHGRONEW', 'PKWHH', 'RAUMTYP', 'KMJAHR', 'GESKM', 'DAYKM', 'WEEKKM','SEGMENT']]

df_TANK

,IDHH,PKWNR,HHGRONEW,PKWHH,RAUMTYP,KMJAHR,GESKM,DAYKM,WEEKKM,SEGMENT
431,4701032844,4,4,4,5,10000.0,1953,32.016393,224.114754,3.0
651,4701035397,1,5,4,5,12608.0,3406,55.836066,390.852459,2.0
1327,4911045423,1,5,4,4,36000.0,6582,107.901639,755.311475,13.0
1629,8911040902,1,2,1,1,12000.0,1853,30.377049,212.639344,10.0
1328,4911045423,2,5,4,4,10000.0,823,13.491803,94.442623,7.0
...,...,...,...,...,...,...,...,...,...,...
873,4901043298,2,1,2,1,3000.0,1490,24.426230,170.983607,8.0
872,4901043298,1,1,2,1,12000.0,2000,32.786885,229.508197,13.0
867,4901043263,1,1,1,1,1500.0,389,6.377049,44.639344,2.0
862,4901043240,1,1,1,2,2500.0,680,11.147541,78.032787,1.0
1665,8911046133,1,1,1,1,12000.0,2627,43.065574,301.459016,10.0

In [14]:
df_TANK

,IDHH,PKWNR,HHGRONEW,PKWHH,RAUMTYP,KMJAHR,GESKM,DAYKM,WEEKKM,SEGMENT
431,4701032844,4,4,4,5,10000.0,1953,32.016393,224.114754,3.0
651,4701035397,1,5,4,5,12608.0,3406,55.836066,390.852459,2.0
1327,4911045423,1,5,4,4,36000.0,6582,107.901639,755.311475,13.0
1629,8911040902,1,2,1,1,12000.0,1853,30.377049,212.639344,10.0
1328,4911045423,2,5,4,4,10000.0,823,13.491803,94.442623,7.0
...,...,...,...,...,...,...,...,...,...,...
873,4901043298,2,1,2,1,3000.0,1490,24.426230,170.983607,8.0
872,4901043298,1,1,2,1,12000.0,2000,32.786885,229.508197,13.0
867,4901043263,1,1,1,1,1500.0,389,6.377049,44.639344,2.0
862,4901043240,1,1,1,2,2500.0,680,11.147541,78.032787,1.0
1665,8911046133,1,1,1,1,12000.0,2627,43.065574,301.459016,10.0

# W18

In [41]:
# Import W18 Mobility Data
df_W = pd.read_csv('W18.csv', sep=";")
df_W

# Delete columns that are not needed
df_W = df_W.drop(columns=['JAHR', 'TEMP', 'REGEN', 'VM1', 'VM2', 'VM3', 'VM4', 'VM5', 'WEGGEW', 'KMGEW', 
                     'DATGEW'])
df_W

,ID,PERSNR,WOTAG,BERTAG,DATUM,WNRT,ABZEIT,ZWECK,VMDIW,ANZEIT,KM,DAUER,SPEED
0,4501022118,1,7,1,21443,1,1130,5,51,1138,1,8,8
1,4501022118,1,7,1,21443,2,1310,7,51,1320,1,10,6
2,4501022118,1,2,3,21445,1,1030,11,51,1045,03. Jun,15,14
3,4501022118,1,2,3,21445,2,1240,7,51,1257,03. Jun,17,13
4,4501022118,1,3,4,21446,1,1315,6,51,1325,02. Aug,10,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
71184,8911046177,2,4,4,21482,1,630,1,41,700,18,30,36
71185,8911046177,2,4,4,21482,2,1630,4,41,1710,21,40,32
71186,8911046177,2,4,4,21482,3,1830,7,41,1845,6,15,24
71187,8911046177,2,5,5,21483,1,645,1,41,715,18,30,36
71188,8911046177,2,5,5,21483,2,1445,7,41,1520,18,35,31

In [42]:
# replace wrong data in KM
cols = ['KM']
df_W = df_W.apply(lambda col: col.astype(str).str.replace('. Jan', '.1'))
df_W = df_W.apply(lambda col: col.astype(str).str.replace('. Feb', '.2'))
df_W = df_W.apply(lambda col: col.astype(str).str.replace('. Mrz', '.3'))
df_W = df_W.apply(lambda col: col.astype(str).str.replace('. Apr', '.4'))
df_W = df_W.apply(lambda col: col.astype(str).str.replace('. Mai', '.5'))
df_W = df_W.apply(lambda col: col.astype(str).str.replace('. Jun', '.6'))
df_W = df_W.apply(lambda col: col.astype(str).str.replace('. Jul', '.7'))
df_W = df_W.apply(lambda col: col.astype(str).str.replace('. Aug', '.8'))
df_W = df_W.apply(lambda col: col.astype(str).str.replace('. Sep', '.9'))

In [43]:
pd.set_option('display.max_rows', 100)

# Change column type to float
df_W['ID'] = df_W['ID'].astype(float)
df_W['PERSNR'] = df_W['PERSNR'].astype(int)
df_W['WOTAG'] = df_W['WOTAG'].astype(int)
df_W['BERTAG'] = df_W['BERTAG'].astype(int)
df_W['DATUM'] = df_W['DATUM'].astype(int)
df_W['WNRT'] = df_W['WNRT'].astype(int)
df_W['ABZEIT'] = df_W['ABZEIT'].astype(int)
df_W['ZWECK'] = df_W['ZWECK'].astype(int)
df_W['VMDIW'] = df_W['VMDIW'].astype(int)
df_W['ANZEIT'] = df_W['ANZEIT'].astype(int)
df_W['KM'] = df_W['KM'].astype(float)
df_W['DAUER'] = df_W['DAUER'].astype(int)
df_W['SPEED'] = df_W['SPEED'].astype(int)

In [45]:
# Take only VMDIW = 41 (driver of vehicle)
print(df_W.groupby('VMDIW').count())
df_W.shape # 71189
df_W = df_W.loc[df_W["VMDIW"] == 41]
df_W.shape # 33318

print(df_W.groupby('VMDIW').count())
df_W

          ID  PERSNR  WOTAG  BERTAG  DATUM   WNRT  ABZEIT  ZWECK  ANZEIT  \
VMDIW
11     13921   13921  13921   13921  13921  13921   13921  13921   13921
21      7128    7128   7128    7128   7128   7128    7128   7128    7128
22       916     916    916     916    916    916     916    916     916
31       454     454    454     454    454    454     454    454     454
41     33318   33318  33318   33318  33318  33318   33318  33318   33318
51      8136    8136   8136    8136   8136   8136    8136   8136    8136
61      2342    2342   2342    2342   2342   2342    2342   2342    2342
62        84      84     84      84     84     84      84     84      84
71      2283    2283   2283    2283   2283   2283    2283   2283    2283
72      2061    2061   2061    2061   2061   2061    2061   2061    2061
73       232     232    232     232    232    232     232    232     232
81        29      29     29      29     29     29      29     29      29
91       285     285    285     285    285    285     285    285     285

          KM  DAUER  SPEED
VMDIW
11     13921  13921  13921
21      7128   7128   7128
22       916    916    916
31       454    454    454
41     33318  33318  33318
51      8136   8136   8136
61      2342   2342   2342
62        84     84     84
71      2283   2283   2283
72      2061   2061   2061
73       232    232    232
81        29     29     29
91       285    285    285
          ID  PERSNR  WOTAG  BERTAG  DATUM   WNRT  ABZEIT  ZWECK  ANZEIT  \
VMDIW
41     33318   33318  33318   33318  33318  33318   33318  33318   33318

          KM  DAUER  SPEED
VMDIW
41     33318  33318  33318

,ID,PERSNR,WOTAG,BERTAG,DATUM,WNRT,ABZEIT,ZWECK,VMDIW,ANZEIT,KM,DAUER,SPEED
11,4.501022e+09,2,7,1,21443,1,1130,5,41,1138,1.0,8,8
12,4.501022e+09,2,7,1,21443,2,1310,7,41,1320,1.0,10,6
13,4.501022e+09,2,1,2,21444,1,1420,4,41,1425,1.0,5,12
14,4.501022e+09,2,1,2,21444,2,1450,7,41,1455,1.0,5,12
15,4.501022e+09,2,2,3,21445,1,1030,6,41,1045,3.6,15,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
71184,8.911046e+09,2,4,4,21482,1,630,1,41,700,18.0,30,36
71185,8.911046e+09,2,4,4,21482,2,1630,4,41,1710,21.0,40,32
71186,8.911046e+09,2,4,4,21482,3,1830,7,41,1845,6.0,15,24
71187,8.911046e+09,2,5,5,21483,1,645,1,41,715,18.0,30,36
71188,8.911046e+09,2,5,5,21483,2,1445,7,41,1520,18.0,35,31

In [46]:
# Calculate number of unique ids
idtest = df_W['ID']
print((~idtest.duplicated()).sum()) # --- 1495 unique ids

1495

In [47]:
# Drop more irrelevant columns
df_W = df_W.drop(columns=['DATUM', 'DAUER', 'SPEED'])

In [48]:
df_W

,ID,PERSNR,WOTAG,BERTAG,WNRT,ABZEIT,ZWECK,VMDIW,ANZEIT,KM
11,4.501022e+09,2,7,1,1,1130,5,41,1138,1.0
12,4.501022e+09,2,7,1,2,1310,7,41,1320,1.0
13,4.501022e+09,2,1,2,1,1420,4,41,1425,1.0
14,4.501022e+09,2,1,2,2,1450,7,41,1455,1.0
15,4.501022e+09,2,2,3,1,1030,6,41,1045,3.6
...,...,...,...,...,...,...,...,...,...,...
71184,8.911046e+09,2,4,4,1,630,1,41,700,18.0
71185,8.911046e+09,2,4,4,2,1630,4,41,1710,21.0
71186,8.911046e+09,2,4,4,3,1830,7,41,1845,6.0
71187,8.911046e+09,2,5,5,1,645,1,41,715,18.0
71188,8.911046e+09,2,5,5,2,1445,7,41,1520,18.0

# Processing Data

In [ ]:
# Sort by ID in TANK data set
df_TANK.sort_values(by=['IDHH'], inplace=True)

In [50]:
import numpy as np

df_TANK['BATTERY'] = np.nan
df_TANK['POWER'] = np.nan
df_TANK['ENERGY'] = np.nan
df_TANK

# Add segment specific attributes: battery, power, and energy consumption
# Segment 1-4: Small, 5-8: Medium, 9-13: Large
def f_BATTERY(row):
    if row['SEGMENT'] == 1.0 or row['SEGMENT'] == 2.0 or row['SEGMENT'] == 3.0 or row['SEGMENT'] == 4.0:
        val = 41
    elif row['SEGMENT'] == 5.0 or row['SEGMENT'] == 6.0 or row['SEGMENT'] == 7.0 or row['SEGMENT'] == 8.0:
        val = 50
    else:
        val = 64
    return val

def f_POWER(row):
    if row['SEGMENT'] == 1.0 or row['SEGMENT'] == 2.0 or row['SEGMENT'] == 3.0 or row['SEGMENT'] == 4.0:
        val = 80
    elif row['SEGMENT'] == 5.0 or row['SEGMENT'] == 6.0 or row['SEGMENT'] == 7.0 or row['SEGMENT'] == 8.0:
        val = 239
    else:
        val = 150
    return val

def f_ENERGY(row):
    if row['SEGMENT'] == 1.0 or row['SEGMENT'] == 2.0 or row['SEGMENT'] == 3.0 or row['SEGMENT'] == 4.0:
        val = 17.2
    elif row['SEGMENT'] == 5.0 or row['SEGMENT'] == 6.0 or row['SEGMENT'] == 7.0 or row['SEGMENT'] == 8.0:
        val = 14.7
    else:
        val = 16.2
    return val

df_TANK['BATTERY'] = df_TANK.apply(f_BATTERY, axis=1)
df_TANK['POWER'] = df_TANK.apply(f_POWER, axis=1)
df_TANK['ENERGY'] = df_TANK.apply(f_ENERGY, axis=1)

print(df_TANK.head(100))

          IDHH  PKWNR  HHGRONEW  PKWHH  RAUMTYP   KMJAHR  GESKM       TAGKM  \
0   4501022118      1         2      1        1  16000.0   2228   36.524590
1   4501022122      1         1      2        3   7145.0    815   13.360656
2   4501022143      1         1      1        2   1800.0    388    6.360656
3   4501022157      1         2      1        3  12608.0   2101   34.442623
4   4501022161      1         2      1        3  30000.0   4250   69.672131
7   4501022162      3         2      3        3   6000.0   1467   24.049180
6   4501022162      1         2      3        3  14000.0   1286   21.081967
5   4501022162      2         2      3        3  12000.0   1222   20.032787
8   4501022169      1         1      3        2  15000.0   3349   54.901639
10  4501022169      2         1      3        2   1500.0     43    0.704918
9   4501022169      3         1      3        2    300.0     47    0.770492
12  4501022174      1         2      2        1  15000.0   2634   43.180328
11  4501022174      2         2      2        1  14000.0    845   13.852459
13  4501022191      1         2      1        1   8800.0   1457   23.885246
14  4501022202      1         2      1        1   9000.0   2217   36.344262
15  4501022205      2         5      3        3   6000.0   1159   19.000000
16  4501022205      1         5      3        3  14000.0   2286   37.475410
17  4501022207      1         2      1        1  16000.0   2668   43.737705
18  4501022224      1         2      1        5  12608.0   3872   63.475410
19  4501022228      1         2      1        1   9000.0    864   14.163934
20  4501022246      1         2      1        3   9650.0   1267   20.770492
21  4501022259      1         2      2        4  12608.0   3401   55.754098
22  4501022261      1         2      2        1   8336.0   1935   31.721311
24  4501022262      1         2      2        1  20000.0   3419   56.049180
23  4501022262      2         2      2        1  12000.0   2940   48.196721
25  4501022276      1         1      1        5  12000.0   2540   41.639344
26  4501022292      1         2      1        1  10900.0   1217   19.950820
28  4501022295      1         2      2        3   9000.0   2976   48.786885
27  4501022295      2         2      2        3   4500.0    936   15.344262
29  4501022305      1         2      1        2  15000.0   2387   39.131148
30  4501022308      1         1      1        1   3700.0    613   10.049180
31  4501022311      1         2      2        3  12000.0   3067   50.278689
32  4501022311      2         2      2        3   5700.0    332    5.442623
33  4501022341      1         2      1        1  11000.0   1484   24.327869
34  4501022356      1         1      1        4   5000.0    576    9.442623
36  4501022358      1         3      2        3  30000.0   6207  101.754098
35  4501022358      2         3      2        3  20000.0   2745   45.000000
37  4501022361      1         1      1        2   8000.0    669   10.967213
38  4501022369      1         1      1        2   6000.0    950   15.573770
39  4501022371      1         2      1        3   5000.0   1023   16.770492
40  4501022379      1         2      3        1  60000.0   1557   25.524590
41  4501022379      2         2      3        1  60000.0   8811  144.442623
42  4501022379      3         2      3        1    150.0      0    0.000000
44  4501022389      2         2      2        2   5000.0    847   13.885246
43  4501022389      1         2      2        2   8700.0   1452   23.803279
45  4501022393      1         3      3        2  12608.0   2381   39.032787
46  4501022510      1         2      1        1   8500.0    912   14.950820
47  4501022529      1         1      1        4   8000.0    871   14.278689
48  4501022530      1         2      2        3  27000.0   4456   73.049180
49  4501022530      2         2      2        3  12000.0   1926   31.573770
51  4501022532      2         3      2        2   3700.0   1131   18.540984
50  4501022532      1         3      2        2  20000.0   3488   57.180328
52  4501022537      1         3      1        2  14000.0   1653   27.098361
53  4501022538      1         2      1        3  11000.0   1719   28.180328
54  4501022542      1         1      1        3   6500.0    952   15.606557
55  4501022569      1         2      1        1   7000.0   1226   20.098361
57  4501022589      3         3      3        3  14500.0   2695   44.180328
58  4501022589      1         3      3        3  23000.0   3617   59.295082
56  4501022589      2         3      3        3  20000.0   3887   63.721311
60  4501022613      1         2      2        3  12500.0   1365   22.377049
59  4501022613      2         2      2        3   8000.0   1662   27.245902
62  4501022620      3         3      3        2  12608.0      0    0.000000
61  4501022620      2         3      3        2  11500.0   1901   31.163934
63  4501022620      1         3      3        2  50600.0   8437  138.311475
64  4501022621      1         1      1        3   6800.0   1237   20.278689
65  4501022635      1         2      1        1   5000.0    747   12.245902
66  4501022638      1         2      1        1  21000.0   4146   67.967213
67  4501022653      1         1      1        3  11000.0   1892   31.016393
68  4501022766      1         1      1        1   5000.0   1091   17.885246
69  4501022773      1         1      1        4  10960.0   1555   25.491803
70  4501022806      1         1      1        2  12608.0    978   16.032787
71  4501022827      1         3      5        5  12000.0   2599   42.606557
72  4501022870      1         2      1        2  14000.0   2817   46.180328
73  4501022877      1         2      3        2  15000.0    751   12.311475
74  4501022877      3         2      3        2   1000.0     60    0.983607
75  4501022877      2         2      3        2  14800.0   4320   70.819672
76  4501022878      2         3      2        4  10022.0   1635   26.803279
77  4501022878      1         3      2        4  12640.0   2516   41.245902
79  4501022900      1         2      2        1   4500.0    458    7.508197
78  4501022900      2         2      2        1   4500.0    473    7.754098
80  4501022912      1         2      2        4  13000.0   2163   35.459016
81  4501022912      2         2      2        4  11000.0   2199   36.049180
82  4501023004      1         2      2        4  15413.0   3045   49.918033
83  4501023004      2         2      2        4  10500.0   1734   28.426230
84  4501023043      1         1      1        1   5000.0    451    7.393443
85  4501023048      1         2      1        1  12000.0   1484   24.327869
86  4501023049      1         2      2        2  14000.0   1663   27.262295
87  4501023049      2         2      2        2  11000.0   1742   28.557377
88  4501023052      1         2      2        3  11000.0   3118   51.114754
89  4501023052      2         2      2        3  11000.0   2277   37.327869
90  4501023106      2         2      2        5   4000.0   1305   21.393443
91  4501023106      1         2      2        5  15000.0   3066   50.262295
92  4501023114      1         1      1        3   4000.0    340    5.573770
93  4501023115      1         1      1        5   5000.0   1375   22.540984
94  4501023131      1         3      1        1  10000.0   1528   25.049180
95  4501023138      1         2      1        1   7000.0    358    5.868852
96  4501023143      1         1      1        3   9000.0    620   10.163934
97  4501023148      1         2      1        1  10000.0   1943   31.852459
98  4501023167      1         2      1        1  10000.0    909   14.901639
99  4501023170      1         2      1        1  10000.0   1058   17.344262

        WOCHEKM  SEGMENT  BATTERY  POWER  ENERGY
0    255.672131      3.0       41     80    17.2
1     93.524590      4.0       41     80    17.2
2     44.524590      3.0       41     80    17.2
3    241.098361      7.0       50    239    14.7
4    487.704918      5.0       50    239    14.7
7    168.344262      7.0       50    239    14.7
6    147.573770      4.0       41     80    17.2
5    140.229508      4.0       41     80    17.2
8    384.311475      3.0       41     80    17.2
10     4.934426      6.0       50    239    14.7
9      5.393443      4.0       41     80    17.2
12   302.262295      3.0       41     80    17.2
11    96.967213      4.0       41     80    17.2
13   167.196721      3.0       41     80    17.2
14   254.409836      5.0       50    239    14.7
15   133.000000      3.0       41     80    17.2
16   262.327869      9.0       64    150    16.2
17   306.163934      2.0       41     80    17.2
18   444.327869     11.0       64    150    16.2
19    99.147541      2.0       41     80    17.2
20   145.393443      3.0       41     80    17.2
21   390.278689      2.0       41     80    17.2
22   222.049180      3.0       41     80    17.2
24   392.344262     10.0       64    150    16.2
23   337.377049      1.0       41     80    17.2
25   291.475410      3.0       41     80    17.2
26   139.655738      2.0       41     80    17.2
28   341.508197     11.0       64    150    16.2
27   107.409836      3.0       41     80    17.2
29   273.918033      3.0       41     80    17.2
30    70.344262      4.0       41     80    17.2
31   351.950820      4.0       41     80    17.2
32    38.098361      2.0       41     80    17.2
33   170.295082     13.0       64    150    16.2
34    66.098361      1.0       41     80    17.2
36   712.278689      3.0       41     80    17.2
35   315.000000      4.0       41     80    17.2
37    76.770492     13.0       64    150    16.2
38   109.016393      3.0       41     80    17.2
39   117.393443      3.0       41     80    17.2
40   178.672131      4.0       41     80    17.2
41  1011.098361      4.0       41     80    17.2
42     0.000000      5.0       50    239    14.7
44    97.196721      2.0       41     80    17.2
43   166.622951      2.0       41     80    17.2
45   273.229508      3.0       41     80    17.2
46   104.655738      9.0       64    150    16.2
47    99.950820      9.0       64    150    16.2
48   511.344262      4.0       41     80    17.2
49   221.016393      8.0       50    239    14.7
51   129.786885      2.0       41     80    17.2
50   400.262295      7.0       50    239    14.7
52   189.688525      7.0       50    239    14.7
53   197.262295     13.0       64    150    16.2
54   109.245902     11.0       64    150    16.2
55   140.688525     13.0       64    150    16.2
57   309.262295      2.0       41     80    17.2
58   415.065574      4.0       41     80    17.2
56   446.049180      3.0       41     80    17.2
60   156.639344     13.0       64    150    16.2
59   190.721311      3.0       41     80    17.2
62     0.000000      2.0       41     80    17.2
61   218.147541      3.0       41     80    17.2
63   968.180328      4.0       41     80    17.2
64   141.950820      3.0       41     80    17.2
65    85.721311      3.0       41     80    17.2
66   475.770492     10.0       64    150    16.2
67   217.114754      4.0       41     80    17.2
68   125.196721      3.0       41     80    17.2
69   178.442623      3.0       41     80    17.2
70   112.229508      3.0       41     80    17.2
71   298.245902      2.0       41     80    17.2
72   323.262295      3.0       41     80    17.2
73    86.180328      4.0       41     80    17.2
74     6.885246      3.0       41     80    17.2
75   495.737705     11.0       64    150    16.2
76   187.622951      7.0       50    239    14.7
77   288.721311      4.0       41     80    17.2
79    52.557377      1.0       41     80    17.2
78    54.278689      4.0       41     80    17.2
80   248.213115      3.0       41     80    17.2
81   252.344262      3.0       41     80    17.2
82   349.426230     11.0       64    150    16.2
83   198.983607      1.0       41     80    17.2
84    51.754098      2.0       41     80    17.2
85   170.295082     10.0       64    150    16.2
86   190.836066     11.0       64    150    16.2
87   199.901639      1.0       41     80    17.2
88   357.803279     11.0       64    150    16.2
89   261.295082      3.0       41     80    17.2
90   149.754098      2.0       41     80    17.2
91   351.836066      9.0       64    150    16.2
92    39.016393      3.0       41     80    17.2
93   157.786885      1.0       41     80    17.2
94   175.344262     10.0       64    150    16.2
95    41.081967      2.0       41     80    17.2
96    71.147541      3.0       41     80    17.2
97   222.967213      4.0       41     80    17.2
98   104.311475     13.0       64    150    16.2
99   121.409836      9.0       64    150    16.2

In [19]:
# ID display option
pd.options.display.float_format = '{:20,.2f}'.format
df_W['ID'] = df_W['ID'].astype(np.int64)

# Add PKW number and driver count to each route
df_W['PKWNR'] = np.nan

# For all households that have PKWHH = 1, PKWNR = 1
def f_PKWNR(row):
    idhh = row[0]
    value = df_TANK.loc[df_TANK['IDHH'] == idhh, 'PKWHH']
    if value.empty:
        val = -1
    else:
        value_pkwnr = value.values[0]
        if value_pkwnr == 1:
            val = 1
        else:
            val = 0
    return val
    
df_W['PKWNR'] = df_W.apply(f_PKWNR, axis=1)
df_W.head(100)

,ID,PERSNR,WOTAG,BERTAG,DATUM,WNRT,ABZEIT,ZWECK,VMDIW,ANZEIT,KM,DAUER,SPEED,PKWNR
11,4501022118,2,7,1,21443,1,1130,5,41,1138,1.00,8,8,1
12,4501022118,2,7,1,21443,2,1310,7,41,1320,1.00,10,6,1
13,4501022118,2,1,2,21444,1,1420,4,41,1425,1.00,5,12,1
14,4501022118,2,1,2,21444,2,1450,7,41,1455,1.00,5,12,1
15,4501022118,2,2,3,21445,1,1030,6,41,1045,3.60,15,14,1
16,4501022118,2,2,3,21445,2,1050,4,41,1115,5.50,25,13,1
17,4501022118,2,2,3,21445,3,1215,6,41,1240,5.50,25,13,1
18,4501022118,2,2,3,21445,4,1245,7,41,1257,3.60,12,18,1
19,4501022118,2,2,3,21445,5,1530,5,41,1550,6.90,20,21,1
20,4501022118,2,2,3,21445,6,1840,7,41,1855,6.90,15,28,1
21,4501022118,2,3,4,21446,1,1315,6,41,1325,2.80,10,17,1
22,4501022118,2,3,4,21446,2,1530,7,41,1545,2.80,15,11,1
23,4501022118,2,4,5,21447,1,1030,4,41,1105,12.60,35,22,1
24,4501022118,2,4,5,21447,2,1245,7,41,1315,12.40,30,25,1
25,4501022118,2,5,6,21448,1,1000,11,41,1025,25.10,25,60,1
26,4501022118,2,5,6,21448,2,1140,7,41,1210,25.60,30,51,1
27,4501022118,2,5,6,21448,3,1230,5,41,1240,2.20,10,13,1
28,4501022118,2,5,6,21448,4,1445,7,41,1500,2.20,15,9,1
29,4501022118,2,6,7,21449,1,1100,9,41,1900,736.00,480,92,1
30,4501022122,1,1,1,21437,1,630,6,41,730,30.00,60,30,0
31,4501022122,1,1,1,21437,2,745,7,41,836,30.00,51,35,0
32,4501022122,1,1,1,21437,3,1900,6,41,1930,30.00,30,60,0
33,4501022122,1,1,1,21437,4,1931,7,41,2000,30.00,29,62,0
34,4501022122,1,2,2,21438,1,630,6,41,730,30.00,60,30,0
35,4501022122,1,2,2,21438,2,735,7,41,830,30.00,55,33,0
36,4501022122,1,2,2,21438,3,1000,6,41,1030,15.00,30,30,0
37,4501022122,1,2,2,21438,4,1040,7,41,1115,15.00,35,26,0
38,4501022122,1,2,2,21438,5,1900,6,41,1935,30.00,35,51,0
39,4501022122,1,2,2,21438,6,1955,7,41,2030,30.00,35,51,0
40,4501022122,1,3,3,21439,1,630,6,41,715,30.00,45,40,0
41,4501022122,1,3,3,21439,2,740,7,41,825,30.00,45,40,0
42,4501022122,1,3,3,21439,3,1900,6,41,1930,30.00,30,60,0
43,4501022122,1,3,3,21439,4,2000,7,41,2030,30.00,30,60,0
44,4501022122,1,4,4,21440,1,700,6,41,730,30.00,30,60,0
45,4501022122,1,4,4,21440,2,731,7,41,800,30.00,29,62,0
68,4501022123,1,4,4,21440,3,1200,5,41,1245,30.00,45,40,-1
69,4501022123,1,4,4,21440,4,2025,7,41,2110,30.00,45,40,-1
70,4501022123,1,5,5,21441,1,1345,11,41,1355,5.00,10,30,-1
71,4501022123,1,5,5,21441,2,1435,7,41,1450,5.00,15,20,-1
106,4501022143,1,1,2,21479,3,1347,4,41,1426,24.00,39,37,1
107,4501022143,1,1,2,21479,4,1530,7,41,1610,26.00,40,39,1
110,4501022143,1,3,4,21481,1,1415,4,41,1445,26.00,30,52,1
111,4501022143,1,3,4,21481,2,1530,7,41,1600,26.00,30,52,1
119,4501022157,1,1,3,21479,1,930,5,41,1000,17.00,30,34,1
129,4501022157,1,4,6,21482,3,1610,11,41,1630,8.50,20,26,1
130,4501022157,1,4,6,21482,4,1710,7,41,1735,8.00,25,19,1
133,4501022157,1,5,7,21483,3,1350,5,41,1405,6.50,15,26,1
134,4501022157,1,5,7,21483,4,1525,7,41,1540,6.00,15,24,1
136,4501022157,2,7,2,21478,2,1735,7,41,1845,75.00,70,64,1
137,4501022157,2,1,3,21479,1,930,5,41,1000,17.00,30,34,1
138,4501022157,2,1,3,21479,2,1110,5,41,1130,6.00,20,18,1
139,4501022157,2,1,3,21479,3,1230,4,41,1245,6.00,15,24,1
140,4501022157,2,1,3,21479,4,1315,7,41,1400,18.00,45,24,1
141,4501022157,2,2,4,21480,1,930,4,41,935,1.10,5,13,1
142,4501022157,2,2,4,21480,2,940,7,41,945,1.20,5,14,1
143,4501022157,2,2,4,21480,3,1040,4,41,1120,17.00,40,26,1
144,4501022157,2,2,4,21480,4,1205,7,41,1245,17.00,40,26,1
145,4501022157,2,3,5,21481,1,1315,4,41,1350,20.10,35,34,1
146,4501022157,2,3,5,21481,2,1420,7,41,1505,20.10,45,27,1
147,4501022157,2,4,6,21482,1,1020,4,41,1125,25.00,65,23,1
148,4501022157,2,4,6,21482,2,1240,7,41,1345,25.10,65,23,1
151,4501022157,2,5,7,21483,1,935,11,41,1010,16.50,35,28,1
152,4501022157,2,5,7,21483,2,1050,7,41,1125,17.00,35,29,1
175,4501022161,2,4,2,21475,1,500,1,41,615,90.00,75,72,1
176,4501022161,2,4,2,21475,2,1530,7,41,1640,90.00,70,77,1
177,4501022161,2,4,2,21475,3,1820,5,41,1835,4.20,15,17,1
178,4501022161,2,4,2,21475,4,2045,7,41,2100,4.20,15,17,1
179,4501022161,2,5,3,21476,1,1300,4,41,1315,4.00,15,16,1
180,4501022161,2,5,3,21476,2,1330,7,41,1345,4.00,15,16,1
181,4501022161,2,5,3,21476,3,1445,11,41,1452,2.50,7,21,1
182,4501022161,2,5,3,21476,4,1630,4,41,1640,2.00,10,12,1
183,4501022161,2,5,3,21476,5,1730,7,41,1745,4.20,15,17,1
189,4501022161,2,1,6,21479,1,500,1,41,615,90.00,75,72,1
190,4501022161,2,1,6,21479,2,1530,7,41,1645,90.00,75,72,1
191,4501022161,2,2,7,21480,1,500,1,41,610,90.00,70,77,1
192,4501022161,2,2,7,21480,2,1535,7,41,1630,90.00,55,98,1
193,4501022161,2,2,7,21480,3,1840,5,41,1855,4.20,15,17,1
194,4501022161,2,2,7,21480,4,2055,7,41,2105,4.20,10,25,1
214,4501022162,2,4,1,21475,1,740,11,41,755,10.00,15,40,0
215,4501022162,2,4,1,21475,2,920,7,41,935,10.00,15,40,0
219,4501022162,2,5,2,21476,1,635,6,41,655,12.00,20,36,0
222,4501022162,2,5,2,21476,4,945,4,41,950,2.00,5,24,0
223,4501022162,2,5,2,21476,5,1025,7,41,1030,2.00,5,24,0
224,4501022162,2,5,2,21476,6,1325,6,41,1345,11.00,20,33,0
225,4501022162,2,5,2,21476,7,1346,7,41,1405,11.00,19,35,0
228,4501022162,2,1,5,21479,1,750,11,41,825,24.00,35,41,0
229,4501022162,2,1,5,21479,2,945,4,41,1030,22.00,45,29,0
230,4501022162,2,1,5,21479,3,1040,7,41,1045,2.00,5,24,0
231,4501022162,2,1,5,21479,4,1435,6,41,1442,1.50,7,13,0
232,4501022162,2,1,5,21479,5,1500,7,41,1515,1.80,15,7,0
237,4501022162,2,2,6,21480,1,740,11,41,755,10.00,15,40,0
238,4501022162,2,2,6,21480,2,900,7,41,915,10.00,15,40,0
243,4501022162,2,3,7,21481,2,1100,5,41,1110,8.00,10,48,0
244,4501022162,2,3,7,21481,3,1145,7,41,1150,8.00,5,96,0
245,4501022162,2,3,7,21481,4,1500,5,41,1505,1.20,5,14,0
246,4501022162,2,3,7,21481,5,1630,7,41,1635,1.20,5,14,0
247,4501022162,2,3,7,21481,6,1700,5,41,1710,5.00,10,30,0
248,4501022162,2,3,7,21481,7,1810,7,41,1820,5.00,10,30,0
278,4501022162,4,4,1,21475,5,1615,6,41,1625,8.00,10,48,0
279,4501022162,4,4,1,21475,6,1630,7,41,1640,8.00,10,48,0

# PKWNR Editing

In [21]:
# Summary
df_HH_copy = df_HH #.....------------ 1525 households
#df_HH_copy
df_TANK_copy = df_TANK #------------- 1666 logs
#df_TANK_copy
df_W_copy = df_W # ------------------- 33318 trips --- 1495 unique ids/households
#df_W_copy

ids = df_W_copy['ID']

# Get all unique ids from W data set and loop through each household to assign vehicles to persons
ids_unique = ids.drop_duplicates()

pkw_values = []

for i in ids_unique:
    test_id = i
    print(f"ID: {test_id}")
    test = df_W_copy.loc[df_W_copy['ID'] == test_id]
    
    # Get person count and vehicle count
    persnrs = df_W_copy.loc[df_W_copy['ID'] == test_id, 'PERSNR'].drop_duplicates()
    perscount = persnrs.count()
    pkwnrs = df_TANK_copy.loc[df_TANK_copy['IDHH'] == test_id, 'PKWNR']
    if(pkwnrs.empty):
        for j in test.values:
            pkw_values.append(0)
        continue
    pkwcount = df_TANK_copy.loc[df_TANK_copy['IDHH'] == test_id, 'PKWHH'].values[0]
    print(persnrs)
    print(perscount)
    print(pkwnrs)
    print(pkwcount)
    
    for j in test.values:
        # If perscount == 1, then all persons have the same car
        if perscount == 1:
            pkw_values.append(pkwnrs.values[0])
            continue

        # If perscount == 2 and 2 or more vehicles: assign vehicles in order
        if (perscount == 2 and pkwcount == 2) or (perscount == 2 and pkwcount == 3) or (perscount == 2 and pkwcount == 4) or (perscount == 2 and pkwcount == 5) or (perscount == 2 and pkwcount == 6):
            try:
                if j[1] == persnrs.values[0]:
                    pkw_values.append(pkwnrs.values[0])
                else:
                    pkw_values.append(pkwnrs.values[1])
            except:
                # Error: 2 persons but only 1 car, take first car for second person
                pkw_values.append(pkwnrs.values[0])
                
                continue
            continue
            
        #if perscount == 3 and 3 or more vehicles: assign vehicles in order
        if (perscount == 3 and pkwcount == 3) or (perscount == 3 and pkwcount == 4) or (perscount == 3 and pkwcount == 5) or (perscount == 3 and pkwcount == 6):
            try:
                if j[1] == persnrs.values[0]:
                    pkw_values.append(pkwnrs.values[0])
                elif j[1] == persnrs.values[1]:
                    pkw_values.append(pkwnrs.values[1])
                else:
                    pkw_values.append(pkwnrs.values[2])
            except:
                # Error: 3 persons but < 3 cars, take first car for second and third person
                pkw_values.append(pkwnrs.values[0])
                continue
            continue
            
        #if perscount == 4 and 4 or more vehicles: assign vehicles in order
        if (perscount == 4 and pkwcount == 4) or (perscount == 4 and pkwcount == 5) or (perscount == 4 and pkwcount == 6):
            try:
                if j[1] == persnrs.values[0]:
                    pkw_values.append(pkwnrs.values[0])
                elif j[1] == persnrs.values[1]:
                    pkw_values.append(pkwnrs.values[1])
                elif j[1] == persnrs.values[2]:
                    pkw_values.append(pkwnrs.values[2])
                else:
                    pkw_values.append(pkwnrs.values[3])
            except:
                # Error: 4 persons but < 4 cars, take first car for every other person
                pkw_values.append(-4)
                continue
            continue
            
        #if perscount == 5 and 5 or more vehicles: assign vehicles in order
        if (perscount == 5 and pkwcount == 5) or (perscount == 5 and pkwcount == 6):
            try:
                if j[1] == persnrs.values[0]:
                    pkw_values.append(pkwnrs.values[0])
                elif j[1] == persnrs.values[1]:
                    pkw_values.append(pkwnrs.values[1])
                elif j[1] == persnrs.values[2]:
                    pkw_values.append(pkwnrs.values[2])
                elif j[1] == persnrs.values[3]:
                    pkw_values.append(pkwnrs.values[3])
                else:
                    pkw_values.append(pkwnrs.values[4])
            except:
                # Error: 5 persons but < 5 cars, take first car for every other person
                pkw_values.append(-5)
                continue
            continue
            
        #if perscount == 6 and 6 or more vehicles: assign vehicles in order
        if (perscount == 6 and pkwcount == 6):
            try:
                if j[1] == persnrs.values[0]:
                    pkw_values.append(pkwnrs.values[0])
                elif j[1] == persnrs.values[1]:
                    pkw_values.append(pkwnrs.values[1])
                elif j[1] == persnrs.values[2]:
                    pkw_values.append(pkwnrs.values[2])
                elif j[1] == persnrs.values[3]:
                    pkw_values.append(pkwnrs.values[3])
                elif j[1] == persnrs.values[4]:
                    pkw_values.append(pkwnrs.values[4])
                else:
                    pkw_values.append(pkwnrs.values[5])
            except:
                # Error: 6 persons but < 6 cars, take first car for every other person
                pkw_values.append(-6)
                continue
            continue
            
        pkw_values.append(1)

        
print(pkw_values)

ID: 4501022118
11    2
Name: PERSNR, dtype: int32
1
0    1
Name: PKWNR, dtype: int64
1
ID: 4501022122
30    1
Name: PERSNR, dtype: int32
1
1    1
Name: PKWNR, dtype: int64
2
ID: 4501022123
ID: 4501022143
106    1
Name: PERSNR, dtype: int32
1
2    1
Name: PKWNR, dtype: int64
1
ID: 4501022157
119    1
136    2
Name: PERSNR, dtype: int32
2
3    1
Name: PKWNR, dtype: int64
1
ID: 4501022161
175    2
Name: PERSNR, dtype: int32
1
4    1
Name: PKWNR, dtype: int64
1
ID: 4501022162
214    2
278    4
Name: PERSNR, dtype: int32
2
5    2
6    1
7    3
Name: PKWNR, dtype: int64
3
ID: 4501022174
318    1
Name: PERSNR, dtype: int32
1
12    1
11    2
Name: PKWNR, dtype: int64
2
ID: 4501022191
427    1
Name: PERSNR, dtype: int32
1
13    1
Name: PKWNR, dtype: int64
1
ID: 4501022202
491    1
520    2
Name: PERSNR, dtype: int32
2
14    1
Name: PKWNR, dtype: int64
1
ID: 4501022205
562    1
622    3
659    5
Name: PERSNR, dtype: int32
3
15    2
16    1
Name: PKWNR, dtype: int64
3
ID: 4501022207
692    1
Name: PERSNR, dtype: int32
1
17    1
Name: PKWNR, dtype: int64
1
ID: 4501022224
749    1
781    2
Name: PERSNR, dtype: int32
2
18    1
Name: PKWNR, dtype: int64
1
ID: 4501022228
798    1
812    2
Name: PERSNR, dtype: int32
2
19    1
Name: PKWNR, dtype: int64
1
ID: 4501022246
826    1
838    2
Name: PERSNR, dtype: int32
2
20    1
Name: PKWNR, dtype: int64
1
ID: 4501022259
916    1
945    2
Name: PERSNR, dtype: int32
2
21    1
Name: PKWNR, dtype: int64
2
ID: 4501022261
959    1
975    2
Name: PERSNR, dtype: int32
2
22    1
Name: PKWNR, dtype: int64
2
ID: 4501022262
1004    1
1038    2
Name: PERSNR, dtype: int32
2
23    2
24    1
Name: PKWNR, dtype: int64
2
ID: 4501022268
ID: 4501022275
ID: 4501022276
1198    1
Name: PERSNR, dtype: int32
1
25    1
Name: PKWNR, dtype: int64
1
ID: 4501022292
1214    1
Name: PERSNR, dtype: int32
1
26    1
Name: PKWNR, dtype: int64
1
ID: 4501022295
1255    1
1313    2
Name: PERSNR, dtype: int32
2
27    2
28    1
Name: PKWNR, dtype: int64
2
ID: 4501022305
1320    1
1370    2
Name: PERSNR, dtype: int32
2
29    1
Name: PKWNR, dtype: int64
1
ID: 4501022308
1376    1
Name: PERSNR, dtype: int32
1
30    1
Name: PKWNR, dtype: int64
1
ID: 4501022311
1420    1
1463    2
Name: PERSNR, dtype: int32
2
31    1
32    2
Name: PKWNR, dtype: int64
2
ID: 4501022341
1496    1
Name: PERSNR, dtype: int32
1
33    1
Name: PKWNR, dtype: int64
1
ID: 4501022349
ID: 4501022356
1555    1
Name: PERSNR, dtype: int32
1
34    1
Name: PKWNR, dtype: int64
1
ID: 4501022358
1580    1
1591    2
1602    3
Name: PERSNR, dtype: int32
3
36    1
35    2
Name: PKWNR, dtype: int64
2
ID: 4501022361
1643    1
Name: PERSNR, dtype: int32
1
37    1
Name: PKWNR, dtype: int64
1
ID: 4501022369
1661    1
Name: PERSNR, dtype: int32
1
38    1
Name: PKWNR, dtype: int64
1
ID: 4501022371
1675    1
Name: PERSNR, dtype: int32
1
39    1
Name: PKWNR, dtype: int64
1
ID: 4501022379
1726    1
Name: PERSNR, dtype: int32
1
40    1
42    3
41    2
Name: PKWNR, dtype: int64
3
ID: 4501022389
1752    1
1769    2
Name: PERSNR, dtype: int32
2
43    1
44    2
Name: PKWNR, dtype: int64
2
ID: 4501022393
1777    2
Name: PERSNR, dtype: int32
1
45    1
Name: PKWNR, dtype: int64
3
ID: 4501022491
ID: 4501022510
1829    1
1838    2
Name: PERSNR, dtype: int32
2
46    1
Name: PKWNR, dtype: int64
1
ID: 4501022529
1851    1
Name: PERSNR, dtype: int32
1
47    1
Name: PKWNR, dtype: int64
1
ID: 4501022530
1875    1
1917    2
Name: PERSNR, dtype: int32
2
48    1
49    2
Name: PKWNR, dtype: int64
2
ID: 4501022532
1937    1
Name: PERSNR, dtype: int32
1
50    1
51    2
Name: PKWNR, dtype: int64
2
ID: 4501022537
2020    2
Name: PERSNR, dtype: int32
1
52    1
Name: PKWNR, dtype: int64
1
ID: 4501022538
2035    1
2061    2
Name: PERSNR, dtype: int32
2
53    1
Name: PKWNR, dtype: int64
1
ID: 4501022542
2080    1
Name: PERSNR, dtype: int32
1
54    1
Name: PKWNR, dtype: int64
1
ID: 4501022551
ID: 4501022589
2195    1
2217    2
2264    4
Name: PERSNR, dtype: int32
3
58    1
56    2
57    3
Name: PKWNR, dtype: int64
3
ID: 4501022608
ID: 4501022613
2318    1
2348    2
Name: PERSNR, dtype: int32
2
60    1
59    2
Name: PKWNR, dtype: int64
2
ID: 4501022620
2356    1
2407    2
2421    3
Name: PERSNR, dtype: int32
3
61    2
62    3
63    1
Name: PKWNR, dtype: int64
3
ID: 4501022621
2453    1
Name: PERSNR, dtype: int32
1
64    1
Name: PKWNR, dtype: int64
1
ID: 4501022635
2510    1
2516    2
Name: PERSNR, dtype: int32
2
65    1
Name: PKWNR, dtype: int64
1
ID: 4501022638
2560    2
Name: PERSNR, dtype: int32
1
66    1
Name: PKWNR, dtype: int64
1
ID: 4501022653
2591    1
Name: PERSNR, dtype: int32
1
67    1
Name: PKWNR, dtype: int64
1
ID: 4501022662
ID: 4501022733
ID: 4501022766
2769    1
Name: PERSNR, dtype: int32
1
68    1
Name: PKWNR, dtype: int64
1
ID: 4501022767
ID: 4501022773
2802    1
Name: PERSNR, dtype: int32
1
69    1
Name: PKWNR, dtype: int64
1
ID: 4501022776
ID: 4501022805
ID: 4501022806
2950    1
Name: PERSNR, dtype: int32
1
70    1
Name: PKWNR, dtype: int64
1
ID: 4501022810
ID: 4501022816
ID: 4501022827
3082    1
3109    2
3124    3
Name: PERSNR, dtype: int32
3
71    1
Name: PKWNR, dtype: int64
5
ID: 4501022831
ID: 4501022835
ID: 4501022843
ID: 4501022852
ID: 4501022870
3308    1
Name: PERSNR, dtype: int32
1
72    1
Name: PKWNR, dtype: int64
1
ID: 4501022877
3330    1
3346    2
Name: PERSNR, dtype: int32
2
73    1
74    3
75    2
Name: PKWNR, dtype: int64
3
ID: 4501022878
3371    1
3383    2
3397    3
Name: PERSNR, dtype: int32
3
77    1
76    2
Name: PKWNR, dtype: int64
2
ID: 4501022881
ID: 4501022900
3421    1
3431    2
Name: PERSNR, dtype: int32
2
78    2
79    1
Name: PKWNR, dtype: int64
2
ID: 4501022912
3459    1
Name: PERSNR, dtype: int32
1
80    1
81    2
Name: PKWNR, dtype: int64
2
ID: 4501022973
ID: 4501023004
3524    1
3550    2
Name: PERSNR, dtype: int32
2
82    1
83    2
Name: PKWNR, dtype: int64
2
ID: 4501023043
3658    1
Name: PERSNR, dtype: int32
1
84    1
Name: PKWNR, dtype: int64
1
ID: 4501023048
3680    1
Name: PERSNR, dtype: int32
1
85    1
Name: PKWNR, dtype: int64
1
ID: 4501023049
3718    1
3741    2
Name: PERSNR, dtype: int32
2
86    1
87    2
Name: PKWNR, dtype: int64
2
ID: 4501023052
3779    1
3806    2
Name: PERSNR, dtype: int32
2
89    2
88    1
Name: PKWNR, dtype: int64
2
ID: 4501023106
3900    1
3916    2
Name: PERSNR, dtype: int32
2
90    2
91    1
Name: PKWNR, dtype: int64
2
ID: 4501023114
3936    1
Name: PERSNR, dtype: int32
1
92    1
Name: PKWNR, dtype: int64
1
ID: 4501023115
3963    1
Name: PERSNR, dtype: int32
1
93    1
Name: PKWNR, dtype: int64
1
ID: 4501023131
3984    1
4018    2
Name: PERSNR, dtype: int32
2
94    1
Name: PKWNR, dtype: int64
1
ID: 4501023138
4078    1
Name: PERSNR, dtype: int32
1
95    1
Name: PKWNR, dtype: int64
1
ID: 4501023143
4148    1
Name: PERSNR, dtype: int32
1
96    1
Name: PKWNR, dtype: int64
1
ID: 4501023148
4200    2
Name: PERSNR, dtype: int32
1
97    1
Name: PKWNR, dtype: int64
1
ID: 4501023167
4283    1
4297    2
Name: PERSNR, dtype: int32
2
98    1
Name: PKWNR, dtype: int64
1
ID: 4501023170
4319    1
4337    2
Name: PERSNR, dtype: int32
2
99    1
Name: PKWNR, dtype: int64
1
ID: 4501023174
4361    1
4429    2
4430    3
Name: PERSNR, dtype: int32
3
100    1
101    2
Name: PKWNR, dtype: int64
2
ID: 4501023201
4460    1
Name: PERSNR, dtype: int32
1
102    1
Name: PKWNR, dtype: int64
2
ID: 4501023203
4486    1
Name: PERSNR, dtype: int32
1
103    1
Name: PKWNR, dtype: int64
2
ID: 4501023284
ID: 4501023286
4611    1
Name: PERSNR, dtype: int32
1
104    1
Name: PKWNR, dtype: int64
1
ID: 4501023296
ID: 4501023316
ID: 4501023317
4695    1
4719    2
4737    3
Name: PERSNR, dtype: int32
3
108    4
107    2
106    1
105    3
Name: PKWNR, dtype: int64
5
ID: 4501023328
4743    1
4790    2
Name: PERSNR, dtype: int32
2
109    1
110    2
Name: PKWNR, dtype: int64
2
ID: 4501023331
4818    1
4838    2
Name: PERSNR, dtype: int32
2
112    2
111    1
Name: PKWNR, dtype: int64
2
ID: 4501023342
4860    1
4883    2
Name: PERSNR, dtype: int32
2
114    2
113    1
Name: PKWNR, dtype: int64
2
ID: 4501023355
4902    1
Name: PERSNR, dtype: int32
1
115    1
116    2
Name: PKWNR, dtype: int64
2
ID: 4501023370
ID: 4501023447
5007    1
5022    2
Name: PERSNR, dtype: int32
2
117    1
118    2
119    3
Name: PKWNR, dtype: int64
4
ID: 4501023455
5065    2
Name: PERSNR, dtype: int32
1
121    2
120    1
Name: PKWNR, dtype: int64
2
ID: 4501023457
5080    1
5116    2
Name: PERSNR, dtype: int32
2
122    1
Name: PKWNR, dtype: int64
1
ID: 4501023482
5170    1
Name: PERSNR, dtype: int32
1
123    1
Name: PKWNR, dtype: int64
1
ID: 4501023501

5219    1
Name: PERSNR, dtype: int32
1
124    1
Name: PKWNR, dtype: int64
1
ID: 4501023502
5238    1
5271    2
Name: PERSNR, dtype: int32
2
126    1
125    2
Name: PKWNR, dtype: int64
2
ID: 4501023505
ID: 4501023516
5426    1
5443    2
Name: PERSNR, dtype: int32
2
127    1
Name: PKWNR, dtype: int64
1
ID: 4501023527
5460    1
Name: PERSNR, dtype: int32
1
128    1
Name: PKWNR, dtype: int64
1
ID: 4501023529
5490    1
Name: PERSNR, dtype: int32
1
129    1
Name: PKWNR, dtype: int64
1
ID: 4501023553
ID: 4501023560
ID: 4501023606
ID: 4501023610
5790    1
Name: PERSNR, dtype: int32
1
130    1
Name: PKWNR, dtype: int64
1
ID: 4501023623
5802    1
5825    2
5853    3
Name: PERSNR, dtype: int32
3
132    2
131    1
Name: PKWNR, dtype: int64
1
ID: 4501023636
5875    1
Name: PERSNR, dtype: int32
1
133    1
Name: PKWNR, dtype: int64
1
ID: 4501023649
5887    1
5918    2
Name: PERSNR, dtype: int32
2
134    1
135    2
Name: PKWNR, dtype: int64
2
ID: 4501023719
ID: 4501023754
6010    1
6024    2
Name: PERSNR, dtype: int32
2
136    1
Name: PKWNR, dtype: int64
2
ID: 4501023807
6086    1
6104    2
Name: PERSNR, dtype: int32
2
137    2
138    1
Name: PKWNR, dtype: int64
2
ID: 4501023823
6134    1
6165    2
6185    3
6215    4
Name: PERSNR, dtype: int32
4
140    2
139    1
Name: PKWNR, dtype: int64
2
ID: 4501023824
6228    1
6232    2
Name: PERSNR, dtype: int32
2
141    1
Name: PKWNR, dtype: int64
1
ID: 4501023923
6247    1
6259    2
6277    3
6297    4
Name: PERSNR, dtype: int32
4
144    4
145    2
143    1
142    3
Name: PKWNR, dtype: int64
4
ID: 4501023949
6319    1
6347    2
Name: PERSNR, dtype: int32
2
146    1
147    2
Name: PKWNR, dtype: int64
2
ID: 4501023961
6404    1
6429    2
Name: PERSNR, dtype: int32
2
149    2
148    1
Name: PKWNR, dtype: int64
2
ID: 4501023969
6490    1
Name: PERSNR, dtype: int32
1
150    1
Name: PKWNR, dtype: int64
1
ID: 4501023994
6545    1
Name: PERSNR, dtype: int32
1
151    1
Name: PKWNR, dtype: int64
1
ID: 4501024009
6578    1
Name: PERSNR, dtype: int32
1
152    1
Name: PKWNR, dtype: int64
1
ID: 4501024032
6589    1
6615    2
Name: PERSNR, dtype: int32
2
154    2
153    1
Name: PKWNR, dtype: int64
3
ID: 4501024050
ID: 4501024054
6643    1
6654    2
Name: PERSNR, dtype: int32
2
155    1
Name: PKWNR, dtype: int64
1
ID: 4501024056
6691    1
6722    2
Name: PERSNR, dtype: int32
2
157    2
156    1
Name: PKWNR, dtype: int64
2
ID: 4501024079
6763    1
6779    2
Name: PERSNR, dtype: int32
2
159    2
158    1
Name: PKWNR, dtype: int64
2
ID: 4501024082
6805    1
Name: PERSNR, dtype: int32
1
160    1
Name: PKWNR, dtype: int64
1
ID: 4501024083
6821    1
6844    2
Name: PERSNR, dtype: int32
2
162    2
161    1
Name: PKWNR, dtype: int64
2
ID: 4501024091
6866    1
6892    2
Name: PERSNR, dtype: int32
2
163    1
Name: PKWNR, dtype: int64
2
ID: 4501024101
6920    1
6943    2
Name: PERSNR, dtype: int32
2
164    1
Name: PKWNR, dtype: int64
1
ID: 4501024102
6977    1
7011    2
Name: PERSNR, dtype: int32
2
165    2
166    1
Name: PKWNR, dtype: int64
2
ID: 4501024121
7047    1
Name: PERSNR, dtype: int32
1
167    1
Name: PKWNR, dtype: int64
1
ID: 4501024122
ID: 4501024127
7105    1
Name: PERSNR, dtype: int32
1
168    1
Name: PKWNR, dtype: int64
1
ID: 4501024135
7131    1
Name: PERSNR, dtype: int32
1
170    3
169    1
171    2
Name: PKWNR, dtype: int64
3
ID: 4501024162
7158    1
Name: PERSNR, dtype: int32
1
172    1
Name: PKWNR, dtype: int64
1
ID: 4501024163
ID: 4501024182
7258    1
Name: PERSNR, dtype: int32
1
173    1
Name: PKWNR, dtype: int64
2
ID: 4501024192
ID: 4501024195
ID: 4501024202
7379    1
7406    2
Name: PERSNR, dtype: int32
2
174    1
175    2
Name: PKWNR, dtype: int64
2
ID: 4501024210
7438    1
Name: PERSNR, dtype: int32
1
176    1
Name: PKWNR, dtype: int64
1
ID: 4501024227
7483    1
7521    3
Name: PERSNR, dtype: int32
2
177    1
178    2
179    3
Name: PKWNR, dtype: int64
3
ID: 4501024234
7531    1
Name: PERSNR, dtype: int32
1
180    1
Name: PKWNR, dtype: int64
1
ID: 4501024244
7565    1
Name: PERSNR, dtype: int32
1
181    1
182    2
Name: PKWNR, dtype: int64
2
ID: 4501024388
7607    1
Name: PERSNR, dtype: int32
1
183    1
Name: PKWNR, dtype: int64
2
ID: 4501024396
7646    1
7656    2
Name: PERSNR, dtype: int32
2
184    1
Name: PKWNR, dtype: int64
1
ID: 4501024443
7702    1
7724    2
Name: PERSNR, dtype: int32
2
185    1
Name: PKWNR, dtype: int64
1
ID: 4501024453
ID: 4501024468
7769    1
7792    2
Name: PERSNR, dtype: int32
2
187    2
186    1
Name: PKWNR, dtype: int64
2
ID: 4501024475
7813    1
7841    2
Name: PERSNR, dtype: int32
2
188    1
189    2
Name: PKWNR, dtype: int64
3
ID: 4501024487
7859    1
Name: PERSNR, dtype: int32
1
190    1
Name: PKWNR, dtype: int64
1
ID: 4501024510
7917    1
Name: PERSNR, dtype: int32
1
192    2
191    1
Name: PKWNR, dtype: int64
2
ID: 4501024528
7966    1
7980    2
Name: PERSNR, dtype: int32
2
194    1
193    2
Name: PKWNR, dtype: int64
2
ID: 4501024541
8015    1
Name: PERSNR, dtype: int32
1
195    1
Name: PKWNR, dtype: int64
1
ID: 4501024614
8059    1
Name: PERSNR, dtype: int32
1
196    1
Name: PKWNR, dtype: int64
1
ID: 4501024620
8094    1
Name: PERSNR, dtype: int32
1
197    1
Name: PKWNR, dtype: int64
1
ID: 4501024637
8121    1
Name: PERSNR, dtype: int32
1
198    1
Name: PKWNR, dtype: int64
1
ID: 4501024661
8146    1
Name: PERSNR, dtype: int32
1
199    1
Name: PKWNR, dtype: int64
1
ID: 4501024672
8241    1
8249    2
8287    3
Name: PERSNR, dtype: int32
3
200    1
201    2
Name: PKWNR, dtype: int64
2
ID: 4501024712
8319    2
Name: PERSNR, dtype: int32
1
204    3
202    1
203    2
Name: PKWNR, dtype: int64
3
ID: 4501024727
8339    1
Name: PERSNR, dtype: int32
1
205    1
Name: PKWNR, dtype: int64
1
ID: 4501024735
8362    1
Name: PERSNR, dtype: int32
1
206    1
Name: PKWNR, dtype: int64
1
ID: 4501024749
8383    1
Name: PERSNR, dtype: int32
1
207    1
Name: PKWNR, dtype: int64
1
ID: 4501024774
8432    1
Name: PERSNR, dtype: int32
1
208    1
Name: PKWNR, dtype: int64
2
ID: 4501024777
8443    1
8483    2
Name: PERSNR, dtype: int32
2
209    1
Name: PKWNR, dtype: int64
1
ID: 4501024801
8501    1
Name: PERSNR, dtype: int32
1
210    1
Name: PKWNR, dtype: int64
1
ID: 4501024849
8519    1
Name: PERSNR, dtype: int32
1
212    2
211    1
Name: PKWNR, dtype: int64
1
ID: 4501024881
8590    1
8615    2
Name: PERSNR, dtype: int32
2
213    1
Name: PKWNR, dtype: int64
1
ID: 4501024930
ID: 4501024986
8714    1
Name: PERSNR, dtype: int32
1
214    1
Name: PKWNR, dtype: int64
1
ID: 4501024995
8733    2
Name: PERSNR, dtype: int32
1
215    1
Name: PKWNR, dtype: int64
1
ID: 4501025000
8752    1
Name: PERSNR, dtype: int32
1
216    1
Name: PKWNR, dtype: int64
1
ID: 4501025007
8822    2
8868    3
Name: PERSNR, dtype: int32
2
218    1
217    2
Name: PKWNR, dtype: int64
2
ID: 4501025014
8892    2
Name: PERSNR, dtype: int32
1
219    1
Name: PKWNR, dtype: int64
1
ID: 4501025034
ID: 4501025073
8931    1
8945    2
Name: PERSNR, dtype: int32
2
221    1
222    2
Name: PKWNR, dtype: int64
2
ID: 4501025106
8960    1
Name: PERSNR, dtype: int32
1
223    1
Name: PKWNR, dtype: int64
1
ID: 4501025109
8983    1
9014    3
Name: PERSNR, dtype: int32
2
224    1
Name: PKWNR, dtype: int64
2
ID: 4501025195
9041    1
Name: PERSNR, dtype: int32
1
225    1
Name: PKWNR, dtype: int64
1
ID: 4501025198
9070    1
9087    2
Name: PERSNR, dtype: int32
2
226    1
Name: PKWNR, dtype: int64
1
ID: 4501025209
ID: 4501025210
ID: 4501025239
9182    2
Name: PERSNR, dtype: int32
1
227    1
228    2
Name: PKWNR, dtype: int64
2
ID: 4501025243
9233    1
9283    2
Name: PERSNR, dtype: int32
2
230    2
229    1
Name: PKWNR, dtype: int64
2
ID: 4501025246
ID: 4501025288
9331    1
Name: PERSNR, dtype: int32
1
231    1
Name: PKWNR, dtype: int64
1
ID: 4501025298
9354    1
9368    2
Name: PERSNR, dtype: int32
2
232    1
Name: PKWNR, dtype: int64
1
ID: 4501025405
9409    1
Name: PERSNR, dtype: int32
1
233    1
Name: PKWNR, dtype: int64
1
ID: 4501025458
ID: 4501025489
9441    1
9464    2
9483    3
Name: PERSNR, dtype: int32
3
235    1
234    2
Name: PKWNR, dtype: int64
2
ID: 4501025495
9509    1
9532    2
Name: PERSNR, dtype: int32
2
236    1
237    2
Name: PKWNR, dtype: int64
3
ID: 4501025625
9617    2
Name: PERSNR, dtype: int32
1
238    1
Name: PKWNR, dtype: int64
1
ID: 4501025667
9680    2
Name: PERSNR, dtype: int32
1
240    1
Name: PKWNR, dtype: int64
1
ID: 4501025676
9688    1
Name: PERSNR, dtype: int32
1
242    2
241    1
Name: PKWNR, dtype: int64
2
ID: 4501025706
ID: 4501025712
9773    1
Name: PERSNR, dtype: int32
1
243    1
Name: PKWNR, dtype: int64
1
ID: 4501025836
9830    1
9866    2
Name: PERSNR, dtype: int32
2
244    2
245    1
Name: PKWNR, dtype: int64
2
ID: 4501025839
9921    1
Name: PERSNR, dtype: int32
1
246    1
Name: PKWNR, dtype: int64
1
ID: 4501025852
9968    2
Name: PERSNR, dtype: int32
1
248    2
247    1
Name: PKWNR, dtype: int64
2
ID: 4501025907
9986     1
10047    2
Name: PERSNR, dtype: int32
2
249    1
250    2
Name: PKWNR, dtype: int64
2
ID: 4501025928
10071    1
Name: PERSNR, dtype: int32
1
251    1
Name: PKWNR, dtype: int64
1
ID: 4501025991
10104    1
10133    2
Name: PERSNR, dtype: int32
2
253    2
252    1
Name: PKWNR, dtype: int64
2
ID: 4501026004
ID: 4501026006
10212    2
Name: PERSNR, dtype: int32
1
254    1
Name: PKWNR, dtype: int64
1
ID: 4501026011
ID: 4501026060
10273    1
10287    2
10305    3
Name: PERSNR, dtype: int32
3
257    3
255    2
256    1
Name: PKWNR, dtype: int64
3
ID: 4501026075
10343    1
Name: PERSNR, dtype: int32
1
258    1
Name: PKWNR, dtype: int64
1
ID: 4501026174
10361    1
Name: PERSNR, dtype: int32
1
259    1
Name: PKWNR, dtype: int64
1
ID: 4501026198
10385    1
10406    2
Name: PERSNR, dtype: int32
2
260    1
Name: PKWNR, dtype: int64
1
ID: 4501026201
10442    1
Name: PERSNR, dtype: int32
1
261    1
262    2
Name: PKWNR, dtype: int64
2
ID: 4501026255
ID: 4501026296
ID: 4501026309
10597    1
10617    2
Name: PERSNR, dtype: int32
2
263    1
264    2
Name: PKWNR, dtype: int64
2
ID: 4501026426
10638    1
10675    2
Name: PERSNR, dtype: int32
2
265    1
Name: PKWNR, dtype: int64
1
ID: 4501026430
10696    1
Name: PERSNR, dtype: int32
1
266    1
Name: PKWNR, dtype: int64
1
ID: 4501026529
10712    1
Name: PERSNR, dtype: int32
1
267    1
Name: PKWNR, dtype: int64
1
ID: 4501026532
10756    1
Name: PERSNR, dtype: int32
1
268    1
Name: PKWNR, dtype: int64
1
ID: 4501026617
10771    1
Name: PERSNR, dtype: int32
1
269    1
Name: PKWNR, dtype: int64
1
ID: 4501026620
10792    1
Name: PERSNR, dtype: int32
1
270    1
Name: PKWNR, dtype: int64
1
ID: 4511020049
ID: 4511020067
10849    1
Name: PERSNR, dtype: int32
1
271    1
Name: PKWNR, dtype: int64
1
ID: 4511020083
ID: 4511020108
10914    1
10938    2
Name: PERSNR, dtype: int32
2
272    1
273    2
Name: PKWNR, dtype: int64
2
ID: 4511020225
ID: 4511020232
11047    1
Name: PERSNR, dtype: int32
1
274    1
Name: PKWNR, dtype: int64
1
ID: 4511020235
11068    1

Name: PERSNR, dtype: int32
1
275    1
Name: PKWNR, dtype: int64
1
ID: 4511020245
11104    1
11127    2
Name: PERSNR, dtype: int32
2
276    1
Name: PKWNR, dtype: int64
1
ID: 4511020260
11140    1
11181    2
11212    3
Name: PERSNR, dtype: int32
3
278    2
277    1
Name: PKWNR, dtype: int64
2
ID: 4511020270
11233    1
Name: PERSNR, dtype: int32
1
279    1
Name: PKWNR, dtype: int64
1
ID: 4511020326
11297    1
11324    2
11360    3
11384    4
Name: PERSNR, dtype: int32
4
281    2
280    1
Name: PKWNR, dtype: int64
3
ID: 4511020331
11410    1
Name: PERSNR, dtype: int32
1
282    1
Name: PKWNR, dtype: int64
1
ID: 4511020332
11431    1
11459    2
Name: PERSNR, dtype: int32
2
284    2
283    1
Name: PKWNR, dtype: int64
2
ID: 4511020384
11481    1
11496    2
11507    3
11524    4
Name: PERSNR, dtype: int32
4
286    2
288    1
285    3
287    4
Name: PKWNR, dtype: int64
4
ID: 4511020396
11536    1
Name: PERSNR, dtype: int32
1
289    1
Name: PKWNR, dtype: int64
1
ID: 4511020405
11542    1
Name: PERSNR, dtype: int32
1
290    1
Name: PKWNR, dtype: int64
1
ID: 4511020433
ID: 4511020434
11609    1
Name: PERSNR, dtype: int32
1
291    1
Name: PKWNR, dtype: int64
1
ID: 4511020440
11622    1
Name: PERSNR, dtype: int32
1
292    1
Name: PKWNR, dtype: int64
1
ID: 4511020445
11629    1
Name: PERSNR, dtype: int32
1
293    1
Name: PKWNR, dtype: int64
1
ID: 4511020482
11646    1
Name: PERSNR, dtype: int32
1
294    1
Name: PKWNR, dtype: int64
1
ID: 4511020512
11668    1
Name: PERSNR, dtype: int32
1
295    1
Name: PKWNR, dtype: int64
1
ID: 4511020517
11697    1
Name: PERSNR, dtype: int32
1
296    1
Name: PKWNR, dtype: int64
1
ID: 4511020518
11708    1
11728    2
Name: PERSNR, dtype: int32
2
297    2
298    1
Name: PKWNR, dtype: int64
2
ID: 4511020525
ID: 4511020537
11826    1
Name: PERSNR, dtype: int32
1
300    1
299    2
Name: PKWNR, dtype: int64
3
ID: 4511020554
11874    1
Name: PERSNR, dtype: int32
1
301    1
Name: PKWNR, dtype: int64
1
ID: 4511020613
11905    1
Name: PERSNR, dtype: int32
1
302    1
303    2
Name: PKWNR, dtype: int64
2
ID: 4511020660
11937    1
Name: PERSNR, dtype: int32
1
304    1
Name: PKWNR, dtype: int64
1
ID: 4511020693
11973    1
11992    2
Name: PERSNR, dtype: int32
2
305    2
306    1
Name: PKWNR, dtype: int64
2
ID: 4511020718
12083    1
Name: PERSNR, dtype: int32
1
307    1
Name: PKWNR, dtype: int64
1
ID: 4511020722
ID: 4511020731
12121    1
12153    2
Name: PERSNR, dtype: int32
2
308    2
309    1
Name: PKWNR, dtype: int64
2
ID: 4511020740
ID: 4511020780
ID: 4511020798
ID: 4511020803
ID: 4511020827
12308    1
Name: PERSNR, dtype: int32
1
311    2
310    1
Name: PKWNR, dtype: int64
2
ID: 4511020833
12349    1
12361    2
Name: PERSNR, dtype: int32
2
312    1
Name: PKWNR, dtype: int64
1
ID: 4511020835
12409    1
12434    2
Name: PERSNR, dtype: int32
2
313    1
314    2
Name: PKWNR, dtype: int64
2
ID: 4511020838
12460    1
Name: PERSNR, dtype: int32
1
315    1
Name: PKWNR, dtype: int64
1
ID: 4511020839
ID: 4511020841
ID: 4511020863
12533    1
12562    2
Name: PERSNR, dtype: int32
2
316    1
317    2
Name: PKWNR, dtype: int64
2
ID: 4511020988
12593    1
Name: PERSNR, dtype: int32
1
320    1
Name: PKWNR, dtype: int64
1
ID: 4511021054
ID: 4511021061
12665    1
Name: PERSNR, dtype: int32
1
321    1
Name: PKWNR, dtype: int64
1
ID: 4511021085
ID: 4511021119
12703    1
12715    2
12721    3
Name: PERSNR, dtype: int32
3
324    3
323    2
322    1
Name: PKWNR, dtype: int64
3
ID: 4511021137
12755    1
Name: PERSNR, dtype: int32
1
325    1
Name: PKWNR, dtype: int64
1
ID: 4511021194
12769    1
Name: PERSNR, dtype: int32
1
326    1
Name: PKWNR, dtype: int64
1
ID: 4511021201
ID: 4511021205
ID: 4511021263
ID: 4511021288
12975    1
Name: PERSNR, dtype: int32
1
327    1
Name: PKWNR, dtype: int64
1
ID: 4511021309
13006    1
13030    2
Name: PERSNR, dtype: int32
2
328    1
Name: PKWNR, dtype: int64
1
ID: 4511021367
13064    1
Name: PERSNR, dtype: int32
1
329    1
Name: PKWNR, dtype: int64
2
ID: 4511021372
13090    1
Name: PERSNR, dtype: int32
1
330    1
Name: PKWNR, dtype: int64
1
ID: 4511021391
13115    1
Name: PERSNR, dtype: int32
1
331    1
Name: PKWNR, dtype: int64
1
ID: 4511021417
ID: 4511021461
13190    1
Name: PERSNR, dtype: int32
1
332    1
Name: PKWNR, dtype: int64
3
ID: 4511021468
13216    1
Name: PERSNR, dtype: int32
1
333    1
Name: PKWNR, dtype: int64
1
ID: 4511021474
ID: 4511021500
13292    1
Name: PERSNR, dtype: int32
1
334    1
Name: PKWNR, dtype: int64
1
ID: 4511021529
13367    1
Name: PERSNR, dtype: int32
1
335    1
Name: PKWNR, dtype: int64
2
ID: 4511021628
13432    2
Name: PERSNR, dtype: int32
1
336    1
Name: PKWNR, dtype: int64
1
ID: 4511021651
13453    1
Name: PERSNR, dtype: int32
1
337    1
Name: PKWNR, dtype: int64
1
ID: 4511021675
13481    1
13516    2
Name: PERSNR, dtype: int32
2
341    4
338    1
339    3
340    2
Name: PKWNR, dtype: int64
4
ID: 4511021759
13558    1
Name: PERSNR, dtype: int32
1
343    1
Name: PKWNR, dtype: int64
1
ID: 4511021790
13597    1
Name: PERSNR, dtype: int32
1
344    1
Name: PKWNR, dtype: int64
1
ID: 4511021845
ID: 4511021849
13641    1
Name: PERSNR, dtype: int32
1
345    1
Name: PKWNR, dtype: int64
1
ID: 4511021864
13668    1
13714    2
Name: PERSNR, dtype: int32
2
346    1
Name: PKWNR, dtype: int64
1
ID: 4511021875
13754    1
Name: PERSNR, dtype: int32
1
347    1
Name: PKWNR, dtype: int64
1
ID: 4511021886
13792    1
Name: PERSNR, dtype: int32
1
349    1
Name: PKWNR, dtype: int64
1
ID: 4511021969
13852    1
Name: PERSNR, dtype: int32
1
350    1
Name: PKWNR, dtype: int64
1
ID: 4511021985
ID: 4511022029
13938    1
Name: PERSNR, dtype: int32
1
351    1
Name: PKWNR, dtype: int64
1
ID: 4511022060
ID: 4511022107
14014    1
14039    2
Name: PERSNR, dtype: int32
2
353    2
352    1
Name: PKWNR, dtype: int64
2
ID: 4701032239
14077    1
14096    2
Name: PERSNR, dtype: int32
2
355    2
356    3
354    1
Name: PKWNR, dtype: int64
3
ID: 4701032246
14153    1
Name: PERSNR, dtype: int32
1
357    1
Name: PKWNR, dtype: int64
2
ID: 4701032279
ID: 4701032288
14272    1
14292    2
Name: PERSNR, dtype: int32
2
360    1
361    2
Name: PKWNR, dtype: int64
2
ID: 4701032290
14324    1
Name: PERSNR, dtype: int32
1
362    1
363    2
Name: PKWNR, dtype: int64
3
ID: 4701032295
14370    1
14400    2
Name: PERSNR, dtype: int32
2
365    1
366    2
Name: PKWNR, dtype: int64
2
ID: 4701032297
ID: 4701032306
14496    2
Name: PERSNR, dtype: int32
1
367    1
Name: PKWNR, dtype: int64
1
ID: 4701032307
14578    1
14591    2
Name: PERSNR, dtype: int32
2
368    1
Name: PKWNR, dtype: int64
1
ID: 4701032314
14619    1
Name: PERSNR, dtype: int32
1
369    1
Name: PKWNR, dtype: int64
1
ID: 4701032327
14653    1
14671    2
Name: PERSNR, dtype: int32
2
370    1
Name: PKWNR, dtype: int64
1
ID: 4701032330
14725    1
14737    2
Name: PERSNR, dtype: int32
2
371    1
Name: PKWNR, dtype: int64
1
ID: 4701032347
ID: 4701032365
14823    1
Name: PERSNR, dtype: int32
1
373    1
Name: PKWNR, dtype: int64
1
ID: 4701032367
14846    1
14887    2
Name: PERSNR, dtype: int32
2
374    1
375    2
Name: PKWNR, dtype: int64
2
ID: 4701032373
14928    1
Name: PERSNR, dtype: int32
1
376    1
Name: PKWNR, dtype: int64
1
ID: 4701032377
14979    2
Name: PERSNR, dtype: int32
1
377    1
Name: PKWNR, dtype: int64
1
ID: 4701032388
14999    1
Name: PERSNR, dtype: int32
1
378    1
Name: PKWNR, dtype: int64
1
ID: 4701032407
15057    1
15076    2
Name: PERSNR, dtype: int32
2
379    2
380    1
Name: PKWNR, dtype: int64
2
ID: 4701032417
15102    1
15104    2
Name: PERSNR, dtype: int32
2
381    1
Name: PKWNR, dtype: int64
1
ID: 4701032431
15115    1
15137    2
Name: PERSNR, dtype: int32
2
382    1
383    2
Name: PKWNR, dtype: int64
2
ID: 4701032511
15219    2
Name: PERSNR, dtype: int32
1
384    1
Name: PKWNR, dtype: int64
1
ID: 4701032526
15224    1
15245    2
Name: PERSNR, dtype: int32
2
386    2
385    1
Name: PKWNR, dtype: int64
3
ID: 4701032529
15263    1
15282    2
Name: PERSNR, dtype: int32
2
387    2
388    1
Name: PKWNR, dtype: int64
2
ID: 4701032530
15314    1
15318    2
Name: PERSNR, dtype: int32
2
389    1
Name: PKWNR, dtype: int64
1
ID: 4701032538
15332    1
15349    2
Name: PERSNR, dtype: int32
2
390    1
391    2
Name: PKWNR, dtype: int64
3
ID: 4701032560
ID: 4701032565
15420    1
15448    2
Name: PERSNR, dtype: int32
2
393    1
392    2
Name: PKWNR, dtype: int64
2
ID: 4701032568
15469    1
Name: PERSNR, dtype: int32
1
394    1
Name: PKWNR, dtype: int64
1
ID: 4701032571
15538    1
15544    2
Name: PERSNR, dtype: int32
2
395    1
Name: PKWNR, dtype: int64
1
ID: 4701032583
15574    1
15597    2
Name: PERSNR, dtype: int32
2
396    1
397    2
Name: PKWNR, dtype: int64
2
ID: 4701032590
15618    1
15651    2
Name: PERSNR, dtype: int32
2
398    1
Name: PKWNR, dtype: int64
1
ID: 4701032593
15679    1
Name: PERSNR, dtype: int32
1
399    1
Name: PKWNR, dtype: int64
1
ID: 4701032597
15715    1
15742    2
Name: PERSNR, dtype: int32
2
401    2
400    1
Name: PKWNR, dtype: int64
2
ID: 4701032605
ID: 4701032612
15830    1
Name: PERSNR, dtype: int32
1
402    1
Name: PKWNR, dtype: int64
1
ID: 4701032617
15881    1
Name: PERSNR, dtype: int32
1
403    1
Name: PKWNR, dtype: int64
1
ID: 4701032618
15905    1
Name: PERSNR, dtype: int32
1
405    2
404    1
Name: PKWNR, dtype: int64
3
ID: 4701032627
15943    1
Name: PERSNR, dtype: int32
1
406    1
Name: PKWNR, dtype: int64
1
ID: 4701032633
15982    1
16009    2
Name: PERSNR, dtype: int32
2
407    1
Name: PKWNR, dtype: int64
1
ID: 4701032634
16017    1
Name: PERSNR, dtype: int32
1
408    1
Name: PKWNR, dtype: int64
3
ID: 4701032643
16045    1
16086    2
Name: PERSNR, dtype: int32
2
409    1
Name: PKWNR, dtype: int64
1
ID: 4701032645
16161    1
Name: PERSNR, dtype: int32
1
410    1
Name: PKWNR, dtype: int64
1
ID: 4701032648
16206    2
Name: PERSNR, dtype: int32
1
411    1
Name: PKWNR, dtype: int64
1
ID: 4701032662
16242    1
Name: PERSNR, dtype: int32
1
412    1
Name: PKWNR, dtype: int64
2
ID: 4701032682
16316    2
Name: PERSNR, dtype: int32
1
414    1
Name: PKWNR, dtype: int64
1
ID: 4701032688
16333    1
Name: PERSNR, dtype: int32
1
415    1
Name: PKWNR, dtype: int64
1
ID: 4701032694
16381    1
Name: PERSNR, dtype: int32
1
416    1
Name: PKWNR, dtype: int64
1
ID: 4701032696
16418    1
16456    2
Name: PERSNR, dtype: int32
2
417    1
Name: PKWNR, dtype: int64
2
ID: 4701032712
16522    1
Name: PERSNR, dtype: int32
1
418    1
Name: PKWNR, dtype: int64
1
ID: 4701032719
16548    1
Name: PERSNR, dtype: int32
1
419    1
Name: PKWNR, dtype: int64
1
ID: 4701032723
16585    1
Name: PERSNR, dtype: int32
1
420    1
Name: PKWNR, dtype: int64
1
ID: 4701032724
16611    1
Name: PERSNR, dtype: int32
1
421    1
Name: PKWNR, dtype: int64
1
ID: 4701032734
16623    1
16653    2
Name: PERSNR, dtype: int32
2
422    1
Name: PKWNR, dtype: int64
1
ID: 4701032738
16690    1
16708    2
Name: PERSNR, dtype: int32
2
423    1
424    2
Name: PKWNR, dtype: int64
2
ID: 4701032811
ID: 4701032830
16867    1
16899    2
Name: PERSNR, dtype: int32
2
426    1
427    2
Name: PKWNR, dtype: int64
2
ID: 4701032833
16926    1
Name: PERSNR, dtype: int32
1
428    1
Name: PKWNR, dtype: int64
1
ID: 4701032844
16936    1
16970    2
16996    3
17022    4
Name: PERSNR, dtype: int32
4
429    1
431    4
430    3
432    2
Name: PKWNR, dtype: int64
4
ID: 4701032854
17066    1
17120    2

Name: PERSNR, dtype: int32
2
433    1
434    2
Name: PKWNR, dtype: int64
2
ID: 4701032863
17137    1
17151    2
17175    4
Name: PERSNR, dtype: int32
3
437    3
435    1
436    2
Name: PKWNR, dtype: int64
3
ID: 4701032864
17189    1
17208    2
Name: PERSNR, dtype: int32
2
438    1
439    2
Name: PKWNR, dtype: int64
2
ID: 4701032888
17233    1
Name: PERSNR, dtype: int32
1
440    1
Name: PKWNR, dtype: int64
1
ID: 4701032916
17253    1
Name: PERSNR, dtype: int32
1
441    1
Name: PKWNR, dtype: int64
1
ID: 4701032920
ID: 4701032928
17375    2
Name: PERSNR, dtype: int32
1
443    1
Name: PKWNR, dtype: int64
1
ID: 4701032945
17423    1
Name: PERSNR, dtype: int32
1
444    1
Name: PKWNR, dtype: int64
1
ID: 4701032949
17455    1
Name: PERSNR, dtype: int32
1
445    1
Name: PKWNR, dtype: int64
1
ID: 4701032951
17471    1
Name: PERSNR, dtype: int32
1
446    1
Name: PKWNR, dtype: int64
2
ID: 4701032954
17504    1
Name: PERSNR, dtype: int32
1
447    1
Name: PKWNR, dtype: int64
1
ID: 4701032963
17543    1
17564    2
Name: PERSNR, dtype: int32
2
448    1
Name: PKWNR, dtype: int64
1
ID: 4701032973
17596    2
Name: PERSNR, dtype: int32
1
449    1
Name: PKWNR, dtype: int64
1
ID: 4701032986
17618    1
17644    2
17678    4
Name: PERSNR, dtype: int32
3
451    1
450    2
Name: PKWNR, dtype: int64
4
ID: 4701032992
17688    1
Name: PERSNR, dtype: int32
1
452    1
Name: PKWNR, dtype: int64
1
ID: 4701032998
17703    1
Name: PERSNR, dtype: int32
1
453    1
Name: PKWNR, dtype: int64
1
ID: 4701033021
17736    2
Name: PERSNR, dtype: int32
1
454    1
Name: PKWNR, dtype: int64
1
ID: 4701033025
ID: 4701033033
17889    1
Name: PERSNR, dtype: int32
1
455    1
Name: PKWNR, dtype: int64
1
ID: 4701033038
17911    1
Name: PERSNR, dtype: int32
1
456    1
Name: PKWNR, dtype: int64
3
ID: 4701033054
17988    1
Name: PERSNR, dtype: int32
1
457    1
Name: PKWNR, dtype: int64
1
ID: 4701033055
18016    1
18033    2
Name: PERSNR, dtype: int32
2
458    2
459    1
Name: PKWNR, dtype: int64
2
ID: 4701033056
18059    1
Name: PERSNR, dtype: int32
1
460    1
461    2
Name: PKWNR, dtype: int64
2
ID: 4701033070
18106    1
Name: PERSNR, dtype: int32
1
462    1
Name: PKWNR, dtype: int64
1
ID: 4701033073
18124    1
18146    2
Name: PERSNR, dtype: int32
2
463    1
464    2
Name: PKWNR, dtype: int64
2
ID: 4701033074
18185    1
Name: PERSNR, dtype: int32
1
465    1
Name: PKWNR, dtype: int64
2
ID: 4701033084
18217    1
18243    2
18258    3
Name: PERSNR, dtype: int32
3
469    2
468    1
470    3
Name: PKWNR, dtype: int64
3
ID: 4701033086
18290    1
Name: PERSNR, dtype: int32
1
471    1
Name: PKWNR, dtype: int64
1
ID: 4701033099
18317    1
Name: PERSNR, dtype: int32
1
472    1
Name: PKWNR, dtype: int64
1
ID: 4701033100
ID: 4701033103
18413    1
18480    2
18500    3
Name: PERSNR, dtype: int32
3
473    1
Name: PKWNR, dtype: int64
1
ID: 4701033105
18601    1
Name: PERSNR, dtype: int32
1
475    1
474    2
Name: PKWNR, dtype: int64
2
ID: 4701033115
18620    1
18645    2
Name: PERSNR, dtype: int32
2
477    2
476    1
Name: PKWNR, dtype: int64
2
ID: 4701033134
18682    1
Name: PERSNR, dtype: int32
1
478    1
Name: PKWNR, dtype: int64
1
ID: 4701033236
18706    1
Name: PERSNR, dtype: int32
1
479    1
Name: PKWNR, dtype: int64
1
ID: 4701033264
18729    1
Name: PERSNR, dtype: int32
1
480    1
Name: PKWNR, dtype: int64
1
ID: 4701033272
18750    1
18779    2
Name: PERSNR, dtype: int32
2
481    1
482    2
Name: PKWNR, dtype: int64
2
ID: 4701033280
18869    1
Name: PERSNR, dtype: int32
1
483    1
Name: PKWNR, dtype: int64
1
ID: 4701033341
18938    2
Name: PERSNR, dtype: int32
1
484    1
Name: PKWNR, dtype: int64
2
ID: 4701033384
ID: 4701033389
19040    1
Name: PERSNR, dtype: int32
1
485    1
Name: PKWNR, dtype: int64
1
ID: 4701033395
ID: 4701033398
19105    1
Name: PERSNR, dtype: int32
1
486    1
Name: PKWNR, dtype: int64
1
ID: 4701033410
19107    1
19131    2
19149    3
Name: PERSNR, dtype: int32
3
487    1
489    3
488    2
Name: PKWNR, dtype: int64
3
ID: 4701033429
19211    1
19269    2
Name: PERSNR, dtype: int32
2
490    1
Name: PKWNR, dtype: int64
2
ID: 4701033430
19331    1
Name: PERSNR, dtype: int32
1
491    1
Name: PKWNR, dtype: int64
1
ID: 4701033454
19376    1
Name: PERSNR, dtype: int32
1
492    1
Name: PKWNR, dtype: int64
1
ID: 4701033460
19397    1
19417    2
Name: PERSNR, dtype: int32
2
493    1
Name: PKWNR, dtype: int64
1
ID: 4701033474
19529    2
19565    3
Name: PERSNR, dtype: int32
2
494    1
Name: PKWNR, dtype: int64
1
ID: 4701033480
19580    1
19610    2
Name: PERSNR, dtype: int32
2
496    2
495    1
Name: PKWNR, dtype: int64
2
ID: 4701033484
19630    1
Name: PERSNR, dtype: int32
1
497    1
Name: PKWNR, dtype: int64
1
ID: 4701033491
19671    1
Name: PERSNR, dtype: int32
1
498    1
Name: PKWNR, dtype: int64
1
ID: 4701033498
19709    2
Name: PERSNR, dtype: int32
1
499    1
Name: PKWNR, dtype: int64
1
ID: 4701033512
19729    1
19756    2
Name: PERSNR, dtype: int32
2
500    1
Name: PKWNR, dtype: int64
2
ID: 4701033541
19804    1
Name: PERSNR, dtype: int32
1
502    1
Name: PKWNR, dtype: int64
1
ID: 4701033543
19833    2
Name: PERSNR, dtype: int32
1
503    1
Name: PKWNR, dtype: int64
1
ID: 4701033544
19901    1
Name: PERSNR, dtype: int32
1
504    1
Name: PKWNR, dtype: int64
1
ID: 4701033567
19932    1
19970    2
Name: PERSNR, dtype: int32
2
505    1
506    2
Name: PKWNR, dtype: int64
2
ID: 4701033568
19992    1
20006    2
Name: PERSNR, dtype: int32
2
508    2
507    1
Name: PKWNR, dtype: int64
2
ID: 4701033615
20074    1
20080    2
Name: PERSNR, dtype: int32
2
509    1
Name: PKWNR, dtype: int64
1
ID: 4701033620
20097    1
20105    2
Name: PERSNR, dtype: int32
2
510    1
Name: PKWNR, dtype: int64
1
ID: 4701033645
20157    1
Name: PERSNR, dtype: int32
1
511    1
Name: PKWNR, dtype: int64
1
ID: 4701033647
ID: 4701033671
20249    1
20288    3
Name: PERSNR, dtype: int32
2
513    1
512    2
Name: PKWNR, dtype: int64
2
ID: 4701033770
20313    1
20344    2
Name: PERSNR, dtype: int32
2
515    2
514    1
Name: PKWNR, dtype: int64
2
ID: 4701033772
20385    1
20439    2
Name: PERSNR, dtype: int32
2
517    2
516    1
Name: PKWNR, dtype: int64
2
ID: 4701033775
20468    1
20490    2
Name: PERSNR, dtype: int32
2
518    1
Name: PKWNR, dtype: int64
1
ID: 4701033816
20523    1
Name: PERSNR, dtype: int32
1
519    1
Name: PKWNR, dtype: int64
1
ID: 4701033827
20556    1
20574    2
Name: PERSNR, dtype: int32
2
520    1
521    2
Name: PKWNR, dtype: int64
2
ID: 4701033842
20598    1
20623    2
Name: PERSNR, dtype: int32
2
523    2
522    1
Name: PKWNR, dtype: int64
2
ID: 4701033867
ID: 4701033869
20659    1
Name: PERSNR, dtype: int32
1
524    1
Name: PKWNR, dtype: int64
1
ID: 4701033872
20674    1
Name: PERSNR, dtype: int32
1
525    1
Name: PKWNR, dtype: int64
1
ID: 4701033886
20713    1
Name: PERSNR, dtype: int32
1
526    1
Name: PKWNR, dtype: int64
1
ID: 4701033937
20761    1
Name: PERSNR, dtype: int32
1
527    1
Name: PKWNR, dtype: int64
1
ID: 4701033942
20783    1
Name: PERSNR, dtype: int32
1
528    1
Name: PKWNR, dtype: int64
1
ID: 4701033960
20804    1
Name: PERSNR, dtype: int32
1
529    1
Name: PKWNR, dtype: int64
1
ID: 4701033963
20829    1
Name: PERSNR, dtype: int32
1
530    1
Name: PKWNR, dtype: int64
1
ID: 4701033964
ID: 4701033966
20880    1
Name: PERSNR, dtype: int32
1
531    1
Name: PKWNR, dtype: int64
1
ID: 4701033972
ID: 4701033985
20990    2
Name: PERSNR, dtype: int32
1
533    1
Name: PKWNR, dtype: int64
1
ID: 4701033995
21068    1
Name: PERSNR, dtype: int32
1
534    1
Name: PKWNR, dtype: int64
1
ID: 4701034032
21104    1
Name: PERSNR, dtype: int32
1
535    1
Name: PKWNR, dtype: int64
1
ID: 4701034034
21141    1
21174    2
Name: PERSNR, dtype: int32
2
536    1
Name: PKWNR, dtype: int64
1
ID: 4701034035
21212    1
Name: PERSNR, dtype: int32
1
537    1
Name: PKWNR, dtype: int64
1
ID: 4701034038
ID: 4701034057
21263    1
21304    2
Name: PERSNR, dtype: int32
2
538    1
Name: PKWNR, dtype: int64
1
ID: 4701034059
21311    1
Name: PERSNR, dtype: int32
1
539    1
Name: PKWNR, dtype: int64
1
ID: 4701034061
21356    1
Name: PERSNR, dtype: int32
1
540    1
Name: PKWNR, dtype: int64
2
ID: 4701034073
21400    1
Name: PERSNR, dtype: int32
1
541    1
Name: PKWNR, dtype: int64
1
ID: 4701034075
ID: 4701034076
21484    1
21500    2
Name: PERSNR, dtype: int32
2
542    1
Name: PKWNR, dtype: int64
1
ID: 4701034083
21525    1
Name: PERSNR, dtype: int32
1
543    1
Name: PKWNR, dtype: int64
1
ID: 4701034109
21568    1
Name: PERSNR, dtype: int32
1
544    1
Name: PKWNR, dtype: int64
2
ID: 4701034121
21593    1
Name: PERSNR, dtype: int32
1
545    1
Name: PKWNR, dtype: int64
1
ID: 4701034135
21625    1
21651    2
Name: PERSNR, dtype: int32
2
546    1
Name: PKWNR, dtype: int64
1
ID: 4701034142
21661    1
21700    2
21757    3
Name: PERSNR, dtype: int32
3
548    2
547    1
Name: PKWNR, dtype: int64
3
ID: 4701034157
21780    1
Name: PERSNR, dtype: int32
1
549    1
Name: PKWNR, dtype: int64
1
ID: 4701034169
ID: 4701034182
ID: 4701034185
ID: 4701034268
21894    1
21947    2
Name: PERSNR, dtype: int32
2
551    1
Name: PKWNR, dtype: int64
1
ID: 4701034271
ID: 4701034277
22021    2
Name: PERSNR, dtype: int32
1
552    1
Name: PKWNR, dtype: int64
1
ID: 4701034289
22029    1
22073    3
Name: PERSNR, dtype: int32
2
553    1
Name: PKWNR, dtype: int64
3
ID: 4701034294
22121    1
Name: PERSNR, dtype: int32
1
554    1
Name: PKWNR, dtype: int64
1
ID: 4701034321
22174    1
Name: PERSNR, dtype: int32
1
555    1
Name: PKWNR, dtype: int64
1
ID: 4701034346
22201    1
22238    2
Name: PERSNR, dtype: int32
2
556    1
557    2
Name: PKWNR, dtype: int64
3
ID: 4701034353
22280    2
Name: PERSNR, dtype: int32
1
558    1
Name: PKWNR, dtype: int64
1
ID: 4701034369
ID: 4701034370
22343    1
Name: PERSNR, dtype: int32
1
560    1
Name: PKWNR, dtype: int64
1
ID: 4701034373
22385    1
22404    2
Name: PERSNR, dtype: int32
2
561    1
562    2
Name: PKWNR, dtype: int64
2
ID: 4701034375
22497    1
Name: PERSNR, dtype: int32
1
563    1
Name: PKWNR, dtype: int64
1
ID: 4701034387
22510    1
Name: PERSNR, dtype: int32
1
564    1
Name: PKWNR, dtype: int64
1
ID: 4701034388
22538    1
22581    3
22606    4
Name: PERSNR, dtype: int32
3
565    1
Name: PKWNR, dtype: int64
2
ID: 4701034394
22617    1
22647    2
Name: PERSNR, dtype: int32
2
567    2
566    1
Name: PKWNR, dtype: int64
2
ID: 4701034398
22702    2
Name: PERSNR, dtype: int32
1
568    1
Name: PKWNR, dtype: int64
1
ID: 4701034418
22748    1
Name: PERSNR, dtype: int32
1
569    2
570    1
Name: PKWNR, dtype: int64
2
ID: 4701034428
22768    1
Name: PERSNR, dtype: int32
1
571    1
Name: PKWNR, dtype: int64
1
ID: 4701034491
ID: 4701034492
ID: 4701034494
22827    1
22850    2
Name: PERSNR, dtype: int32
2
572    1
Name: PKWNR, dtype: int64
1
ID: 4701034495
22854    1
Name: PERSNR, dtype: int32
1
573    1
Name: PKWNR, dtype: int64
1
ID: 4701034506
22881    1
Name: PERSNR, dtype: int32
1
574    1
Name: PKWNR, dtype: int64
2
ID: 4701034508
22902    1
22929    2
22962    3
Name: PERSNR, dtype: int32
3
575    1
Name: PKWNR, dtype: int64
1
ID: 4701034514
22970    1
Name: PERSNR, dtype: int32
1
576    1
Name: PKWNR, dtype: int64
1
ID: 4701034515
22997    1
Name: PERSNR, dtype: int32
1
577    1
Name: PKWNR, dtype: int64
1
ID: 4701034517
23013    1
Name: PERSNR, dtype: int32
1
578    1
Name: PKWNR, dtype: int64
1
ID: 4701034530
ID: 4701034547
23123    2
Name: PERSNR, dtype: int32
1
580    1
Name: PKWNR, dtype: int64
1
ID: 4701034550
23161    1
23175    2
Name: PERSNR, dtype: int32
2
581    1
Name: PKWNR, dtype: int64
1
ID: 4701034554

23198    1
23216    2
23250    4
Name: PERSNR, dtype: int32
3
583    2
582    1
Name: PKWNR, dtype: int64
3
ID: 4701034575
23290    1
23322    2
Name: PERSNR, dtype: int32
2
584    1
Name: PKWNR, dtype: int64
1
ID: 4701034581
23384    1
23399    2
Name: PERSNR, dtype: int32
2
585    1
Name: PKWNR, dtype: int64
1
ID: 4701034591
23459    1
Name: PERSNR, dtype: int32
1
586    1
Name: PKWNR, dtype: int64
2
ID: 4701034595
23484    1
Name: PERSNR, dtype: int32
1
587    1
Name: PKWNR, dtype: int64
1
ID: 4701034599
ID: 4701034617
23609    1
23698    2
Name: PERSNR, dtype: int32
2
589    1
588    2
Name: PKWNR, dtype: int64
2
ID: 4701034623
ID: 4701034640
23785    2
Name: PERSNR, dtype: int32
1
590    1
Name: PKWNR, dtype: int64
1
ID: 4701034644
23861    2
23902    4
Name: PERSNR, dtype: int32
2
591    1
Name: PKWNR, dtype: int64
1
ID: 4701034647
23923    1
23960    2
Name: PERSNR, dtype: int32
2
592    1
Name: PKWNR, dtype: int64
1
ID: 4701034657
23969    1
Name: PERSNR, dtype: int32
1
593    1
Name: PKWNR, dtype: int64
1
ID: 4701034659
24081    2
Name: PERSNR, dtype: int32
1
594    1
Name: PKWNR, dtype: int64
1
ID: 4701034696
24101    1
24114    2
Name: PERSNR, dtype: int32
2
595    1
Name: PKWNR, dtype: int64
2
ID: 4701034704
24131    1
24156    2
Name: PERSNR, dtype: int32
2
596    1
Name: PKWNR, dtype: int64
1
ID: 4701034710
24161    1
24191    2
Name: PERSNR, dtype: int32
2
598    2
597    1
Name: PKWNR, dtype: int64
3
ID: 4701034711
ID: 4701034749
24264    1
24286    2
24320    4
Name: PERSNR, dtype: int32
3
600    1
601    3
599    2
Name: PKWNR, dtype: int64
3
ID: 4701034766
24338    1
24381    2
Name: PERSNR, dtype: int32
2
602    1
603    2
Name: PKWNR, dtype: int64
2
ID: 4701034770
24400    1
24420    2
Name: PERSNR, dtype: int32
2
604    1
Name: PKWNR, dtype: int64
1
ID: 4701034773
24469    2
Name: PERSNR, dtype: int32
1
605    1
Name: PKWNR, dtype: int64
1
ID: 4701034786
24483    1
Name: PERSNR, dtype: int32
1
606    1
Name: PKWNR, dtype: int64
1
ID: 4701034793
ID: 4701034874
24513    1
24533    2
Name: PERSNR, dtype: int32
2
609    2
607    3
608    1
Name: PKWNR, dtype: int64
3
ID: 4701034893
24558    1
24603    2
Name: PERSNR, dtype: int32
2
611    2
610    1
Name: PKWNR, dtype: int64
2
ID: 4701034940
24697    1
Name: PERSNR, dtype: int32
1
614    1
Name: PKWNR, dtype: int64
4
ID: 4701034953
24824    1
Name: PERSNR, dtype: int32
1
615    1
Name: PKWNR, dtype: int64
1
ID: 4701034954
24842    1
Name: PERSNR, dtype: int32
1
616    1
Name: PKWNR, dtype: int64
1
ID: 4701034957
24865    1
Name: PERSNR, dtype: int32
1
617    1
Name: PKWNR, dtype: int64
2
ID: 4701034978
24881    1
24908    2
Name: PERSNR, dtype: int32
2
619    2
618    1
Name: PKWNR, dtype: int64
2
ID: 4701034993
ID: 4701035101
25005    1
25029    2
Name: PERSNR, dtype: int32
2
620    1
Name: PKWNR, dtype: int64
1
ID: 4701035103
ID: 4701035114
25073    1
Name: PERSNR, dtype: int32
1
621    1
Name: PKWNR, dtype: int64
1
ID: 4701035119
25099    1
Name: PERSNR, dtype: int32
1
622    1
Name: PKWNR, dtype: int64
1
ID: 4701035130
25155    1
25188    2
Name: PERSNR, dtype: int32
2
623    1
624    2
Name: PKWNR, dtype: int64
2
ID: 4701035137
25240    1
25244    2
Name: PERSNR, dtype: int32
2
625    1
Name: PKWNR, dtype: int64
1
ID: 4701035139
25321    2
Name: PERSNR, dtype: int32
1
626    1
Name: PKWNR, dtype: int64
1
ID: 4701035141
25359    1
25371    2
Name: PERSNR, dtype: int32
2
627    1
Name: PKWNR, dtype: int64
1
ID: 4701035149
25401    1
25409    2
Name: PERSNR, dtype: int32
2
628    2
629    1
Name: PKWNR, dtype: int64
2
ID: 4701035166
25426    1
25440    2
Name: PERSNR, dtype: int32
2
630    1
631    2
Name: PKWNR, dtype: int64
2
ID: 4701035171
25478    1
25490    2
Name: PERSNR, dtype: int32
2
632    1
Name: PKWNR, dtype: int64
1
ID: 4701035184
ID: 4701035195
25564    1
25587    2
Name: PERSNR, dtype: int32
2
635    3
634    2
633    1
Name: PKWNR, dtype: int64
3
ID: 4701035196
25623    2
Name: PERSNR, dtype: int32
1
636    2
637    1
Name: PKWNR, dtype: int64
2
ID: 4701035222
25657    1
25676    2
25697    3
25720    4
Name: PERSNR, dtype: int32
4
639    3
640    2
638    1
Name: PKWNR, dtype: int64
3
ID: 4701035279
25782    1
25804    2
25812    3
Name: PERSNR, dtype: int32
3
641    1
642    2
Name: PKWNR, dtype: int64
2
ID: 4701035286
25895    1
25912    2
Name: PERSNR, dtype: int32
2
643    1
645    2
644    3
646    4
Name: PKWNR, dtype: int64
5
ID: 4701035300
ID: 4701035305
25993    1
Name: PERSNR, dtype: int32
1
647    1
Name: PKWNR, dtype: int64
1
ID: 4701035345
ID: 4701035372
26116    1
Name: PERSNR, dtype: int32
1
649    1
648    2
Name: PKWNR, dtype: int64
2
ID: 4701035373
ID: 4701035387
26173    1
Name: PERSNR, dtype: int32
1
650    1
Name: PKWNR, dtype: int64
1
ID: 4701035397
26221    1
Name: PERSNR, dtype: int32
1
651    1
Name: PKWNR, dtype: int64
4
ID: 4701035404
26233    1
Name: PERSNR, dtype: int32
1
652    1
Name: PKWNR, dtype: int64
2
ID: 4701035419
26251    1
Name: PERSNR, dtype: int32
1
653    1
Name: PKWNR, dtype: int64
1
ID: 4701035471
26276    1
26313    2
Name: PERSNR, dtype: int32
2
654    1
Name: PKWNR, dtype: int64
1
ID: 4701035596
26345    3
Name: PERSNR, dtype: int32
1
656    1
655    2
Name: PKWNR, dtype: int64
2
ID: 4701035634
26395    1
Name: PERSNR, dtype: int32
1
657    1
Name: PKWNR, dtype: int64
1
ID: 4701035636
ID: 4701035664
26523    1
26561    2
Name: PERSNR, dtype: int32
2
658    1
Name: PKWNR, dtype: int64
1
ID: 4701035688
ID: 4701035703
26659    1
Name: PERSNR, dtype: int32
1
659    1
Name: PKWNR, dtype: int64
1
ID: 4701035708
26677    2
Name: PERSNR, dtype: int32
1
660    1
Name: PKWNR, dtype: int64
1
ID: 4701035779
ID: 4701035822
26842    2
Name: PERSNR, dtype: int32
1
661    1
Name: PKWNR, dtype: int64
1
ID: 4701035873
26940    1
Name: PERSNR, dtype: int32
1
662    1
Name: PKWNR, dtype: int64
1
ID: 4701035981
26982    1
Name: PERSNR, dtype: int32
1
663    1
Name: PKWNR, dtype: int64
1
ID: 4701036000
26999    1
Name: PERSNR, dtype: int32
1
664    1
Name: PKWNR, dtype: int64
1
ID: 4701036022
27037    1
Name: PERSNR, dtype: int32
1
665    1
Name: PKWNR, dtype: int64
1
ID: 4711030011
27061    1
Name: PERSNR, dtype: int32
1
667    2
666    1
Name: PKWNR, dtype: int64
2
ID: 4711030027
27155    1
27213    4
Name: PERSNR, dtype: int32
2
668    1
Name: PKWNR, dtype: int64
1
ID: 4711030028
27250    1
Name: PERSNR, dtype: int32
1
669    1
670    2
Name: PKWNR, dtype: int64
2
ID: 4711030062
ID: 4711030077
27376    2
Name: PERSNR, dtype: int32
1
671    1
Name: PKWNR, dtype: int64
1
ID: 4711030079
27408    1
27434    2
Name: PERSNR, dtype: int32
2
672    1
Name: PKWNR, dtype: int64
1
ID: 4711030091
ID: 4711030110
ID: 4711030135
27628    1
Name: PERSNR, dtype: int32
1
673    1
Name: PKWNR, dtype: int64
1
ID: 4711030155
27654    1
Name: PERSNR, dtype: int32
1
674    1
Name: PKWNR, dtype: int64
2
ID: 4711030171
ID: 4711030172
27689    1
Name: PERSNR, dtype: int32
1
675    1
Name: PKWNR, dtype: int64
1
ID: 4711030178
ID: 4711030201
27787    1
27812    2
27840    3
Name: PERSNR, dtype: int32
3
677    2
678    3
676    1
Name: PKWNR, dtype: int64
3
ID: 4711030210
ID: 4711030222
ID: 4711030225
ID: 4711030238
28072    1
Name: PERSNR, dtype: int32
1
679    1
Name: PKWNR, dtype: int64
1
ID: 4711030247
ID: 4711030249
ID: 4711030261
28190    1
Name: PERSNR, dtype: int32
1
680    1
Name: PKWNR, dtype: int64
1
ID: 4711030271
ID: 4711030291
ID: 4711030345
28301    1
Name: PERSNR, dtype: int32
1
681    1
Name: PKWNR, dtype: int64
1
ID: 4711030372
28303    1
Name: PERSNR, dtype: int32
1
682    1
Name: PKWNR, dtype: int64
1
ID: 4711030380
28334    1
Name: PERSNR, dtype: int32
1
683    1
Name: PKWNR, dtype: int64
1
ID: 4711030388
28357    1
28383    2
Name: PERSNR, dtype: int32
2
684    2
685    1
Name: PKWNR, dtype: int64
2
ID: 4711030399
28420    1
28437    2
Name: PERSNR, dtype: int32
2
686    1
687    2
Name: PKWNR, dtype: int64
2
ID: 4711030410
ID: 4711030414
28491    1
28512    2
Name: PERSNR, dtype: int32
2
689    1
688    2
Name: PKWNR, dtype: int64
2
ID: 4711030426
28570    1
Name: PERSNR, dtype: int32
1
690    1
Name: PKWNR, dtype: int64
1
ID: 4711030528
28615    1
28629    2
Name: PERSNR, dtype: int32
2
691    1
692    2
Name: PKWNR, dtype: int64
2
ID: 4711030556
ID: 4711030594
28694    1
28728    2
Name: PERSNR, dtype: int32
2
693    1
Name: PKWNR, dtype: int64
2
ID: 4711030599
28761    1
Name: PERSNR, dtype: int32
1
694    1
Name: PKWNR, dtype: int64
1
ID: 4711030608
28775    1
Name: PERSNR, dtype: int32
1
695    1
Name: PKWNR, dtype: int64
1
ID: 4711030613
28801    1
28820    2
28828    3
Name: PERSNR, dtype: int32
3
696    1
698    3
697    2
Name: PKWNR, dtype: int64
3
ID: 4711030635
28859    1
Name: PERSNR, dtype: int32
1
699    1
Name: PKWNR, dtype: int64
1
ID: 4711030639
28890    1
Name: PERSNR, dtype: int32
1
700    1
Name: PKWNR, dtype: int64
1
ID: 4711030651
28940    1
28952    2
Name: PERSNR, dtype: int32
2
701    1
Name: PKWNR, dtype: int64
1
ID: 4711030672
ID: 4711030678
29059    1
29101    2
29122    3
29144    4
29177    5
Name: PERSNR, dtype: int32
5
704    2
706    3
703    1
702    4
705    5
Name: PKWNR, dtype: int64
5
ID: 4711030684
ID: 4711030692
29224    1
29249    2
Name: PERSNR, dtype: int32
2
708    2
707    1
Name: PKWNR, dtype: int64
2
ID: 4711030700
ID: 4711030714
29333    1
Name: PERSNR, dtype: int32
1
709    1
Name: PKWNR, dtype: int64
1
ID: 4711030722
29337    1
29372    2
Name: PERSNR, dtype: int32
2
710    1
Name: PKWNR, dtype: int64
5
ID: 4711030733
29399    1
Name: PERSNR, dtype: int32
1
711    1
Name: PKWNR, dtype: int64
1
ID: 4711030742
ID: 4711030769
29429    1
29455    2
Name: PERSNR, dtype: int32
2
712    1
Name: PKWNR, dtype: int64
1
ID: 4711030782
29476    1
29490    2
Name: PERSNR, dtype: int32
2
714    2
713    1
Name: PKWNR, dtype: int64
2
ID: 4711030807
29532    1
29574    2
29599    3
Name: PERSNR, dtype: int32
3
715    1
Name: PKWNR, dtype: int64
3
ID: 4711030820
29653    1
Name: PERSNR, dtype: int32
1
716    1
Name: PKWNR, dtype: int64
1
ID: 4711030855
29656    1
29697    2
Name: PERSNR, dtype: int32
2
717    1
Name: PKWNR, dtype: int64
1
ID: 4711030859
ID: 4711030900
29754    1
Name: PERSNR, dtype: int32
1
720    1
Name: PKWNR, dtype: int64
1
ID: 4711030916
29771    1
29806    2
Name: PERSNR, dtype: int32
2
721    1
722    2
Name: PKWNR, dtype: int64
2
ID: 4711030920
ID: 4711030925
ID: 4711030931
29895    1
29922    2
Name: PERSNR, dtype: int32
2
723    2
724    1
Name: PKWNR, dtype: int64
2
ID: 4711030963
29948    1
29987    2
Name: PERSNR, dtype: int32
2
725    1
Name: PKWNR, dtype: int64
1
ID: 4711030973
30002    1
30026    2
Name: PERSNR, dtype: int32
2
726    1
Name: PKWNR, dtype: int64
1
ID: 4711030976
30038    1
30068    4
Name: PERSNR, dtype: int32
2
727    1
728    2
Name: PKWNR, dtype: int64
2
ID: 4711030984
30089    1
30108    2

Name: PERSNR, dtype: int32
2
731    2
729    1
730    3
Name: PKWNR, dtype: int64
3
ID: 4711031004
30188    1
Name: PERSNR, dtype: int32
1
732    1
Name: PKWNR, dtype: int64
2
ID: 4711031005
30205    1
Name: PERSNR, dtype: int32
1
733    1
Name: PKWNR, dtype: int64
1
ID: 4711031010
30221    1
30247    2
30302    3
30318    4
Name: PERSNR, dtype: int32
4
735    2
734    1
Name: PKWNR, dtype: int64
2
ID: 4711031065
30376    1
Name: PERSNR, dtype: int32
1
736    1
Name: PKWNR, dtype: int64
1
ID: 4711031069
ID: 4711031070
30495    1
Name: PERSNR, dtype: int32
1
737    1
Name: PKWNR, dtype: int64
1
ID: 4711031168
30516    1
30552    2
Name: PERSNR, dtype: int32
2
738    1
Name: PKWNR, dtype: int64
1
ID: 4711031183
ID: 4711031186
30647    1
Name: PERSNR, dtype: int32
1
739    1
Name: PKWNR, dtype: int64
2
ID: 4711031198
ID: 4711031209
ID: 4711031220
30773    1
Name: PERSNR, dtype: int32
1
740    1
Name: PKWNR, dtype: int64
1
ID: 4711031234
ID: 4711031298
30830    1
30845    2
Name: PERSNR, dtype: int32
2
742    1
Name: PKWNR, dtype: int64
1
ID: 4711031301
ID: 4711031328
30947    1
Name: PERSNR, dtype: int32
1
743    1
Name: PKWNR, dtype: int64
1
ID: 4711031330
30991    1
31011    2
Name: PERSNR, dtype: int32
2
745    2
744    1
Name: PKWNR, dtype: int64
2
ID: 4711031332
31048    1
Name: PERSNR, dtype: int32
1
746    1
747    2
Name: PKWNR, dtype: int64
2
ID: 4711031333
31072    1
Name: PERSNR, dtype: int32
1
748    1
Name: PKWNR, dtype: int64
1
ID: 4711031346
31116    1
31142    2
31171    3
Name: PERSNR, dtype: int32
3
750    2
749    1
Name: PKWNR, dtype: int64
2
ID: 4711031356
31183    1
Name: PERSNR, dtype: int32
1
753    2
754    4
752    3
751    1
Name: PKWNR, dtype: int64
4
ID: 4711031357
31205    1
31222    2
Name: PERSNR, dtype: int32
2
756    2
755    1
Name: PKWNR, dtype: int64
2
ID: 4711031370
ID: 4711031398
31265    1
31273    2
Name: PERSNR, dtype: int32
2
757    1
Name: PKWNR, dtype: int64
1
ID: 4711031419
31286    1
Name: PERSNR, dtype: int32
1
758    1
Name: PKWNR, dtype: int64
1
ID: 4711031427
ID: 4711031429
31355    1
Name: PERSNR, dtype: int32
1
759    1
Name: PKWNR, dtype: int64
1
ID: 4711031484
31375    1
Name: PERSNR, dtype: int32
1
760    1
Name: PKWNR, dtype: int64
1
ID: 4711031545
31401    1
Name: PERSNR, dtype: int32
1
761    1
Name: PKWNR, dtype: int64
1
ID: 4711031581
31447    1
31491    2
Name: PERSNR, dtype: int32
2
762    1
763    2
Name: PKWNR, dtype: int64
2
ID: 4711031600
ID: 4711031609
31528    1
31553    2
Name: PERSNR, dtype: int32
2
765    2
766    3
764    1
Name: PKWNR, dtype: int64
3
ID: 4711031623
ID: 4711031635
ID: 4711031640
31632    1
Name: PERSNR, dtype: int32
1
767    1
Name: PKWNR, dtype: int64
1
ID: 4711031686
31673    1
Name: PERSNR, dtype: int32
1
768    1
Name: PKWNR, dtype: int64
1
ID: 4711031693
31705    1
31732    2
31756    3
Name: PERSNR, dtype: int32
3
770    2
769    1
Name: PKWNR, dtype: int64
3
ID: 4711031704
ID: 4711031718
31889    1
Name: PERSNR, dtype: int32
1
771    1
Name: PKWNR, dtype: int64
2
ID: 4711031729
31916    1
31953    4
Name: PERSNR, dtype: int32
2
772    1
773    2
Name: PKWNR, dtype: int64
2
ID: 4711031734
31977    1
32004    2
Name: PERSNR, dtype: int32
2
774    1
775    2
Name: PKWNR, dtype: int64
2
ID: 4711031745
32017    1
Name: PERSNR, dtype: int32
1
776    1
Name: PKWNR, dtype: int64
1
ID: 4711031766
32061    1
32085    2
32121    3
Name: PERSNR, dtype: int32
3
777    1
779    3
778    2
Name: PKWNR, dtype: int64
3
ID: 4711031767
32135    1
32155    2
Name: PERSNR, dtype: int32
2
780    1
781    2
Name: PKWNR, dtype: int64
2
ID: 4711031773
32163    1
Name: PERSNR, dtype: int32
1
782    1
Name: PKWNR, dtype: int64
1
ID: 4711031790
32185    1
Name: PERSNR, dtype: int32
1
783    1
Name: PKWNR, dtype: int64
1
ID: 4711031803
ID: 4711031854
32236    1
Name: PERSNR, dtype: int32
1
784    1
Name: PKWNR, dtype: int64
1
ID: 4711031890
32292    2
Name: PERSNR, dtype: int32
1
785    1
Name: PKWNR, dtype: int64
1
ID: 4711031936
32316    1
Name: PERSNR, dtype: int32
1
786    1
Name: PKWNR, dtype: int64
1
ID: 4711031937
32353    1
Name: PERSNR, dtype: int32
1
787    1
Name: PKWNR, dtype: int64
1
ID: 4711031982
ID: 4711031993
32400    1
Name: PERSNR, dtype: int32
1
788    1
Name: PKWNR, dtype: int64
1
ID: 4711032013
32430    1
Name: PERSNR, dtype: int32
1
789    1
Name: PKWNR, dtype: int64
1
ID: 4711032031
ID: 4711032100
32592    2
Name: PERSNR, dtype: int32
1
790    1
Name: PKWNR, dtype: int64
1
ID: 4711032164
ID: 4711032170
32666    2
Name: PERSNR, dtype: int32
1
791    1
Name: PKWNR, dtype: int64
1
ID: 4711032190
32716    1
Name: PERSNR, dtype: int32
1
792    1
Name: PKWNR, dtype: int64
1
ID: 4711036093
ID: 4711036104
32751    1
32772    2
Name: PERSNR, dtype: int32
2
798    4
793    1
796    6
797    5
795    3
794    2
Name: PKWNR, dtype: int64
6
ID: 4711036120
32794    1
32818    2
Name: PERSNR, dtype: int32
2
800    2
799    1
Name: PKWNR, dtype: int64
2
ID: 4711036125
32858    1
Name: PERSNR, dtype: int32
1
802    2
801    1
Name: PKWNR, dtype: int64
2
ID: 4711036128
ID: 4711036134
ID: 4901042448
32925    1
32950    2
32972    4
Name: PERSNR, dtype: int32
3
803    1
804    2
Name: PKWNR, dtype: int64
3
ID: 4901042457
32989    1
33015    2
33028    3
Name: PERSNR, dtype: int32
3
805    1
806    2
Name: PKWNR, dtype: int64
2
ID: 4901042469
33076    1
Name: PERSNR, dtype: int32
1
807    1
Name: PKWNR, dtype: int64
1
ID: 4901042477
ID: 4901042492
33111    1
33152    2
Name: PERSNR, dtype: int32
2
808    1
Name: PKWNR, dtype: int64
1
ID: 4901042531
33170    1
Name: PERSNR, dtype: int32
1
809    1
Name: PKWNR, dtype: int64
2
ID: 4901042534
33222    1
Name: PERSNR, dtype: int32
1
810    1
Name: PKWNR, dtype: int64
1
ID: 4901042544
ID: 4901042549
33267    1
Name: PERSNR, dtype: int32
1
811    1
Name: PKWNR, dtype: int64
2
ID: 4901042558
33298    1
33308    2
Name: PERSNR, dtype: int32
2
813    2
812    1
Name: PKWNR, dtype: int64
2
ID: 4901042565
33317    1
Name: PERSNR, dtype: int32
1
814    1
Name: PKWNR, dtype: int64
2
ID: 4901042566
33327    1
Name: PERSNR, dtype: int32
1
815    1
Name: PKWNR, dtype: int64
1
ID: 4901042567
33360    1
Name: PERSNR, dtype: int32
1
816    1
Name: PKWNR, dtype: int64
1
ID: 4901042571
ID: 4901042574
33439    1
33460    2
Name: PERSNR, dtype: int32
2
817    1
818    2
Name: PKWNR, dtype: int64
2
ID: 4901042606
33504    1
Name: PERSNR, dtype: int32
1
819    1
Name: PKWNR, dtype: int64
1
ID: 4901042610
ID: 4901042643
33607    1
Name: PERSNR, dtype: int32
1
820    1
Name: PKWNR, dtype: int64
1
ID: 4901042654
33638    1
Name: PERSNR, dtype: int32
1
821    1
Name: PKWNR, dtype: int64
1
ID: 4901042665
ID: 4901042668
ID: 4901042758
33715    1
33739    2
Name: PERSNR, dtype: int32
2
822    1
Name: PKWNR, dtype: int64
1
ID: 4901042775
ID: 4901042803
33780    1
Name: PERSNR, dtype: int32
1
823    1
824    2
Name: PKWNR, dtype: int64
2
ID: 4901042806
33801    1
Name: PERSNR, dtype: int32
1
825    1
Name: PKWNR, dtype: int64
1
ID: 4901042810
33823    1
Name: PERSNR, dtype: int32
1
826    1
Name: PKWNR, dtype: int64
1
ID: 4901042814
ID: 4901042817
33899    1
Name: PERSNR, dtype: int32
1
827    1
Name: PKWNR, dtype: int64
1
ID: 4901042821
33924    1
Name: PERSNR, dtype: int32
1
828    1
Name: PKWNR, dtype: int64
1
ID: 4901042834
ID: 4901042835
34008    2
Name: PERSNR, dtype: int32
1
829    1
Name: PKWNR, dtype: int64
1
ID: 4901042839
34033    1
Name: PERSNR, dtype: int32
1
830    1
Name: PKWNR, dtype: int64
1
ID: 4901042840
ID: 4901042859
34086    2
Name: PERSNR, dtype: int32
1
832    2
831    1
Name: PKWNR, dtype: int64
2
ID: 4901042861
34116    1
Name: PERSNR, dtype: int32
1
833    1
Name: PKWNR, dtype: int64
1
ID: 4901042869
34148    1
Name: PERSNR, dtype: int32
1
834    1
Name: PKWNR, dtype: int64
1
ID: 4901042879
34178    1
Name: PERSNR, dtype: int32
1
835    1
Name: PKWNR, dtype: int64
1
ID: 4901042884
ID: 4901042927
34317    1
Name: PERSNR, dtype: int32
1
836    1
Name: PKWNR, dtype: int64
1
ID: 4901042987
34391    1
Name: PERSNR, dtype: int32
1
837    1
Name: PKWNR, dtype: int64
1
ID: 4901042988
34421    1
Name: PERSNR, dtype: int32
1
838    1
Name: PKWNR, dtype: int64
1
ID: 4901042991
34455    1
Name: PERSNR, dtype: int32
1
839    1
Name: PKWNR, dtype: int64
1
ID: 4901043002
34486    1
Name: PERSNR, dtype: int32
1
840    1
Name: PKWNR, dtype: int64
1
ID: 4901043014
34499    1
Name: PERSNR, dtype: int32
1
841    1
Name: PKWNR, dtype: int64
1
ID: 4901043019
34533    1
34561    2
Name: PERSNR, dtype: int32
2
842    1
Name: PKWNR, dtype: int64
1
ID: 4901043030
34613    1
34633    2
Name: PERSNR, dtype: int32
2
844    2
843    1
Name: PKWNR, dtype: int64
2
ID: 4901043042
34656    1
Name: PERSNR, dtype: int32
1
845    1
Name: PKWNR, dtype: int64
1
ID: 4901043049
34711    1
Name: PERSNR, dtype: int32
1
846    1
Name: PKWNR, dtype: int64
1
ID: 4901043052
34740    1
Name: PERSNR, dtype: int32
1
847    1
Name: PKWNR, dtype: int64
1
ID: 4901043061
34788    1
Name: PERSNR, dtype: int32
1
848    1
Name: PKWNR, dtype: int64
3
ID: 4901043069
34829    1
Name: PERSNR, dtype: int32
1
849    1
Name: PKWNR, dtype: int64
1
ID: 4901043132
ID: 4901043133
34906    1
34917    2
Name: PERSNR, dtype: int32
2
850    1
Name: PKWNR, dtype: int64
1
ID: 4901043134
34944    1
34974    2
Name: PERSNR, dtype: int32
2
851    1
Name: PKWNR, dtype: int64
3
ID: 4901043146
35021    1
Name: PERSNR, dtype: int32
1
852    1
853    2
Name: PKWNR, dtype: int64
2
ID: 4901043156
ID: 4901043158
35089    1
Name: PERSNR, dtype: int32
1
854    1
Name: PKWNR, dtype: int64
1
ID: 4901043163
35127    1
Name: PERSNR, dtype: int32
1
855    1
Name: PKWNR, dtype: int64
2
ID: 4901043164
35145    1
35224    3
Name: PERSNR, dtype: int32
2
856    1
Name: PKWNR, dtype: int64
1
ID: 4901043165
35259    1
35285    2
Name: PERSNR, dtype: int32
2
857    1
Name: PKWNR, dtype: int64
1
ID: 4901043168
ID: 4901043175
35371    3
35397    4
Name: PERSNR, dtype: int32
2
859    2
858    1
Name: PKWNR, dtype: int64
2
ID: 4901043193
35443    1
35458    2
35481    3
35501    4
Name: PERSNR, dtype: int32
4
860    1
861    2
Name: PKWNR, dtype: int64
2
ID: 4901043200
ID: 4901043213
ID: 4901043240
35581    1
Name: PERSNR, dtype: int32
1
862    1
Name: PKWNR, dtype: int64
1
ID: 4901043241
ID: 4901043245
35737    1
35763    2
Name: PERSNR, dtype: int32
2
863    1
Name: PKWNR, dtype: int64
2
ID: 4901043247
35788    1
Name: PERSNR, dtype: int32
1
864    1
Name: PKWNR, dtype: int64
1
ID: 4901043258

35859    1
35881    2
Name: PERSNR, dtype: int32
2
865    1
866    2
Name: PKWNR, dtype: int64
2
ID: 4901043263
35904    1
Name: PERSNR, dtype: int32
1
867    1
Name: PKWNR, dtype: int64
1
ID: 4901043270
35940    1
Name: PERSNR, dtype: int32
1
868    1
Name: PKWNR, dtype: int64
1
ID: 4901043288
35984    1
36006    2
Name: PERSNR, dtype: int32
2
869    1
Name: PKWNR, dtype: int64
1
ID: 4901043289
36027    1
36050    2
Name: PERSNR, dtype: int32
2
870    1
871    2
Name: PKWNR, dtype: int64
2
ID: 4901043298
36072    1
Name: PERSNR, dtype: int32
1
873    2
872    1
Name: PKWNR, dtype: int64
2
ID: 4901043301
36089    1
36121    2
Name: PERSNR, dtype: int32
2
874    1
875    2
Name: PKWNR, dtype: int64
2
ID: 4901043315
36139    1
Name: PERSNR, dtype: int32
1
876    1
Name: PKWNR, dtype: int64
1
ID: 4901043342
ID: 4901043369
36194    1
36226    2
36243    3
Name: PERSNR, dtype: int32
3
877    1
878    2
Name: PKWNR, dtype: int64
3
ID: 4901043377
36260    1
36277    2
Name: PERSNR, dtype: int32
2
880    2
879    1
Name: PKWNR, dtype: int64
2
ID: 4901043380
36291    1
36313    2
36346    3
Name: PERSNR, dtype: int32
3
881    1
882    2
Name: PKWNR, dtype: int64
2
ID: 4901043491
36416    1
36441    2
Name: PERSNR, dtype: int32
2
883    1
Name: PKWNR, dtype: int64
2
ID: 4901043496
36448    1
36468    2
Name: PERSNR, dtype: int32
2
885    2
884    1
Name: PKWNR, dtype: int64
2
ID: 4901043502
36484    1
36503    2
Name: PERSNR, dtype: int32
2
887    2
886    1
Name: PKWNR, dtype: int64
2
ID: 4901043506
36536    1
Name: PERSNR, dtype: int32
1
888    1
Name: PKWNR, dtype: int64
1
ID: 4901043513
ID: 4901043516
36608    2
Name: PERSNR, dtype: int32
1
889    1
890    2
Name: PKWNR, dtype: int64
2
ID: 4901043522
36623    1
Name: PERSNR, dtype: int32
1
891    1
Name: PKWNR, dtype: int64
1
ID: 4901043528
36653    1
Name: PERSNR, dtype: int32
1
892    1
Name: PKWNR, dtype: int64
1
ID: 4901043534
ID: 4901043535
ID: 4901043541
36767    1
Name: PERSNR, dtype: int32
1
893    1
Name: PKWNR, dtype: int64
1
ID: 4901043545
36797    1
36814    2
Name: PERSNR, dtype: int32
2
894    1
Name: PKWNR, dtype: int64
1
ID: 4901043550
ID: 4901043593
36909    1
36920    2
Name: PERSNR, dtype: int32
2
895    1
896    2
Name: PKWNR, dtype: int64
2
ID: 4901043598
ID: 4901043609
36978    1
36993    2
Name: PERSNR, dtype: int32
2
898    2
897    1
Name: PKWNR, dtype: int64
2
ID: 4901043614
37026    1
Name: PERSNR, dtype: int32
1
899    1
Name: PKWNR, dtype: int64
2
ID: 4901043626
37043    1
37069    2
Name: PERSNR, dtype: int32
2
900    1
901    2
Name: PKWNR, dtype: int64
2
ID: 4901043630
37099    1
37117    2
Name: PERSNR, dtype: int32
2
903    2
902    1
Name: PKWNR, dtype: int64
2
ID: 4901043634
ID: 4901043644
37178    1
37229    2
Name: PERSNR, dtype: int32
2
904    1
Name: PKWNR, dtype: int64
1
ID: 4901043648
37269    1
37312    2
Name: PERSNR, dtype: int32
2
905    1
Name: PKWNR, dtype: int64
1
ID: 4901043654
37343    1
Name: PERSNR, dtype: int32
1
906    1
Name: PKWNR, dtype: int64
2
ID: 4901043656
37411    1
37423    2
Name: PERSNR, dtype: int32
2
907    1
Name: PKWNR, dtype: int64
1
ID: 4901043658
37447    1
Name: PERSNR, dtype: int32
1
908    1
Name: PKWNR, dtype: int64
1
ID: 4901043666
37498    2
Name: PERSNR, dtype: int32
1
909    1
Name: PKWNR, dtype: int64
1
ID: 4901043667
37521    1
Name: PERSNR, dtype: int32
1
910    1
Name: PKWNR, dtype: int64
1
ID: 4901043681
37545    1
37568    2
Name: PERSNR, dtype: int32
2
911    1
Name: PKWNR, dtype: int64
2
ID: 4901043683
37594    1
Name: PERSNR, dtype: int32
1
912    1
Name: PKWNR, dtype: int64
1
ID: 4901043684
37597    1
Name: PERSNR, dtype: int32
1
913    1
Name: PKWNR, dtype: int64
2
ID: 4901043692
ID: 4901043704
37747    1
Name: PERSNR, dtype: int32
1
915    1
Name: PKWNR, dtype: int64
1
ID: 4901043707
37795    1
37816    2
Name: PERSNR, dtype: int32
2
916    1
Name: PKWNR, dtype: int64
1
ID: 4901043720
37933    1
Name: PERSNR, dtype: int32
1
917    1
Name: PKWNR, dtype: int64
1
ID: 4901043724
37972    1
38007    2
Name: PERSNR, dtype: int32
2
918    1
Name: PKWNR, dtype: int64
1
ID: 4901043805
38075    1
38096    2
Name: PERSNR, dtype: int32
2
919    1
Name: PKWNR, dtype: int64
1
ID: 4901043811
38112    1
Name: PERSNR, dtype: int32
1
920    1
Name: PKWNR, dtype: int64
1
ID: 4901043820
38144    1
Name: PERSNR, dtype: int32
1
921    1
Name: PKWNR, dtype: int64
1
ID: 4901043821
38171    1
Name: PERSNR, dtype: int32
1
922    1
Name: PKWNR, dtype: int64
1
ID: 4901043839
38207    1
38241    2
Name: PERSNR, dtype: int32
2
924    1
Name: PKWNR, dtype: int64
2
ID: 4901043840
38268    1
Name: PERSNR, dtype: int32
1
925    1
Name: PKWNR, dtype: int64
1
ID: 4901043841
38295    1
38306    2
Name: PERSNR, dtype: int32
2
926    1
Name: PKWNR, dtype: int64
1
ID: 4901043842
38323    1
Name: PERSNR, dtype: int32
1
927    1
928    2
Name: PKWNR, dtype: int64
2
ID: 4901043858
38347    1
38378    2
Name: PERSNR, dtype: int32
2
929    1
Name: PKWNR, dtype: int64
2
ID: 4901043859
38409    1
Name: PERSNR, dtype: int32
1
930    1
Name: PKWNR, dtype: int64
1
ID: 4901043870
38439    1
38453    2
Name: PERSNR, dtype: int32
2
931    1
Name: PKWNR, dtype: int64
1
ID: 4901043879
38463    1
Name: PERSNR, dtype: int32
1
932    1
933    2
Name: PKWNR, dtype: int64
2
ID: 4901043898
38511    1
38536    2
38555    3
Name: PERSNR, dtype: int32
3
936    2
937    3
935    1
Name: PKWNR, dtype: int64
3
ID: 4901043909
38644    1
38680    2
Name: PERSNR, dtype: int32
2
939    1
940    2
Name: PKWNR, dtype: int64
2
ID: 4901043924
38706    1
38740    2
38773    3
Name: PERSNR, dtype: int32
3
942    2
941    1
943    3
Name: PKWNR, dtype: int64
3
ID: 4901043969
38797    1
Name: PERSNR, dtype: int32
1
944    1
Name: PKWNR, dtype: int64
1
ID: 4901043975
38816    1
Name: PERSNR, dtype: int32
1
946    2
945    1
Name: PKWNR, dtype: int64
2
ID: 4901043988
38842    1
38858    2
Name: PERSNR, dtype: int32
2
947    1
Name: PKWNR, dtype: int64
1
ID: 4901043991
38879    1
Name: PERSNR, dtype: int32
1
948    1
Name: PKWNR, dtype: int64
1
ID: 4901044006
38909    1
Name: PERSNR, dtype: int32
1
949    1
Name: PKWNR, dtype: int64
1
ID: 4901044008
38936    1
38966    3
Name: PERSNR, dtype: int32
2
951    2
950    1
952    3
Name: PKWNR, dtype: int64
3
ID: 4901044009
39013    1
39032    2
Name: PERSNR, dtype: int32
2
953    1
Name: PKWNR, dtype: int64
1
ID: 4901044014
39066    1
39085    2
Name: PERSNR, dtype: int32
2
954    1
Name: PKWNR, dtype: int64
1
ID: 4901044020
39107    1
Name: PERSNR, dtype: int32
1
955    1
Name: PKWNR, dtype: int64
1
ID: 4901044025
39174    2
Name: PERSNR, dtype: int32
1
956    1
Name: PKWNR, dtype: int64
1
ID: 4901044029
ID: 4901044073
39298    1
39325    2
Name: PERSNR, dtype: int32
2
958    1
Name: PKWNR, dtype: int64
1
ID: 4901044075
39346    1
Name: PERSNR, dtype: int32
1
959    1
Name: PKWNR, dtype: int64
1
ID: 4901044091
39375    1
Name: PERSNR, dtype: int32
1
960    1
Name: PKWNR, dtype: int64
1
ID: 4901044092
39405    1
39423    2
Name: PERSNR, dtype: int32
2
961    1
962    2
Name: PKWNR, dtype: int64
2
ID: 4901044093
39435    1
39469    3
Name: PERSNR, dtype: int32
2
963    1
964    2
Name: PKWNR, dtype: int64
3
ID: 4901044113
39541    1
39568    2
39593    3
Name: PERSNR, dtype: int32
3
966    2
965    1
Name: PKWNR, dtype: int64
2
ID: 4901044121
39660    1
39680    2
Name: PERSNR, dtype: int32
2
967    1
968    2
Name: PKWNR, dtype: int64
2
ID: 4901044127
39706    1
39737    2
Name: PERSNR, dtype: int32
2
970    2
969    1
Name: PKWNR, dtype: int64
2
ID: 4901044204
39774    1
39807    2
Name: PERSNR, dtype: int32
2
972    2
971    1
973    3
Name: PKWNR, dtype: int64
3
ID: 4901044208
ID: 4901044210
39897    1
Name: PERSNR, dtype: int32
1
974    1
Name: PKWNR, dtype: int64
1
ID: 4901044214
39919    1
Name: PERSNR, dtype: int32
1
975    1
976    2
Name: PKWNR, dtype: int64
2
ID: 4901044233
39975    1
Name: PERSNR, dtype: int32
1
977    1
Name: PKWNR, dtype: int64
1
ID: 4901044246
ID: 4901044252
40046    1
40067    2
40083    3
Name: PERSNR, dtype: int32
3
978    1
979    2
Name: PKWNR, dtype: int64
3
ID: 4901044258
40099    1
40122    2
Name: PERSNR, dtype: int32
2
981    2
980    1
Name: PKWNR, dtype: int64
2
ID: 4901044270
40145    1
Name: PERSNR, dtype: int32
1
982    1
Name: PKWNR, dtype: int64
1
ID: 4901044278
40160    1
Name: PERSNR, dtype: int32
1
984    2
985    3
983    1
Name: PKWNR, dtype: int64
3
ID: 4901044281
40266    1
40282    2
Name: PERSNR, dtype: int32
2
986    1
Name: PKWNR, dtype: int64
1
ID: 4901044286
ID: 4901044299
40404    1
Name: PERSNR, dtype: int32
1
989    2
988    1
Name: PKWNR, dtype: int64
2
ID: 4901044328
40454    1
40477    2
Name: PERSNR, dtype: int32
2
990    1
991    2
Name: PKWNR, dtype: int64
2
ID: 4901044357
40518    2
Name: PERSNR, dtype: int32
1
992    1
Name: PKWNR, dtype: int64
1
ID: 4901044362
40568    1
Name: PERSNR, dtype: int32
1
994    2
993    1
Name: PKWNR, dtype: int64
2
ID: 4901044363
ID: 4901044368
ID: 4901044375
40643    1
Name: PERSNR, dtype: int32
1
995    1
Name: PKWNR, dtype: int64
1
ID: 4901044410
40651    1
40671    2
Name: PERSNR, dtype: int32
2
996    1
Name: PKWNR, dtype: int64
1
ID: 4901044413
40694    1
40715    2
Name: PERSNR, dtype: int32
2
997    1
998    2
Name: PKWNR, dtype: int64
2
ID: 4901044415
40732    1
40750    2
Name: PERSNR, dtype: int32
2
999    1
Name: PKWNR, dtype: int64
1
ID: 4901044420
40770    1
Name: PERSNR, dtype: int32
1
1000    1
Name: PKWNR, dtype: int64
2
ID: 4901044426
40796    1
40811    2
40830    3
40854    4
Name: PERSNR, dtype: int32
4
1003    3
1001    1
1002    2
Name: PKWNR, dtype: int64
3
ID: 4901044436
40907    2
40930    3
40970    4
Name: PERSNR, dtype: int32
3
1005    2
1004    1
Name: PKWNR, dtype: int64
2
ID: 4901044520
40988    1
41015    2
Name: PERSNR, dtype: int32
2
1006    1
Name: PKWNR, dtype: int64
1
ID: 4901044561
41049    1
Name: PERSNR, dtype: int32
1
1008    1
Name: PKWNR, dtype: int64
1
ID: 4901044562
41073    1
41113    2
41151    3
Name: PERSNR, dtype: int32
3
1009    1
1010    2
Name: PKWNR, dtype: int64
2
ID: 4901044563
ID: 4901044566
41219    1
41250    2
Name: PERSNR, dtype: int32
2
1011    1
Name: PKWNR, dtype: int64
1
ID: 4901044567
41260    1
Name: PERSNR, dtype: int32
1
1012    1
Name: PKWNR, dtype: int64
1
ID: 4901044569
41310    1
Name: PERSNR, dtype: int32
1
1013    1
Name: PKWNR, dtype: int64
1
ID: 4901044574
ID: 4901044579
41352    1
Name: PERSNR, dtype: int32
1
1014    1
Name: PKWNR, dtype: int64
1
ID: 4901044584
41400    1
Name: PERSNR, dtype: int32
1
1015    1
Name: PKWNR, dtype: int64
1
ID: 4901044600
41434    1
Name: PERSNR, dtype: int32
1
1016    1
Name: PKWNR, dtype: int64
1
ID: 4901044604
41456    1
Name: PERSNR, dtype: int32
1
1017    1
Name: PKWNR, dtype: int64
1
ID: 4901044619
41494    1
41525    2
Name: PERSNR, dtype: int32
2
1019    2
1018    1
Name: PKWNR, dtype: int64
2
ID: 4901044621
ID: 4901044629
41567    1
41602    2
Name: PERSNR, dtype: int32
2
1020    1
1021    2
Name: PKWNR, dtype: int64
2
ID: 4901044658
ID: 4901044661
ID: 4901044677
41729    1
Name: PERSNR, dtype: int32
1
1022    1
Name: PKWNR, dtype: int64
2
ID: 4901044681
41754    1
41784    2
Name: PERSNR, dtype: int32
2
1023    1
Name: PKWNR, dtype: int64
1
ID: 4901044687
41816    1
Name: PERSNR, dtype: int32
1
1024    1
Name: PKWNR, dtype: int64
1
ID: 4901044689
41852    1
41869    2
Name: PERSNR, dtype: int32
2
1026    2
1025    1
Name: PKWNR, dtype: int64
2
ID: 4901044691
41897    1
Name: PERSNR, dtype: int32
1
1027    1
Name: PKWNR, dtype: int64
1
ID: 4901044693

ID: 4901044702
ID: 4901044709
42042    1
Name: PERSNR, dtype: int32
1
1028    1
Name: PKWNR, dtype: int64
2
ID: 4901044722
ID: 4901044726
42090    1
42125    2
Name: PERSNR, dtype: int32
2
1030    2
1029    1
Name: PKWNR, dtype: int64
2
ID: 4901044737
42146    1
Name: PERSNR, dtype: int32
1
1032    2
1031    1
Name: PKWNR, dtype: int64
2
ID: 4901044740
42164    1
Name: PERSNR, dtype: int32
1
1033    1
Name: PKWNR, dtype: int64
1
ID: 4901044757
42250    1
Name: PERSNR, dtype: int32
1
1034    1
Name: PKWNR, dtype: int64
1
ID: 4901044770
42264    1
Name: PERSNR, dtype: int32
1
1035    1
Name: PKWNR, dtype: int64
1
ID: 4901044771
42293    1
42346    2
Name: PERSNR, dtype: int32
2
1036    1
Name: PKWNR, dtype: int64
2
ID: 4901044783
42368    1
Name: PERSNR, dtype: int32
1
1037    1
Name: PKWNR, dtype: int64
1
ID: 4901044795
42388    1
42428    2
Name: PERSNR, dtype: int32
2
1038    1
Name: PKWNR, dtype: int64
1
ID: 4901044806
42481    1
42504    2
Name: PERSNR, dtype: int32
2
1039    1
Name: PKWNR, dtype: int64
1
ID: 4901044809
ID: 4901044815
42612    1
42637    2
Name: PERSNR, dtype: int32
2
1040    1
1041    2
Name: PKWNR, dtype: int64
2
ID: 4901044822
42655    1
42679    2
Name: PERSNR, dtype: int32
2
1042    1
Name: PKWNR, dtype: int64
2
ID: 4901044829
42747    1
42761    2
Name: PERSNR, dtype: int32
2
1043    1
Name: PKWNR, dtype: int64
2
ID: 4901044946
42781    1
Name: PERSNR, dtype: int32
1
1044    1
Name: PKWNR, dtype: int64
1
ID: 4901044953
42807    1
42825    2
42835    3
Name: PERSNR, dtype: int32
3
1045    1
1046    2
Name: PKWNR, dtype: int64
2
ID: 4901045103
42874    1
Name: PERSNR, dtype: int32
1
1047    1
Name: PKWNR, dtype: int64
1
ID: 4901045108
ID: 4901045132
ID: 4901045140
43025    1
Name: PERSNR, dtype: int32
1
1050    2
1049    1
Name: PKWNR, dtype: int64
2
ID: 4901045145
43063    1
Name: PERSNR, dtype: int32
1
1051    1
Name: PKWNR, dtype: int64
1
ID: 4901045149
43076    1
43108    2
Name: PERSNR, dtype: int32
2
1053    2
1052    1
Name: PKWNR, dtype: int64
2
ID: 4901045150
43132    1
43158    2
Name: PERSNR, dtype: int32
2
1055    2
1054    1
Name: PKWNR, dtype: int64
2
ID: 4901045169
43218    1
43236    2
Name: PERSNR, dtype: int32
2
1057    1
Name: PKWNR, dtype: int64
1
ID: 4901045189
43249    1
43277    2
43299    3
Name: PERSNR, dtype: int32
3
1060    3
1059    2
1058    1
Name: PKWNR, dtype: int64
3
ID: 4901045190
43352    1
43378    2
Name: PERSNR, dtype: int32
2
1061    1
Name: PKWNR, dtype: int64
1
ID: 4901045205
43443    1
Name: PERSNR, dtype: int32
1
1062    1
Name: PKWNR, dtype: int64
1
ID: 4901045218
43461    1
43473    2
Name: PERSNR, dtype: int32
2
1063    1
Name: PKWNR, dtype: int64
2
ID: 4901045230
43485    1
Name: PERSNR, dtype: int32
1
1064    1
Name: PKWNR, dtype: int64
1
ID: 4901045235
43506    1
43523    2
Name: PERSNR, dtype: int32
2
1066    2
1065    1
Name: PKWNR, dtype: int64
2
ID: 4901045249
43557    1
43593    2
43619    3
Name: PERSNR, dtype: int32
3
1067    1
Name: PKWNR, dtype: int64
1
ID: 4901045262
43645    1
Name: PERSNR, dtype: int32
1
1068    1
Name: PKWNR, dtype: int64
1
ID: 4901045263
ID: 4901045269
43748    2
Name: PERSNR, dtype: int32
1
1069    1
Name: PKWNR, dtype: int64
1
ID: 4901045275
43796    1
43814    2
Name: PERSNR, dtype: int32
2
1070    1
1071    2
Name: PKWNR, dtype: int64
2
ID: 4901045282
43835    1
Name: PERSNR, dtype: int32
1
1072    1
1073    2
Name: PKWNR, dtype: int64
2
ID: 4901045287
43875    1
Name: PERSNR, dtype: int32
1
1074    1
Name: PKWNR, dtype: int64
1
ID: 4901045298
43910    1
Name: PERSNR, dtype: int32
1
1075    1
Name: PKWNR, dtype: int64
1
ID: 4901045302
43924    1
43958    2
Name: PERSNR, dtype: int32
2
1078    3
1076    1
1077    2
Name: PKWNR, dtype: int64
3
ID: 4901045303
44018    1
44028    2
Name: PERSNR, dtype: int32
2
1079    1
Name: PKWNR, dtype: int64
1
ID: 4901045380
44048    1
Name: PERSNR, dtype: int32
1
1080    1
Name: PKWNR, dtype: int64
1
ID: 4901045405
44082    1
Name: PERSNR, dtype: int32
1
1081    1
Name: PKWNR, dtype: int64
1
ID: 4901045570
44111    1
44121    2
44162    3
44199    4
Name: PERSNR, dtype: int32
4
1083    2
1084    3
1082    1
Name: PKWNR, dtype: int64
3
ID: 4901045579
44230    1
44308    2
44328    5
Name: PERSNR, dtype: int32
3
1085    1
Name: PKWNR, dtype: int64
2
ID: 4901045582
ID: 4901045589
44414    1
44432    2
Name: PERSNR, dtype: int32
2
1087    2
1086    1
Name: PKWNR, dtype: int64
2
ID: 4901045595
ID: 4901045596
ID: 4901045603
ID: 4901045609
44661    1
Name: PERSNR, dtype: int32
1
1088    1
Name: PKWNR, dtype: int64
1
ID: 4901045622
44701    1
44739    2
Name: PERSNR, dtype: int32
2
1089    1
Name: PKWNR, dtype: int64
1
ID: 4901045627
44756    1
44768    2
Name: PERSNR, dtype: int32
2
1090    1
Name: PKWNR, dtype: int64
1
ID: 4901045638
44791    1
44857    2
Name: PERSNR, dtype: int32
2
1092    2
1091    1
Name: PKWNR, dtype: int64
2
ID: 4901045662
45016    1
Name: PERSNR, dtype: int32
1
1093    1
Name: PKWNR, dtype: int64
2
ID: 4901045692
45047    1
45063    2
45077    3
Name: PERSNR, dtype: int32
3
1095    2
1094    1
Name: PKWNR, dtype: int64
3
ID: 4901045695
ID: 4901045713
45144    1
Name: PERSNR, dtype: int32
1
1096    1
Name: PKWNR, dtype: int64
1
ID: 4901045718
ID: 4901045722
ID: 4901045733
ID: 4901045736
45271    1
45277    2
Name: PERSNR, dtype: int32
2
1097    1
Name: PKWNR, dtype: int64
1
ID: 4901045774
45305    1
Name: PERSNR, dtype: int32
1
1098    1
Name: PKWNR, dtype: int64
1
ID: 4901045846
45336    1
45348    2
45365    3
45381    4
Name: PERSNR, dtype: int32
4
1099    1
Name: PKWNR, dtype: int64
3
ID: 4901045853
45402    1
Name: PERSNR, dtype: int32
1
1100    1
Name: PKWNR, dtype: int64
1
ID: 4901045871
45451    2
Name: PERSNR, dtype: int32
1
1101    1
Name: PKWNR, dtype: int64
1
ID: 4901045896
ID: 4901045926
45524    1
45557    2
Name: PERSNR, dtype: int32
2
1102    1
1104    3
1103    2
Name: PKWNR, dtype: int64
3
ID: 4901045927
45579    1
45612    2
Name: PERSNR, dtype: int32
2
1105    1
1106    2
Name: PKWNR, dtype: int64
2
ID: 4901045937
45661    1
45681    2
Name: PERSNR, dtype: int32
2
1108    2
1107    1
Name: PKWNR, dtype: int64
3
ID: 4901045955
45756    1
45785    3
45818    4
Name: PERSNR, dtype: int32
3
1109    1
1111    3
1110    2
Name: PKWNR, dtype: int64
3
ID: 4901045962
45867    2
Name: PERSNR, dtype: int32
1
1112    1
Name: PKWNR, dtype: int64
1
ID: 4901045966
45931    1
Name: PERSNR, dtype: int32
1
1113    1
Name: PKWNR, dtype: int64
1
ID: 4901045978
45962    1
Name: PERSNR, dtype: int32
1
1114    1
Name: PKWNR, dtype: int64
2
ID: 4901045984
45993    1
Name: PERSNR, dtype: int32
1
1115    1
Name: PKWNR, dtype: int64
1
ID: 4901045985
46034    1
46071    2
Name: PERSNR, dtype: int32
2
1116    1
1117    2
Name: PKWNR, dtype: int64
2
ID: 4901046004
46151    1
46160    2
46187    3
Name: PERSNR, dtype: int32
3
1118    1
1119    2
Name: PKWNR, dtype: int64
2
ID: 4901046021
ID: 4901046070
46361    1
46381    2
Name: PERSNR, dtype: int32
2
1121    2
1120    1
Name: PKWNR, dtype: int64
2
ID: 4901046077
ID: 4901046252
46455    1
46475    2
Name: PERSNR, dtype: int32
2
1122    1
1123    2
Name: PKWNR, dtype: int64
2
ID: 4901046270
46523    1
46546    2
Name: PERSNR, dtype: int32
2
1125    2
1124    1
Name: PKWNR, dtype: int64
2
ID: 4901046279
ID: 4901046282
46647    1
46661    2
46681    3
Name: PERSNR, dtype: int32
3
1127    2
1126    1
1128    3
Name: PKWNR, dtype: int64
3
ID: 4901046319
46748    1
46766    2
Name: PERSNR, dtype: int32
2
1129    1
1130    2
Name: PKWNR, dtype: int64
2
ID: 4911040015
46830    1
46856    2
Name: PERSNR, dtype: int32
2
1131    1
Name: PKWNR, dtype: int64
1
ID: 4911040018
46880    1
Name: PERSNR, dtype: int32
1
1132    1
Name: PKWNR, dtype: int64
1
ID: 4911040039
46902    1
46911    2
Name: PERSNR, dtype: int32
2
1133    1
1134    2
Name: PKWNR, dtype: int64
2
ID: 4911040064
46934    1
46955    2
Name: PERSNR, dtype: int32
2
1136    2
1135    1
Name: PKWNR, dtype: int64
2
ID: 4911040075
ID: 4911040087
ID: 4911040107
47020    1
47036    2
Name: PERSNR, dtype: int32
2
1138    2
1137    1
Name: PKWNR, dtype: int64
2
ID: 4911040115
47071    1
47096    2
Name: PERSNR, dtype: int32
2
1139    1
1140    2
Name: PKWNR, dtype: int64
2
ID: 4911040126
47119    1
Name: PERSNR, dtype: int32
1
1141    1
Name: PKWNR, dtype: int64
1
ID: 4911040136
ID: 4911040152
47231    1
47251    2
Name: PERSNR, dtype: int32
2
1143    2
1144    3
1142    1
Name: PKWNR, dtype: int64
3
ID: 4911040183
ID: 4911040185
47313    1
47348    2
Name: PERSNR, dtype: int32
2
1145    1
1146    2
Name: PKWNR, dtype: int64
2
ID: 4911040202
47382    1
47409    2
Name: PERSNR, dtype: int32
2
1147    1
1148    2
Name: PKWNR, dtype: int64
2
ID: 4911040218
47450    1
47479    2
Name: PERSNR, dtype: int32
2
1150    2
1149    1
Name: PKWNR, dtype: int64
2
ID: 4911040235
47503    1
Name: PERSNR, dtype: int32
1
1151    1
Name: PKWNR, dtype: int64
2
ID: 4911040257
47520    1
47546    4
Name: PERSNR, dtype: int32
2
1152    1
1154    3
1153    2
Name: PKWNR, dtype: int64
3
ID: 4911040288
ID: 4911040296
47593    1
47608    2
Name: PERSNR, dtype: int32
2
1156    2
1155    1
Name: PKWNR, dtype: int64
2
ID: 4911040306
47626    1
Name: PERSNR, dtype: int32
1
1157    1
Name: PKWNR, dtype: int64
1
ID: 4911040321
ID: 4911040350
47680    1
47699    2
Name: PERSNR, dtype: int32
2
1159    2
1158    1
Name: PKWNR, dtype: int64
2
ID: 4911040364
47716    1
47742    2
47768    3
Name: PERSNR, dtype: int32
3
1162    3
1160    1
1161    2
Name: PKWNR, dtype: int64
3
ID: 4911040368
47834    2
Name: PERSNR, dtype: int32
1
1163    1
Name: PKWNR, dtype: int64
1
ID: 4911040373
ID: 4911040374
ID: 4911040391
ID: 4911040396
ID: 4911040406
48030    1
Name: PERSNR, dtype: int32
1
1164    1
Name: PKWNR, dtype: int64
3
ID: 4911040418
48065    1
48086    2
Name: PERSNR, dtype: int32
2
1165    1
1166    2
Name: PKWNR, dtype: int64
2
ID: 4911040420
ID: 4911040452
ID: 4911040508
ID: 4911040512
48276    1
48292    2
Name: PERSNR, dtype: int32
2
1167    1
1168    2
Name: PKWNR, dtype: int64
2
ID: 4911040515
ID: 4911040516
ID: 4911040531
48380    1
48399    2
Name: PERSNR, dtype: int32
2
1169    1
Name: PKWNR, dtype: int64
1
ID: 4911040545
48423    1
48457    2
Name: PERSNR, dtype: int32
2
1170    1
Name: PKWNR, dtype: int64
1
ID: 4911040571
48469    1
Name: PERSNR, dtype: int32
1
1171    1
Name: PKWNR, dtype: int64
1
ID: 4911040574
48572    1
48597    2
Name: PERSNR, dtype: int32
2
1172    1
1173    2
Name: PKWNR, dtype: int64
2
ID: 4911040575
48621    1
48653    2
Name: PERSNR, dtype: int32
2
1174    1
Name: PKWNR, dtype: int64
1
ID: 4911040589
ID: 4911040594
ID: 4911040612
48845    1
Name: PERSNR, dtype: int32
1
1175    1
Name: PKWNR, dtype: int64
1
ID: 4911040650
48867    1
48886    2
Name: PERSNR, dtype: int32
2
1177    2
1176    1
Name: PKWNR, dtype: int64
2
ID: 4911040654
48952    1
48997    3
Name: PERSNR, dtype: int32
2
1178    1
Name: PKWNR, dtype: int64
1
ID: 4911040659
49028    1
Name: PERSNR, dtype: int32
1
1179    1
Name: PKWNR, dtype: int64
1
ID: 4911040663
49051    1
49064    2
Name: PERSNR, dtype: int32
2
1180    1
Name: PKWNR, dtype: int64
1
ID: 4911040677
49089    1
49116    2
Name: PERSNR, dtype: int32
2
1181    1
Name: PKWNR, dtype: int64
4
ID: 4911040691
49139    1
49164    2
Name: PERSNR, dtype: int32
2
1182    1
Name: PKWNR, dtype: int64
1
ID: 4911040697

49210    1
Name: PERSNR, dtype: int32
1
1183    1
Name: PKWNR, dtype: int64
1
ID: 4911040703
49235    1
49253    2
Name: PERSNR, dtype: int32
2
1184    1
Name: PKWNR, dtype: int64
1
ID: 4911040713
49268    1
Name: PERSNR, dtype: int32
1
1185    1
Name: PKWNR, dtype: int64
1
ID: 4911040735
ID: 4911040745
49300    1
Name: PERSNR, dtype: int32
1
1186    1
Name: PKWNR, dtype: int64
2
ID: 4911040772
49321    1
49348    2
Name: PERSNR, dtype: int32
2
1187    1
Name: PKWNR, dtype: int64
1
ID: 4911040804
49369    1
Name: PERSNR, dtype: int32
1
1188    1
Name: PKWNR, dtype: int64
1
ID: 4911040806
49379    1
49395    2
Name: PERSNR, dtype: int32
2
1189    1
1190    2
Name: PKWNR, dtype: int64
2
ID: 4911040890
ID: 4911040929
49468    1
Name: PERSNR, dtype: int32
1
1192    2
1191    1
Name: PKWNR, dtype: int64
2
ID: 4911040957
49494    1
Name: PERSNR, dtype: int32
1
1193    1
Name: PKWNR, dtype: int64
2
ID: 4911040959
49516    1
49546    3
Name: PERSNR, dtype: int32
2
1194    1
Name: PKWNR, dtype: int64
2
ID: 4911040985
ID: 4911041003
49623    1
Name: PERSNR, dtype: int32
1
1195    1
Name: PKWNR, dtype: int64
1
ID: 4911041012
49671    1
49684    2
Name: PERSNR, dtype: int32
2
1197    2
1196    1
Name: PKWNR, dtype: int64
2
ID: 4911041058
49751    1
Name: PERSNR, dtype: int32
1
1198    1
Name: PKWNR, dtype: int64
1
ID: 4911041074
49795    1
Name: PERSNR, dtype: int32
1
1199    1
Name: PKWNR, dtype: int64
1
ID: 4911041099
ID: 4911041145
49897    1
Name: PERSNR, dtype: int32
1
1200    1
Name: PKWNR, dtype: int64
1
ID: 4911041165
ID: 4911041177
49977    1
Name: PERSNR, dtype: int32
1
1201    1
Name: PKWNR, dtype: int64
1
ID: 4911041190
49995    1
50038    2
Name: PERSNR, dtype: int32
2
1202    1
1203    2
Name: PKWNR, dtype: int64
2
ID: 4911041195
50061    1
Name: PERSNR, dtype: int32
1
1204    1
Name: PKWNR, dtype: int64
4
ID: 4911041198
50094    1
Name: PERSNR, dtype: int32
1
1205    1
Name: PKWNR, dtype: int64
1
ID: 4911041201
50151    1
Name: PERSNR, dtype: int32
1
1206    1
Name: PKWNR, dtype: int64
1
ID: 4911041218
50208    1
50228    2
Name: PERSNR, dtype: int32
2
1208    2
1207    1
1209    3
Name: PKWNR, dtype: int64
3
ID: 4911041227
50279    1
Name: PERSNR, dtype: int32
1
1210    1
Name: PKWNR, dtype: int64
1
ID: 4911041234
50299    1
Name: PERSNR, dtype: int32
1
1211    1
Name: PKWNR, dtype: int64
1
ID: 4911041238
50336    1
Name: PERSNR, dtype: int32
1
1212    1
Name: PKWNR, dtype: int64
1
ID: 4911041248
50351    1
Name: PERSNR, dtype: int32
1
1213    1
Name: PKWNR, dtype: int64
1
ID: 4911041284
50385    1
50410    2
Name: PERSNR, dtype: int32
2
1214    1
Name: PKWNR, dtype: int64
1
ID: 4911041294
50443    1
Name: PERSNR, dtype: int32
1
1215    1
Name: PKWNR, dtype: int64
1
ID: 4911041306
50447    1
50497    2
Name: PERSNR, dtype: int32
2
1217    2
1216    1
Name: PKWNR, dtype: int64
1
ID: 4911041326
50520    1
50545    2
50591    3
Name: PERSNR, dtype: int32
3
1218    1
Name: PKWNR, dtype: int64
1
ID: 4911041343
50682    1
50716    2
Name: PERSNR, dtype: int32
2
1220    2
1219    1
Name: PKWNR, dtype: int64
2
ID: 4911041354
50757    1
50786    2
Name: PERSNR, dtype: int32
2
1222    2
1221    1
Name: PKWNR, dtype: int64
2
ID: 4911041362
50812    1
50826    2
Name: PERSNR, dtype: int32
2
1223    1
1224    2
Name: PKWNR, dtype: int64
2
ID: 4911041363
ID: 4911041366
50863    1
Name: PERSNR, dtype: int32
1
1225    1
Name: PKWNR, dtype: int64
2
ID: 4911041368
ID: 4911041369
50899    1
Name: PERSNR, dtype: int32
1
1226    1
Name: PKWNR, dtype: int64
1
ID: 4911041379
50917    1
50949    2
50965    3
Name: PERSNR, dtype: int32
3
1229    3
1227    1
1228    2
Name: PKWNR, dtype: int64
3
ID: 4911041410
50986    1
Name: PERSNR, dtype: int32
1
1230    1
Name: PKWNR, dtype: int64
1
ID: 4911041414
51025    1
Name: PERSNR, dtype: int32
1
1231    1
Name: PKWNR, dtype: int64
1
ID: 4911041418
51055    2
Name: PERSNR, dtype: int32
1
1232    1
1233    2
Name: PKWNR, dtype: int64
2
ID: 4911041420
ID: 4911041468
ID: 4911041469
51119    1
51138    2
Name: PERSNR, dtype: int32
2
1235    2
1234    1
Name: PKWNR, dtype: int64
2
ID: 4911041471
51230    2
Name: PERSNR, dtype: int32
1
1236    1
Name: PKWNR, dtype: int64
1
ID: 4911041474
51240    1
51254    2
Name: PERSNR, dtype: int32
2
1237    1
Name: PKWNR, dtype: int64
1
ID: 4911041489
51269    1
Name: PERSNR, dtype: int32
1
1238    1
Name: PKWNR, dtype: int64
1
ID: 4911041510
51303    1
Name: PERSNR, dtype: int32
1
1239    1
Name: PKWNR, dtype: int64
1
ID: 4911041511
51325    1
51354    2
51381    3
Name: PERSNR, dtype: int32
3
1240    1
1241    2
Name: PKWNR, dtype: int64
2
ID: 4911041550
51410    1
51429    2
Name: PERSNR, dtype: int32
2
1242    1
Name: PKWNR, dtype: int64
1
ID: 4911041560
51445    1
Name: PERSNR, dtype: int32
1
1243    1
Name: PKWNR, dtype: int64
1
ID: 4911041581
51472    1
Name: PERSNR, dtype: int32
1
1244    1
Name: PKWNR, dtype: int64
1
ID: 4911041586
51485    1
51515    2
Name: PERSNR, dtype: int32
2
1246    2
1245    1
Name: PKWNR, dtype: int64
2
ID: 4911041587
ID: 4911041589
51560    1
51571    2
Name: PERSNR, dtype: int32
2
1247    1
1248    2
Name: PKWNR, dtype: int64
3
ID: 4911041591
51585    1
Name: PERSNR, dtype: int32
1
1249    1
Name: PKWNR, dtype: int64
1
ID: 4911041599
51634    1
51639    2
Name: PERSNR, dtype: int32
2
1250    1
Name: PKWNR, dtype: int64
2
ID: 4911041601
51674    1
51701    2
Name: PERSNR, dtype: int32
2
1252    2
1251    1
Name: PKWNR, dtype: int64
2
ID: 4911041626
51767    1
Name: PERSNR, dtype: int32
1
1255    2
1256    3
1254    1
Name: PKWNR, dtype: int64
3
ID: 4911041630
51800    1
51826    2
Name: PERSNR, dtype: int32
2
1258    2
1257    1
Name: PKWNR, dtype: int64
2
ID: 4911041659
ID: 4911041668
51901    1
51913    2
Name: PERSNR, dtype: int32
2
1259    1
1260    2
Name: PKWNR, dtype: int64
2
ID: 4911041670
51923    1
51957    2
Name: PERSNR, dtype: int32
2
1261    1
1262    2
Name: PKWNR, dtype: int64
2
ID: 4911041676
ID: 4911041684
52025    1
Name: PERSNR, dtype: int32
1
1264    2
1263    1
Name: PKWNR, dtype: int64
2
ID: 4911041701
ID: 4911041727
ID: 4911041733
52264    1
Name: PERSNR, dtype: int32
1
1265    1
Name: PKWNR, dtype: int64
1
ID: 4911041768
52284    2
Name: PERSNR, dtype: int32
1
1266    1
Name: PKWNR, dtype: int64
1
ID: 4911041769
52296    1
Name: PERSNR, dtype: int32
1
1267    1
Name: PKWNR, dtype: int64
1
ID: 4911041794
52331    1
Name: PERSNR, dtype: int32
1
1268    1
Name: PKWNR, dtype: int64
4
ID: 4911041807
52345    1
52369    2
Name: PERSNR, dtype: int32
2
1269    1
Name: PKWNR, dtype: int64
1
ID: 4911041811
52399    1
52423    2
Name: PERSNR, dtype: int32
2
1270    1
Name: PKWNR, dtype: int64
1
ID: 4911041829
ID: 4911041846
52553    1
Name: PERSNR, dtype: int32
1
1271    1
Name: PKWNR, dtype: int64
1
ID: 4911041860
ID: 4911041886
52592    1
Name: PERSNR, dtype: int32
1
1272    1
Name: PKWNR, dtype: int64
1
ID: 4911041921
52616    1
52652    2
Name: PERSNR, dtype: int32
2
1273    1
Name: PKWNR, dtype: int64
1
ID: 4911041938
52747    1
52774    2
Name: PERSNR, dtype: int32
2
1274    1
1275    2
Name: PKWNR, dtype: int64
2
ID: 4911041941
ID: 4911041944
ID: 4911041961
52972    1
Name: PERSNR, dtype: int32
1
1276    1
Name: PKWNR, dtype: int64
1
ID: 4911041969
53001    1
53030    2
Name: PERSNR, dtype: int32
2
1278    2
1277    1
Name: PKWNR, dtype: int64
2
ID: 4911041993
ID: 4911041994
53107    1
53140    2
Name: PERSNR, dtype: int32
2
1279    1
1280    2
Name: PKWNR, dtype: int64
2
ID: 4911042001
ID: 4911042054
53244    1
Name: PERSNR, dtype: int32
1
1281    1
Name: PKWNR, dtype: int64
1
ID: 4911042062
ID: 4911042065
53310    1
53338    2
Name: PERSNR, dtype: int32
2
1282    1
Name: PKWNR, dtype: int64
2
ID: 4911042073
ID: 4911042111
53525    1
53547    2
53581    3
Name: PERSNR, dtype: int32
3
1283    1
1284    2
Name: PKWNR, dtype: int64
2
ID: 4911042124
53614    1
Name: PERSNR, dtype: int32
1
1285    1
Name: PKWNR, dtype: int64
1
ID: 4911042125
53642    1
Name: PERSNR, dtype: int32
1
1286    1
Name: PKWNR, dtype: int64
1
ID: 4911042126
53661    1
Name: PERSNR, dtype: int32
1
1287    1
Name: PKWNR, dtype: int64
1
ID: 4911042127
ID: 4911042137
53735    1
53757    2
Name: PERSNR, dtype: int32
2
1288    1
Name: PKWNR, dtype: int64
1
ID: 4911042139
53778    1
Name: PERSNR, dtype: int32
1
1289    1
Name: PKWNR, dtype: int64
1
ID: 4911042146
53805    1
Name: PERSNR, dtype: int32
1
1290    1
Name: PKWNR, dtype: int64
1
ID: 4911042179
ID: 4911042222
53900    1
Name: PERSNR, dtype: int32
1
1292    1
Name: PKWNR, dtype: int64
1
ID: 4911042241
53952    1
53986    2
54023    3
Name: PERSNR, dtype: int32
3
1293    1
1294    2
Name: PKWNR, dtype: int64
3
ID: 4911042255
54063    1
54083    2
Name: PERSNR, dtype: int32
2
1296    2
1295    1
Name: PKWNR, dtype: int64
2
ID: 4911042261
54108    1
54137    2
Name: PERSNR, dtype: int32
2
1298    2
1299    3
1297    1
Name: PKWNR, dtype: int64
3
ID: 4911042274
54203    1
54223    2
Name: PERSNR, dtype: int32
2
1300    1
1301    2
Name: PKWNR, dtype: int64
2
ID: 4911042287
54252    1
54270    2
Name: PERSNR, dtype: int32
2
1303    2
1302    1
Name: PKWNR, dtype: int64
2
ID: 4911042295
54286    1
Name: PERSNR, dtype: int32
1
1305    2
1304    1
Name: PKWNR, dtype: int64
2
ID: 4911042309
ID: 4911042315
54503    1
Name: PERSNR, dtype: int32
1
1306    1
Name: PKWNR, dtype: int64
2
ID: 4911042329
54545    1
Name: PERSNR, dtype: int32
1
1307    1
Name: PKWNR, dtype: int64
1
ID: 4911042330
ID: 4911042339
ID: 4911042349
54682    1
Name: PERSNR, dtype: int32
1
1308    1
Name: PKWNR, dtype: int64
1
ID: 4911042364
54694    1
Name: PERSNR, dtype: int32
1
1309    1
Name: PKWNR, dtype: int64
2
ID: 4911042372
54724    1
Name: PERSNR, dtype: int32
1
1310    1
Name: PKWNR, dtype: int64
1
ID: 4911042375
ID: 4911042376
54834    1
54867    2
Name: PERSNR, dtype: int32
2
1311    1
1312    2
Name: PKWNR, dtype: int64
3
ID: 4911042378
54886    1
54901    2
Name: PERSNR, dtype: int32
2
1313    1
1314    2
Name: PKWNR, dtype: int64
2
ID: 4911042412
54949    1
Name: PERSNR, dtype: int32
1
1316    1
Name: PKWNR, dtype: int64
1
ID: 4911042413
54970    1
55019    2
Name: PERSNR, dtype: int32
2
1317    1
1318    2
Name: PKWNR, dtype: int64
2
ID: 4911042427
ID: 4911044964
55148    1
Name: PERSNR, dtype: int32
1
1319    1
Name: PKWNR, dtype: int64
2
ID: 4911044979
55182    1
Name: PERSNR, dtype: int32
1
1320    1
Name: PKWNR, dtype: int64
1
ID: 4911044999
55203    1
Name: PERSNR, dtype: int32
1
1322    2
1321    1
Name: PKWNR, dtype: int64
2
ID: 4911045015
ID: 4911045025
ID: 4911045035
55292    1
55315    2
Name: PERSNR, dtype: int32
2
1323    1
1324    2
Name: PKWNR, dtype: int64
2
ID: 4911045069
55375    1
55394    2
Name: PERSNR, dtype: int32
2
1326    2
1325    1
Name: PKWNR, dtype: int64
2
ID: 4911045423
55452    1
55454    2
55473    3
55489    5
Name: PERSNR, dtype: int32
4
1329    3
1328    2
1327    1
1330    4
Name: PKWNR, dtype: int64
4
ID: 4911045442
ID: 4911045483
55575    1
Name: PERSNR, dtype: int32
1
1331    1
Name: PKWNR, dtype: int64
1
ID: 4911045505

ID: 4911045543
ID: 4911046137
55672    1
Name: PERSNR, dtype: int32
1
1332    1
Name: PKWNR, dtype: int64
1
ID: 4911046157
55705    1
Name: PERSNR, dtype: int32
1
1333    1
Name: PKWNR, dtype: int64
1
ID: 4911046196
ID: 4911046197
55759    1
Name: PERSNR, dtype: int32
1
1334    1
Name: PKWNR, dtype: int64
4
ID: 4911046205
ID: 8501022404
55933    1
Name: PERSNR, dtype: int32
1
1335    1
Name: PKWNR, dtype: int64
1
ID: 8501022424
ID: 8501022429
55956    1
Name: PERSNR, dtype: int32
1
1336    1
Name: PKWNR, dtype: int64
1
ID: 8501022459
ID: 8501022462
56009    1
56040    2
Name: PERSNR, dtype: int32
2
1338    1
Name: PKWNR, dtype: int64
1
ID: 8501022681
56116    1
56135    2
56164    3
Name: PERSNR, dtype: int32
3
1339    1
Name: PKWNR, dtype: int64
2
ID: 8501022685
ID: 8501022692
56226    1
Name: PERSNR, dtype: int32
1
1340    1
Name: PKWNR, dtype: int64
1
ID: 8501022697
56249    1
Name: PERSNR, dtype: int32
1
1341    1
Name: PKWNR, dtype: int64
1
ID: 8501022925
56293    1
56308    2
Name: PERSNR, dtype: int32
2
1342    1
Name: PKWNR, dtype: int64
1
ID: 8501022936
56330    1
Name: PERSNR, dtype: int32
1
1343    1
Name: PKWNR, dtype: int64
1
ID: 8501022940
ID: 8501022945
56360    1
Name: PERSNR, dtype: int32
1
1344    1
Name: PKWNR, dtype: int64
1
ID: 8501022966
56425    1
Name: PERSNR, dtype: int32
1
1345    1
Name: PKWNR, dtype: int64
3
ID: 8501023247
56543    1
56566    2
Name: PERSNR, dtype: int32
2
1346    1
1347    2
Name: PKWNR, dtype: int64
2
ID: 8501023251
56579    1
Name: PERSNR, dtype: int32
1
1348    1
Name: PKWNR, dtype: int64
1
ID: 8501023255
56610    1
Name: PERSNR, dtype: int32
1
1349    1
Name: PKWNR, dtype: int64
1
ID: 8501023266
56718    1
Name: PERSNR, dtype: int32
1
1350    1
Name: PKWNR, dtype: int64
2
ID: 8501023408
56747    1
Name: PERSNR, dtype: int32
1
1351    1
Name: PKWNR, dtype: int64
1
ID: 8501023412
56774    1
56790    2
Name: PERSNR, dtype: int32
2
1352    2
1353    1
Name: PKWNR, dtype: int64
2
ID: 8501023414
56811    1
Name: PERSNR, dtype: int32
1
1354    1
Name: PKWNR, dtype: int64
1
ID: 8501023595
56844    1
56880    2
Name: PERSNR, dtype: int32
2
1356    2
1355    1
Name: PKWNR, dtype: int64
2
ID: 8501023684
56928    1
56952    2
Name: PERSNR, dtype: int32
2
1357    1
1358    2
Name: PKWNR, dtype: int64
2
ID: 8501023937
57047    1
57071    2
Name: PERSNR, dtype: int32
2
1359    1
Name: PKWNR, dtype: int64
1
ID: 8501024264
57090    1
Name: PERSNR, dtype: int32
1
1360    1
Name: PKWNR, dtype: int64
1
ID: 8501024269
57111    1
57121    2
57138    3
Name: PERSNR, dtype: int32
3
1361    1
1362    2
Name: PKWNR, dtype: int64
2
ID: 8501024289
57172    2
Name: PERSNR, dtype: int32
1
1363    1
Name: PKWNR, dtype: int64
1
ID: 8501024345
ID: 8501024352
57212    1
Name: PERSNR, dtype: int32
1
1364    1
Name: PKWNR, dtype: int64
1
ID: 8501024563
ID: 8501024570
ID: 8501024590
57347    1
Name: PERSNR, dtype: int32
1
1365    1
Name: PKWNR, dtype: int64
1
ID: 8501024802
57396    1
Name: PERSNR, dtype: int32
1
1366    1
Name: PKWNR, dtype: int64
1
ID: 8501024820
ID: 8501024973
ID: 8501025175
57571    1
Name: PERSNR, dtype: int32
1
1367    1
Name: PKWNR, dtype: int64
1
ID: 8501025277
57609    1
57635    2
Name: PERSNR, dtype: int32
2
1368    1
1369    2
Name: PKWNR, dtype: int64
2
ID: 8501025784
57657    1
Name: PERSNR, dtype: int32
1
1370    1
Name: PKWNR, dtype: int64
1
ID: 8501025829
57661    1
57675    2
Name: PERSNR, dtype: int32
2
1372    2
1371    1
Name: PKWNR, dtype: int64
2
ID: 8501026108
57694    1
Name: PERSNR, dtype: int32
1
1373    1
Name: PKWNR, dtype: int64
1
ID: 8501026129
57739    1
57815    3
57842    4
Name: PERSNR, dtype: int32
3
1377    4
1375    3
1374    1
1376    2
Name: PKWNR, dtype: int64
3
ID: 8501026660
ID: 8501026678
57985    1
58003    2
Name: PERSNR, dtype: int32
2
1379    1
1380    2
Name: PKWNR, dtype: int64
2
ID: 8511020115
58013    1
58040    2
Name: PERSNR, dtype: int32
2
1381    1
1382    2
Name: PKWNR, dtype: int64
2
ID: 8511020168
ID: 8511020185
ID: 8511020227
58154    1
Name: PERSNR, dtype: int32
1
1383    1
Name: PKWNR, dtype: int64
1
ID: 8511020318
58219    2
Name: PERSNR, dtype: int32
1
1384    1
Name: PKWNR, dtype: int64
1
ID: 8511020351
58254    1
Name: PERSNR, dtype: int32
1
1385    1
Name: PKWNR, dtype: int64
2
ID: 8511020642
58327    1
58345    2
58380    3
58393    4
Name: PERSNR, dtype: int32
4
1389    3
1388    2
1387    1
Name: PKWNR, dtype: int64
3
ID: 8511020672
58416    1
58444    2
Name: PERSNR, dtype: int32
2
1390    1
Name: PKWNR, dtype: int64
2
ID: 8511020710
58505    2
Name: PERSNR, dtype: int32
1
1392    2
1391    1
Name: PKWNR, dtype: int64
2
ID: 8511020745
58530    1
Name: PERSNR, dtype: int32
1
1393    2
1394    1
Name: PKWNR, dtype: int64
2
ID: 8511020876
58547    1
Name: PERSNR, dtype: int32
1
1396    1
1395    2
Name: PKWNR, dtype: int64
2
ID: 8511020905
58635    2
Name: PERSNR, dtype: int32
1
1397    1
Name: PKWNR, dtype: int64
1
ID: 8511020968
58668    1
Name: PERSNR, dtype: int32
1
1398    1
Name: PKWNR, dtype: int64
2
ID: 8511020977
ID: 8511021009
58741    1
Name: PERSNR, dtype: int32
1
1399    1
Name: PKWNR, dtype: int64
2
ID: 8511021155
ID: 8511021253
58806    1
Name: PERSNR, dtype: int32
1
1400    1
Name: PKWNR, dtype: int64
1
ID: 8511021317
58856    1
58877    2
Name: PERSNR, dtype: int32
2
1401    1
Name: PKWNR, dtype: int64
1
ID: 8511021339
ID: 8511021342
ID: 8511021423
59024    1
Name: PERSNR, dtype: int32
1
1402    1
Name: PKWNR, dtype: int64
1
ID: 8511021447
59102    1
Name: PERSNR, dtype: int32
1
1403    1
Name: PKWNR, dtype: int64
1
ID: 8511021691
59153    1
Name: PERSNR, dtype: int32
1
1405    1
1404    2
Name: PKWNR, dtype: int64
2
ID: 8511021758
59178    1
Name: PERSNR, dtype: int32
1
1406    1
Name: PKWNR, dtype: int64
1
ID: 8511021768
ID: 8511021806
59249    2
Name: PERSNR, dtype: int32
1
1407    1
Name: PKWNR, dtype: int64
1
ID: 8511021922
59349    1
59377    2
Name: PERSNR, dtype: int32
2
1408    1
Name: PKWNR, dtype: int64
2
ID: 8511021925
59403    1
59419    2
Name: PERSNR, dtype: int32
2
1409    1
Name: PKWNR, dtype: int64
1
ID: 8511022037
59481    2
Name: PERSNR, dtype: int32
1
1410    1
Name: PKWNR, dtype: int64
1
ID: 8511022043
59496    1
59530    2
Name: PERSNR, dtype: int32
2
1411    1
Name: PKWNR, dtype: int64
1
ID: 8511022088
59560    2
Name: PERSNR, dtype: int32
1
1412    1
Name: PKWNR, dtype: int64
1
ID: 8511022102
59576    1
59613    2
Name: PERSNR, dtype: int32
2
1413    1
Name: PKWNR, dtype: int64
1
ID: 8701032451
ID: 8701032463
59728    1
Name: PERSNR, dtype: int32
1
1415    1
Name: PKWNR, dtype: int64
2
ID: 8701032465
59768    1
59785    2
Name: PERSNR, dtype: int32
2
1416    1
Name: PKWNR, dtype: int64
2
ID: 8701032466
59855    1
Name: PERSNR, dtype: int32
1
1417    1
Name: PKWNR, dtype: int64
1
ID: 8701032476
59944    1
59974    2
Name: PERSNR, dtype: int32
2
1419    2
1418    1
Name: PKWNR, dtype: int64
2
ID: 8701032501
60021    1
60040    2
Name: PERSNR, dtype: int32
2
1420    1
Name: PKWNR, dtype: int64
1
ID: 8701032770
60103    2
Name: PERSNR, dtype: int32
1
1422    2
1421    1
Name: PKWNR, dtype: int64
2
ID: 8701032772
ID: 8701032773
60183    1
60197    2
Name: PERSNR, dtype: int32
2
1423    1
Name: PKWNR, dtype: int64
1
ID: 8701032774
ID: 8701032786
60241    1
Name: PERSNR, dtype: int32
1
1424    1
Name: PKWNR, dtype: int64
1
ID: 8701032790
60297    2
Name: PERSNR, dtype: int32
1
1425    1
Name: PKWNR, dtype: int64
1
ID: 8701033145
ID: 8701033161
60430    1
Name: PERSNR, dtype: int32
1
1426    1
Name: PKWNR, dtype: int64
1
ID: 8701033173
60444    1
Name: PERSNR, dtype: int32
1
1427    1
Name: PKWNR, dtype: int64
1
ID: 8701033177
60479    1
60501    2
Name: PERSNR, dtype: int32
2
1429    2
1428    1
Name: PKWNR, dtype: int64
2
ID: 8701033187
60519    1
60553    2
Name: PERSNR, dtype: int32
2
1430    1
Name: PKWNR, dtype: int64
1
ID: 8701033188
ID: 8701033195
60585    1
Name: PERSNR, dtype: int32
1
1431    1
Name: PKWNR, dtype: int64
1
ID: 8701033223
60638    1
60664    2
Name: PERSNR, dtype: int32
2
1432    1
1433    2
Name: PKWNR, dtype: int64
2
ID: 8701033225
60697    1
Name: PERSNR, dtype: int32
1
1434    1
Name: PKWNR, dtype: int64
1
ID: 8701033226
60714    1
60742    2
Name: PERSNR, dtype: int32
2
1435    2
1436    1
Name: PKWNR, dtype: int64
2
ID: 8701033229
60796    1
60827    2
Name: PERSNR, dtype: int32
2
1437    1
Name: PKWNR, dtype: int64
1
ID: 8701033354
60878    1
60906    2
60933    3
Name: PERSNR, dtype: int32
3
1438    1
1439    2
Name: PKWNR, dtype: int64
2
ID: 8701033355
60953    1
Name: PERSNR, dtype: int32
1
1440    1
Name: PKWNR, dtype: int64
2
ID: 8701033368
60969    1
Name: PERSNR, dtype: int32
1
1441    1
Name: PKWNR, dtype: int64
1
ID: 8701033373
61020    1
61049    2
Name: PERSNR, dtype: int32
2
1442    1
1443    2
Name: PKWNR, dtype: int64
2
ID: 8701033697
61085    1
Name: PERSNR, dtype: int32
1
1444    1
Name: PKWNR, dtype: int64
1
ID: 8701033712
61178    2
Name: PERSNR, dtype: int32
1
1445    1
Name: PKWNR, dtype: int64
1
ID: 8701033727
ID: 8701033738
61284    1
61293    2
Name: PERSNR, dtype: int32
2
1446    1
Name: PKWNR, dtype: int64
1
ID: 8701033745
ID: 8701033904
61429    1
Name: PERSNR, dtype: int32
1
1448    2
1447    1
Name: PKWNR, dtype: int64
2
ID: 8701034197
ID: 8701034219
61518    1
Name: PERSNR, dtype: int32
1
1449    1
Name: PKWNR, dtype: int64
1
ID: 8701034231
61538    1
61553    2
Name: PERSNR, dtype: int32
2
1450    1
1451    2
Name: PKWNR, dtype: int64
2
ID: 8701034454
61601    1
Name: PERSNR, dtype: int32
1
1453    1
Name: PKWNR, dtype: int64
1
ID: 8701034456
61619    1
Name: PERSNR, dtype: int32
1
1454    1
Name: PKWNR, dtype: int64
1
ID: 8701034466
61630    1
Name: PERSNR, dtype: int32
1
1455    1
Name: PKWNR, dtype: int64
1
ID: 8701034474
61669    2
Name: PERSNR, dtype: int32
1
1456    1
Name: PKWNR, dtype: int64
1
ID: 8701034823
61697    1
Name: PERSNR, dtype: int32
1
1457    1
Name: PKWNR, dtype: int64
1
ID: 8701034832
ID: 8701034835
61782    1
Name: PERSNR, dtype: int32
1
1458    1
Name: PKWNR, dtype: int64
1
ID: 8701034836
61816    1
61834    2
Name: PERSNR, dtype: int32
2
1460    2
1459    1
Name: PKWNR, dtype: int64
2
ID: 8701034837
61852    1
Name: PERSNR, dtype: int32
1
1461    1
Name: PKWNR, dtype: int64
1
ID: 8701034844
61873    1
Name: PERSNR, dtype: int32
1
1462    1
Name: PKWNR, dtype: int64
1
ID: 8701035047
ID: 8701035061
61926    1
61946    2
Name: PERSNR, dtype: int32
2
1463    1
Name: PKWNR, dtype: int64
1
ID: 8701035073
61980    1
Name: PERSNR, dtype: int32
1
1464    1
Name: PKWNR, dtype: int64
1
ID: 8701035237
62004    1
62025    2
Name: PERSNR, dtype: int32
2
1465    1
1466    2
Name: PKWNR, dtype: int64
2
ID: 8701035238
62062    1
Name: PERSNR, dtype: int32
1
1467    1
Name: PKWNR, dtype: int64
1
ID: 8701035531
ID: 8701035550
62198    1
62234    2

Name: PERSNR, dtype: int32
2
1468    1
Name: PKWNR, dtype: int64
1
ID: 8701035896
62281    1
Name: PERSNR, dtype: int32
1
1469    1
Name: PKWNR, dtype: int64
2
ID: 8701035908
62308    2
Name: PERSNR, dtype: int32
1
1470    1
Name: PKWNR, dtype: int64
1
ID: 8701035936
62336    1
Name: PERSNR, dtype: int32
1
1471    1
Name: PKWNR, dtype: int64
1
ID: 8711030024
ID: 8711030182
62429    2
Name: PERSNR, dtype: int32
1
1472    1
Name: PKWNR, dtype: int64
1
ID: 8711030195
62443    1
62462    2
62464    3
Name: PERSNR, dtype: int32
3
1475    2
1473    3
1474    1
Name: PKWNR, dtype: int64
3
ID: 8711030362
62481    1
62514    2
Name: PERSNR, dtype: int32
2
1477    2
1476    1
Name: PKWNR, dtype: int64
2
ID: 8711030393
ID: 8711030408
62555    1
62620    2
62646    3
Name: PERSNR, dtype: int32
3
1479    2
1478    1
1480    3
Name: PKWNR, dtype: int64
3
ID: 8711030458
ID: 8711030588
62767    1
Name: PERSNR, dtype: int32
1
1481    1
Name: PKWNR, dtype: int64
1
ID: 8711030669
62869    1
62873    2
Name: PERSNR, dtype: int32
2
1482    1
Name: PKWNR, dtype: int64
1
ID: 8711030676
62886    1
62895    2
Name: PERSNR, dtype: int32
2
1483    1
Name: PKWNR, dtype: int64
1
ID: 8711030766
62937    1
62957    2
Name: PERSNR, dtype: int32
2
1485    1
1484    2
Name: PKWNR, dtype: int64
2
ID: 8711030806
63000    1
Name: PERSNR, dtype: int32
1
1486    1
Name: PKWNR, dtype: int64
1
ID: 8711030816
ID: 8711030837
63060    1
63065    2
Name: PERSNR, dtype: int32
2
1487    1
Name: PKWNR, dtype: int64
1
ID: 8711030878
63109    2
Name: PERSNR, dtype: int32
1
1488    1
Name: PKWNR, dtype: int64
1
ID: 8711030893
63133    1
Name: PERSNR, dtype: int32
1
1489    1
Name: PKWNR, dtype: int64
1
ID: 8711030901
63155    1
63182    2
Name: PERSNR, dtype: int32
2
1491    2
1490    1
Name: PKWNR, dtype: int64
3
ID: 8711030902
ID: 8711030912
63260    2
Name: PERSNR, dtype: int32
1
1492    1
Name: PKWNR, dtype: int64
1
ID: 8711030914
ID: 8711030966
63353    1
Name: PERSNR, dtype: int32
1
1493    1
1494    2
Name: PKWNR, dtype: int64
2
ID: 8711030974
63373    1
Name: PERSNR, dtype: int32
1
1495    1
Name: PKWNR, dtype: int64
1
ID: 8711030977
63397    1
63401    2
Name: PERSNR, dtype: int32
2
1497    1
1496    2
Name: PKWNR, dtype: int64
2
ID: 8711030998
63458    1
63471    2
Name: PERSNR, dtype: int32
2
1498    1
Name: PKWNR, dtype: int64
1
ID: 8711031131
63505    2
Name: PERSNR, dtype: int32
1
1499    1
Name: PKWNR, dtype: int64
1
ID: 8711031145
63535    1
63557    2
Name: PERSNR, dtype: int32
2
1501    2
1500    1
Name: PKWNR, dtype: int64
2
ID: 8711031148
63612    2
Name: PERSNR, dtype: int32
1
1502    1
Name: PKWNR, dtype: int64
1
ID: 8711031162
63628    1
63662    2
63678    3
Name: PERSNR, dtype: int32
3
1504    2
1505    3
1503    1
Name: PKWNR, dtype: int64
3
ID: 8711031169
ID: 8711031243
63738    1
Name: PERSNR, dtype: int32
1
1506    1
1507    2
Name: PKWNR, dtype: int64
2
ID: 8711031249
63767    1
Name: PERSNR, dtype: int32
1
1508    1
Name: PKWNR, dtype: int64
1
ID: 8711031250
63790    1
Name: PERSNR, dtype: int32
1
1509    1
Name: PKWNR, dtype: int64
1
ID: 8711031400
63813    1
63842    2
Name: PERSNR, dtype: int32
2
1511    1
1512    2
Name: PKWNR, dtype: int64
2
ID: 8711031475
ID: 8711031477
63894    1
63916    2
Name: PERSNR, dtype: int32
2
1514    2
1513    1
Name: PKWNR, dtype: int64
2
ID: 8711031488
63922    1
63933    2
Name: PERSNR, dtype: int32
2
1515    1
1516    2
Name: PKWNR, dtype: int64
2
ID: 8711031492
ID: 8711031501
63978    1
64000    2
Name: PERSNR, dtype: int32
2
1517    1
Name: PKWNR, dtype: int64
1
ID: 8711031509
ID: 8711031514
64075    1
Name: PERSNR, dtype: int32
1
1518    1
1519    2
Name: PKWNR, dtype: int64
2
ID: 8711031515
64102    1
64119    2
Name: PERSNR, dtype: int32
2
1521    2
1520    1
Name: PKWNR, dtype: int64
2
ID: 8711031549
64132    1
64181    2
Name: PERSNR, dtype: int32
2
1522    1
1523    2
Name: PKWNR, dtype: int64
2
ID: 8711031582
64221    1
64241    2
Name: PERSNR, dtype: int32
2
1524    1
Name: PKWNR, dtype: int64
1
ID: 8711031595
64259    1
64294    2
Name: PERSNR, dtype: int32
2
1525    1
Name: PKWNR, dtype: int64
1
ID: 8711031650
64391    1
64433    2
Name: PERSNR, dtype: int32
2
1526    1
Name: PKWNR, dtype: int64
1
ID: 8711031707
ID: 8711031744
64471    1
64500    2
Name: PERSNR, dtype: int32
2
1527    1
Name: PKWNR, dtype: int64
1
ID: 8711031747
64513    1
64517    2
Name: PERSNR, dtype: int32
2
1528    1
Name: PKWNR, dtype: int64
1
ID: 8711031764
64544    1
64566    2
Name: PERSNR, dtype: int32
2
1529    1
Name: PKWNR, dtype: int64
1
ID: 8711031798
64589    1
Name: PERSNR, dtype: int32
1
1530    1
Name: PKWNR, dtype: int64
1
ID: 8711031836
64601    1
Name: PERSNR, dtype: int32
1
1531    1
Name: PKWNR, dtype: int64
1
ID: 8711031924
64662    1
Name: PERSNR, dtype: int32
1
1532    1
Name: PKWNR, dtype: int64
1
ID: 8711031960
64683    1
64700    2
Name: PERSNR, dtype: int32
2
1533    1
Name: PKWNR, dtype: int64
1
ID: 8711031986
ID: 8711032028
64734    1
Name: PERSNR, dtype: int32
1
1534    1
Name: PKWNR, dtype: int64
1
ID: 8711032039
64751    1
Name: PERSNR, dtype: int32
1
1535    1
Name: PKWNR, dtype: int64
1
ID: 8711032048
64775    1
64812    2
Name: PERSNR, dtype: int32
2
1536    1
Name: PKWNR, dtype: int64
1
ID: 8711032087
64845    1
64863    2
Name: PERSNR, dtype: int32
2
1537    1
Name: PKWNR, dtype: int64
1
ID: 8711032118
64877    1
Name: PERSNR, dtype: int32
1
1538    1
Name: PKWNR, dtype: int64
1
ID: 8901042697
ID: 8901042700
64932    1
64989    2
Name: PERSNR, dtype: int32
2
1539    1
Name: PKWNR, dtype: int64
1
ID: 8901042715
65028    1
Name: PERSNR, dtype: int32
1
1540    1
Name: PKWNR, dtype: int64
1
ID: 8901042721
65071    1
65107    2
Name: PERSNR, dtype: int32
2
1541    1
Name: PKWNR, dtype: int64
1
ID: 8901042724
65117    1
Name: PERSNR, dtype: int32
1
1542    1
Name: PKWNR, dtype: int64
1
ID: 8901042738
65137    1
65145    2
Name: PERSNR, dtype: int32
2
1543    1
Name: PKWNR, dtype: int64
1
ID: 8901042749
65178    1
65207    2
Name: PERSNR, dtype: int32
2
1545    2
1544    1
Name: PKWNR, dtype: int64
3
ID: 8901042750
65256    1
65270    2
Name: PERSNR, dtype: int32
2
1547    2
1546    1
Name: PKWNR, dtype: int64
2
ID: 8901042943
65290    1
Name: PERSNR, dtype: int32
1
1548    1
Name: PKWNR, dtype: int64
1
ID: 8901042953
ID: 8901042961
65362    1
Name: PERSNR, dtype: int32
1
1549    1
Name: PKWNR, dtype: int64
1
ID: 8901042975
65396    1
Name: PERSNR, dtype: int32
1
1550    1
Name: PKWNR, dtype: int64
2
ID: 8901043081
ID: 8901043100
65503    1
Name: PERSNR, dtype: int32
1
1552    1
Name: PKWNR, dtype: int64
1
ID: 8901043410
65534    1
Name: PERSNR, dtype: int32
1
1553    1
Name: PKWNR, dtype: int64
1
ID: 8901043426
65596    1
65617    2
Name: PERSNR, dtype: int32
2
1554    1
Name: PKWNR, dtype: int64
2
ID: 8901043428
65648    1
Name: PERSNR, dtype: int32
1
1555    1
Name: PKWNR, dtype: int64
1
ID: 8901043434
65708    2
Name: PERSNR, dtype: int32
1
1556    1
Name: PKWNR, dtype: int64
1
ID: 8901043451
ID: 8901043462
65775    1
65785    2
Name: PERSNR, dtype: int32
2
1558    1
1559    2
Name: PKWNR, dtype: int64
2
ID: 8901043742
ID: 8901043754
ID: 8901043762
66010    1
Name: PERSNR, dtype: int32
1
1560    1
Name: PKWNR, dtype: int64
2
ID: 8901043774
66033    1
66059    2
Name: PERSNR, dtype: int32
2
1561    1
Name: PKWNR, dtype: int64
1
ID: 8901043797
66095    1
66110    2
Name: PERSNR, dtype: int32
2
1562    1
Name: PKWNR, dtype: int64
1
ID: 8901043927
66116    1
66141    2
Name: PERSNR, dtype: int32
2
1563    1
1564    2
Name: PKWNR, dtype: int64
2
ID: 8901043932
66162    1
Name: PERSNR, dtype: int32
1
1565    1
Name: PKWNR, dtype: int64
2
ID: 8901043937
66189    1
Name: PERSNR, dtype: int32
1
1567    2
1566    1
Name: PKWNR, dtype: int64
2
ID: 8901043946
66234    1
66279    2
Name: PERSNR, dtype: int32
2
1568    1
Name: PKWNR, dtype: int64
1
ID: 8901044149
ID: 8901044158
66368    1
66387    2
Name: PERSNR, dtype: int32
2
1570    2
1569    1
Name: PKWNR, dtype: int64
2
ID: 8901044160
ID: 8901044161
66491    1
Name: PERSNR, dtype: int32
1
1571    1
1572    2
Name: PKWNR, dtype: int64
2
ID: 8901044166
66505    1
66527    2
Name: PERSNR, dtype: int32
2
1573    1
1574    2
Name: PKWNR, dtype: int64
2
ID: 8901044176
66573    1
Name: PERSNR, dtype: int32
1
1575    1
Name: PKWNR, dtype: int64
1
ID: 8901044460
ID: 8901044468
66730    2
Name: PERSNR, dtype: int32
1
1576    1
Name: PKWNR, dtype: int64
1
ID: 8901044474
66744    1
Name: PERSNR, dtype: int32
1
1577    1
Name: PKWNR, dtype: int64
1
ID: 8901044481
66753    1
Name: PERSNR, dtype: int32
1
1578    1
Name: PKWNR, dtype: int64
1
ID: 8901044488
66776    1
Name: PERSNR, dtype: int32
1
1579    1
Name: PKWNR, dtype: int64
2
ID: 8901044506
66799    1
66829    2
66845    3
Name: PERSNR, dtype: int32
3
1581    2
1580    1
Name: PKWNR, dtype: int64
2
ID: 8901044862
66956    1
Name: PERSNR, dtype: int32
1
1582    1
Name: PKWNR, dtype: int64
1
ID: 8901044875
67026    1
67056    2
Name: PERSNR, dtype: int32
2
1584    2
1583    1
Name: PKWNR, dtype: int64
2
ID: 8901044896
67138    1
Name: PERSNR, dtype: int32
1
1586    1
Name: PKWNR, dtype: int64
2
ID: 8901044900
67157    1
Name: PERSNR, dtype: int32
1
1587    1
Name: PKWNR, dtype: int64
1
ID: 8901044905
67177    1
Name: PERSNR, dtype: int32
1
1588    1
Name: PKWNR, dtype: int64
1
ID: 8901044907
67213    2
67225    3
Name: PERSNR, dtype: int32
2
1589    1
Name: PKWNR, dtype: int64
2
ID: 8901044913
67259    2
Name: PERSNR, dtype: int32
1
1590    1
Name: PKWNR, dtype: int64
1
ID: 8901045317
67288    1
Name: PERSNR, dtype: int32
1
1591    1
Name: PKWNR, dtype: int64
1
ID: 8901045327
67311    1
67324    2
Name: PERSNR, dtype: int32
2
1593    2
1592    1
Name: PKWNR, dtype: int64
2
ID: 8901045332
67336    1
Name: PERSNR, dtype: int32
1
1594    1
Name: PKWNR, dtype: int64
1
ID: 8901045334
67355    1
Name: PERSNR, dtype: int32
1
1595    1
Name: PKWNR, dtype: int64
1
ID: 8901045342
67382    1
Name: PERSNR, dtype: int32
1
1596    1
Name: PKWNR, dtype: int64
1
ID: 8901045366
67464    1
Name: PERSNR, dtype: int32
1
1597    1
Name: PKWNR, dtype: int64
1
ID: 8901045785
ID: 8901045787
ID: 8901045798
67606    1
Name: PERSNR, dtype: int32
1
1598    1
Name: PKWNR, dtype: int64
2
ID: 8901045812
67661    1
67671    2
Name: PERSNR, dtype: int32
2
1599    1
Name: PKWNR, dtype: int64
2
ID: 8901045817
67687    1
67720    2
Name: PERSNR, dtype: int32
2
1601    2
1600    1
Name: PKWNR, dtype: int64
2
ID: 8901045825
67770    1
Name: PERSNR, dtype: int32
1
1602    1
Name: PKWNR, dtype: int64
1
ID: 8901045828
67795    1
Name: PERSNR, dtype: int32
1
1603    1
Name: PKWNR, dtype: int64
1
ID: 8901045834
67812    1
Name: PERSNR, dtype: int32
1
1604    1
Name: PKWNR, dtype: int64
1
ID: 8901045914
67896    2
Name: PERSNR, dtype: int32
1
1605    1
Name: PKWNR, dtype: int64
1
ID: 8901045917
67953    1
67965    2
Name: PERSNR, dtype: int32
2
1607    2
1606    1
Name: PKWNR, dtype: int64
2
ID: 8901046094
ID: 8901046132
ID: 8911040073
68027    1
Name: PERSNR, dtype: int32
1
1608    1
Name: PKWNR, dtype: int64
1
ID: 8911040145
ID: 8911040163

68117    1
68144    2
Name: PERSNR, dtype: int32
2
1609    1
Name: PKWNR, dtype: int64
1
ID: 8911040173
68174    1
68195    2
Name: PERSNR, dtype: int32
2
1610    1
1611    2
Name: PKWNR, dtype: int64
2
ID: 8911040182
68252    1
68283    2
Name: PERSNR, dtype: int32
2
1613    2
1612    1
Name: PKWNR, dtype: int64
2
ID: 8911040217
68321    1
68325    2
Name: PERSNR, dtype: int32
2
1614    1
Name: PKWNR, dtype: int64
1
ID: 8911040240
ID: 8911040319
68428    1
68461    2
Name: PERSNR, dtype: int32
2
1615    1
1616    2
Name: PKWNR, dtype: int64
2
ID: 8911040383
68492    1
Name: PERSNR, dtype: int32
1
1617    1
Name: PKWNR, dtype: int64
2
ID: 8911040415
68514    1
Name: PERSNR, dtype: int32
1
1618    1
Name: PKWNR, dtype: int64
1
ID: 8911040446
68552    1
Name: PERSNR, dtype: int32
1
1619    1
1620    2
Name: PKWNR, dtype: int64
2
ID: 8911040504
ID: 8911040692
ID: 8911040724
ID: 8911040744
ID: 8911040750
ID: 8911040786
68844    1
Name: PERSNR, dtype: int32
1
1621    1
Name: PKWNR, dtype: int64
2
ID: 8911040793
68905    1
68937    2
Name: PERSNR, dtype: int32
2
1622    1
1623    2
1624    3
Name: PKWNR, dtype: int64
3
ID: 8911040809
68961    1
68983    2
Name: PERSNR, dtype: int32
2
1625    1
1626    2
Name: PKWNR, dtype: int64
2
ID: 8911040835
68987    1
69006    2
69029    3
Name: PERSNR, dtype: int32
3
1627    1
1628    2
Name: PKWNR, dtype: int64
3
ID: 8911040871
ID: 8911040902
69097    1
69120    2
Name: PERSNR, dtype: int32
2
1629    1
Name: PKWNR, dtype: int64
1
ID: 8911040931
69198    1
69225    2
Name: PERSNR, dtype: int32
2
1630    1
Name: PKWNR, dtype: int64
1
ID: 8911040945
ID: 8911040949
69237    1
Name: PERSNR, dtype: int32
1
1631    1
Name: PKWNR, dtype: int64
1
ID: 8911040980
ID: 8911041011
69351    1
69368    2
Name: PERSNR, dtype: int32
2
1632    1
Name: PKWNR, dtype: int64
2
ID: 8911041130
69407    1
Name: PERSNR, dtype: int32
1
1633    1
Name: PKWNR, dtype: int64
1
ID: 8911041185
69462    1
69472    2
Name: PERSNR, dtype: int32
2
1634    1
Name: PKWNR, dtype: int64
1
ID: 8911041251
69488    1
69519    2
Name: PERSNR, dtype: int32
2
1635    1
Name: PKWNR, dtype: int64
2
ID: 8911041252
69541    1
69550    2
Name: PERSNR, dtype: int32
2
1636    1
1637    2
Name: PKWNR, dtype: int64
2
ID: 8911041302
ID: 8911041351
69622    1
Name: PERSNR, dtype: int32
1
1638    1
Name: PKWNR, dtype: int64
1
ID: 8911041380
ID: 8911041502
69713    1
Name: PERSNR, dtype: int32
1
1639    1
Name: PKWNR, dtype: int64
1
ID: 8911041515
ID: 8911041529
69775    1
Name: PERSNR, dtype: int32
1
1640    1
Name: PKWNR, dtype: int64
1
ID: 8911041634
69822    2
Name: PERSNR, dtype: int32
1
1641    1
1642    2
Name: PKWNR, dtype: int64
2
ID: 8911041641
69843    1
69868    2
Name: PERSNR, dtype: int32
2
1643    1
Name: PKWNR, dtype: int64
1
ID: 8911041650
69889    1
69912    2
Name: PERSNR, dtype: int32
2
1644    1
Name: PKWNR, dtype: int64
2
ID: 8911041688
69959    1
Name: PERSNR, dtype: int32
1
1645    1
Name: PKWNR, dtype: int64
1
ID: 8911041759
69976    1
69998    2
Name: PERSNR, dtype: int32
2
1646    1
1647    2
Name: PKWNR, dtype: int64
2
ID: 8911041859
ID: 8911041861
70058    1
Name: PERSNR, dtype: int32
1
1649    1
Name: PKWNR, dtype: int64
1
ID: 8911041968
70075    1
Name: PERSNR, dtype: int32
1
1650    1
Name: PKWNR, dtype: int64
1
ID: 8911041972
70094    1
Name: PERSNR, dtype: int32
1
1651    1
Name: PKWNR, dtype: int64
1
ID: 8911042017
ID: 8911042091
70183    1
Name: PERSNR, dtype: int32
1
1652    1
Name: PKWNR, dtype: int64
1
ID: 8911042093
ID: 8911042116
ID: 8911042144
70318    1
70349    2
Name: PERSNR, dtype: int32
2
1654    2
1653    1
Name: PKWNR, dtype: int64
2
ID: 8911042234
70473    1
70499    2
Name: PERSNR, dtype: int32
2
1655    1
Name: PKWNR, dtype: int64
1
ID: 8911042240
70522    1
70545    2
Name: PERSNR, dtype: int32
2
1656    1
Name: PKWNR, dtype: int64
1
ID: 8911042258
ID: 8911042260
70600    1
70628    2
Name: PERSNR, dtype: int32
2
1657    1
Name: PKWNR, dtype: int64
1
ID: 8911042266
70673    1
70717    2
Name: PERSNR, dtype: int32
2
1658    1
Name: PKWNR, dtype: int64
1
ID: 8911042268
70724    1
Name: PERSNR, dtype: int32
1
1659    1
Name: PKWNR, dtype: int64
1
ID: 8911042284
70786    1
70807    2
Name: PERSNR, dtype: int32
2
1661    2
1660    1
Name: PKWNR, dtype: int64
2
ID: 8911042421
70875    1
Name: PERSNR, dtype: int32
1
1662    1
Name: PKWNR, dtype: int64
1
ID: 8911044932
70907    1
Name: PERSNR, dtype: int32
1
1663    1
Name: PKWNR, dtype: int64
1
ID: 8911045385
ID: 8911045497
71040    2
Name: PERSNR, dtype: int32
1
1664    1
Name: PKWNR, dtype: int64
1
ID: 8911046133
71118    1
Name: PERSNR, dtype: int32
1
1665    1
Name: PKWNR, dtype: int64
1
ID: 8911046177

In [23]:
# Check results
df_W_copy.head(100)
df_W_copy['PKWNR'] = pkw_values

df_W = df_W_copy
df_W.head(100)

,ID,PERSNR,WOTAG,BERTAG,DATUM,WNRT,ABZEIT,ZWECK,VMDIW,ANZEIT,KM,DAUER,SPEED,PKWNR
11,4501022118,2,7,1,21443,1,1130,5,41,1138,1.00,8,8,1
12,4501022118,2,7,1,21443,2,1310,7,41,1320,1.00,10,6,1
13,4501022118,2,1,2,21444,1,1420,4,41,1425,1.00,5,12,1
14,4501022118,2,1,2,21444,2,1450,7,41,1455,1.00,5,12,1
15,4501022118,2,2,3,21445,1,1030,6,41,1045,3.60,15,14,1
16,4501022118,2,2,3,21445,2,1050,4,41,1115,5.50,25,13,1
17,4501022118,2,2,3,21445,3,1215,6,41,1240,5.50,25,13,1
18,4501022118,2,2,3,21445,4,1245,7,41,1257,3.60,12,18,1
19,4501022118,2,2,3,21445,5,1530,5,41,1550,6.90,20,21,1
20,4501022118,2,2,3,21445,6,1840,7,41,1855,6.90,15,28,1
21,4501022118,2,3,4,21446,1,1315,6,41,1325,2.80,10,17,1
22,4501022118,2,3,4,21446,2,1530,7,41,1545,2.80,15,11,1
23,4501022118,2,4,5,21447,1,1030,4,41,1105,12.60,35,22,1
24,4501022118,2,4,5,21447,2,1245,7,41,1315,12.40,30,25,1
25,4501022118,2,5,6,21448,1,1000,11,41,1025,25.10,25,60,1
26,4501022118,2,5,6,21448,2,1140,7,41,1210,25.60,30,51,1
27,4501022118,2,5,6,21448,3,1230,5,41,1240,2.20,10,13,1
28,4501022118,2,5,6,21448,4,1445,7,41,1500,2.20,15,9,1
29,4501022118,2,6,7,21449,1,1100,9,41,1900,736.00,480,92,1
30,4501022122,1,1,1,21437,1,630,6,41,730,30.00,60,30,1
31,4501022122,1,1,1,21437,2,745,7,41,836,30.00,51,35,1
32,4501022122,1,1,1,21437,3,1900,6,41,1930,30.00,30,60,1
33,4501022122,1,1,1,21437,4,1931,7,41,2000,30.00,29,62,1
34,4501022122,1,2,2,21438,1,630,6,41,730,30.00,60,30,1
35,4501022122,1,2,2,21438,2,735,7,41,830,30.00,55,33,1
36,4501022122,1,2,2,21438,3,1000,6,41,1030,15.00,30,30,1
37,4501022122,1,2,2,21438,4,1040,7,41,1115,15.00,35,26,1
38,4501022122,1,2,2,21438,5,1900,6,41,1935,30.00,35,51,1
39,4501022122,1,2,2,21438,6,1955,7,41,2030,30.00,35,51,1
40,4501022122,1,3,3,21439,1,630,6,41,715,30.00,45,40,1
41,4501022122,1,3,3,21439,2,740,7,41,825,30.00,45,40,1
42,4501022122,1,3,3,21439,3,1900,6,41,1930,30.00,30,60,1
43,4501022122,1,3,3,21439,4,2000,7,41,2030,30.00,30,60,1
44,4501022122,1,4,4,21440,1,700,6,41,730,30.00,30,60,1
45,4501022122,1,4,4,21440,2,731,7,41,800,30.00,29,62,1
68,4501022123,1,4,4,21440,3,1200,5,41,1245,30.00,45,40,0
69,4501022123,1,4,4,21440,4,2025,7,41,2110,30.00,45,40,0
70,4501022123,1,5,5,21441,1,1345,11,41,1355,5.00,10,30,0
71,4501022123,1,5,5,21441,2,1435,7,41,1450,5.00,15,20,0
106,4501022143,1,1,2,21479,3,1347,4,41,1426,24.00,39,37,1
107,4501022143,1,1,2,21479,4,1530,7,41,1610,26.00,40,39,1
110,4501022143,1,3,4,21481,1,1415,4,41,1445,26.00,30,52,1
111,4501022143,1,3,4,21481,2,1530,7,41,1600,26.00,30,52,1
119,4501022157,1,1,3,21479,1,930,5,41,1000,17.00,30,34,1
129,4501022157,1,4,6,21482,3,1610,11,41,1630,8.50,20,26,1
130,4501022157,1,4,6,21482,4,1710,7,41,1735,8.00,25,19,1
133,4501022157,1,5,7,21483,3,1350,5,41,1405,6.50,15,26,1
134,4501022157,1,5,7,21483,4,1525,7,41,1540,6.00,15,24,1
136,4501022157,2,7,2,21478,2,1735,7,41,1845,75.00,70,64,1
137,4501022157,2,1,3,21479,1,930,5,41,1000,17.00,30,34,1
138,4501022157,2,1,3,21479,2,1110,5,41,1130,6.00,20,18,1
139,4501022157,2,1,3,21479,3,1230,4,41,1245,6.00,15,24,1
140,4501022157,2,1,3,21479,4,1315,7,41,1400,18.00,45,24,1
141,4501022157,2,2,4,21480,1,930,4,41,935,1.10,5,13,1
142,4501022157,2,2,4,21480,2,940,7,41,945,1.20,5,14,1
143,4501022157,2,2,4,21480,3,1040,4,41,1120,17.00,40,26,1
144,4501022157,2,2,4,21480,4,1205,7,41,1245,17.00,40,26,1
145,4501022157,2,3,5,21481,1,1315,4,41,1350,20.10,35,34,1
146,4501022157,2,3,5,21481,2,1420,7,41,1505,20.10,45,27,1
147,4501022157,2,4,6,21482,1,1020,4,41,1125,25.00,65,23,1
148,4501022157,2,4,6,21482,2,1240,7,41,1345,25.10,65,23,1
151,4501022157,2,5,7,21483,1,935,11,41,1010,16.50,35,28,1
152,4501022157,2,5,7,21483,2,1050,7,41,1125,17.00,35,29,1
175,4501022161,2,4,2,21475,1,500,1,41,615,90.00,75,72,1
176,4501022161,2,4,2,21475,2,1530,7,41,1640,90.00,70,77,1
177,4501022161,2,4,2,21475,3,1820,5,41,1835,4.20,15,17,1
178,4501022161,2,4,2,21475,4,2045,7,41,2100,4.20,15,17,1
179,4501022161,2,5,3,21476,1,1300,4,41,1315,4.00,15,16,1
180,4501022161,2,5,3,21476,2,1330,7,41,1345,4.00,15,16,1
181,4501022161,2,5,3,21476,3,1445,11,41,1452,2.50,7,21,1
182,4501022161,2,5,3,21476,4,1630,4,41,1640,2.00,10,12,1
183,4501022161,2,5,3,21476,5,1730,7,41,1745,4.20,15,17,1
189,4501022161,2,1,6,21479,1,500,1,41,615,90.00,75,72,1
190,4501022161,2,1,6,21479,2,1530,7,41,1645,90.00,75,72,1
191,4501022161,2,2,7,21480,1,500,1,41,610,90.00,70,77,1
192,4501022161,2,2,7,21480,2,1535,7,41,1630,90.00,55,98,1
193,4501022161,2,2,7,21480,3,1840,5,41,1855,4.20,15,17,1
194,4501022161,2,2,7,21480,4,2055,7,41,2105,4.20,10,25,1
214,4501022162,2,4,1,21475,1,740,11,41,755,10.00,15,40,2
215,4501022162,2,4,1,21475,2,920,7,41,935,10.00,15,40,2
219,4501022162,2,5,2,21476,1,635,6,41,655,12.00,20,36,2
222,4501022162,2,5,2,21476,4,945,4,41,950,2.00,5,24,2
223,4501022162,2,5,2,21476,5,1025,7,41,1030,2.00,5,24,2
224,4501022162,2,5,2,21476,6,1325,6,41,1345,11.00,20,33,2
225,4501022162,2,5,2,21476,7,1346,7,41,1405,11.00,19,35,2
228,4501022162,2,1,5,21479,1,750,11,41,825,24.00,35,41,2
229,4501022162,2,1,5,21479,2,945,4,41,1030,22.00,45,29,2
230,4501022162,2,1,5,21479,3,1040,7,41,1045,2.00,5,24,2
231,4501022162,2,1,5,21479,4,1435,6,41,1442,1.50,7,13,2
232,4501022162,2,1,5,21479,5,1500,7,41,1515,1.80,15,7,2
237,4501022162,2,2,6,21480,1,740,11,41,755,10.00,15,40,2
238,4501022162,2,2,6,21480,2,900,7,41,915,10.00,15,40,2
243,4501022162,2,3,7,21481,2,1100,5,41,1110,8.00,10,48,2
244,4501022162,2,3,7,21481,3,1145,7,41,1150,8.00,5,96,2
245,4501022162,2,3,7,21481,4,1500,5,41,1505,1.20,5,14,2
246,4501022162,2,3,7,21481,5,1630,7,41,1635,1.20,5,14,2
247,4501022162,2,3,7,21481,6,1700,5,41,1710,5.00,10,30,2
248,4501022162,2,3,7,21481,7,1810,7,41,1820,5.00,10,30,2
278,4501022162,4,4,1,21475,5,1615,6,41,1625,8.00,10,48,1
279,4501022162,4,4,1,21475,6,1630,7,41,1640,8.00,10,48,1

In [24]:
# Count PKWNR
print(df_W_copy.groupby('PKWNR').count())

          ID  PERSNR  WOTAG  BERTAG  DATUM   WNRT  ABZEIT  ZWECK  VMDIW  \
PKWNR
0       6629    6629   6629    6629   6629   6629    6629   6629   6629
1      20767   20767  20767   20767  20767  20767   20767  20767  20767
2       5163    5163   5163    5163   5163   5163    5163   5163   5163
3        555     555    555     555    555    555     555    555    555
4        193     193    193     193    193    193     193    193    193
5         11      11     11      11     11     11      11     11     11

       ANZEIT     KM  DAUER  SPEED
PKWNR
0        6629   6629   6629   6629
1       20767  20767  20767  20767
2        5163   5163   5163   5163
3         555    555    555    555
4         193    193    193    193
5          11     11     11     11

In [28]:
df_W_energy = df_W
# Add energy consumption to W data set
df_W_energy['ENERGYCONS'] = np.nan

# Add energy consumption according to consumption rate from assigned vehicle 
def f_ENERGYCONS(row):
    idhh = row[0]
    pkwnr = row[13]
    if pkwnr == 0:
        consumption = 0.16
        val = consumption * row[10]
    else:  
        consumption = df_TANK.loc[(df_TANK['IDHH'] == idhh) & (df_TANK['PKWNR'] == pkwnr), 'ENERGY']
        cons = consumption.values[0]/100
        val = cons * row[10]
    return val

    
df_W_energy['ENERGYCONS'] = df_W_energy.apply(f_ENERGYCONS, axis=1)
df_W_energy.head(100)

,ID,PERSNR,WOTAG,BERTAG,DATUM,WNRT,ABZEIT,ZWECK,VMDIW,ANZEIT,KM,DAUER,SPEED,PKWNR,ENERGYCONS
11,4501022118,2,7,1,21443,1,1130,5,41,1138,1.00,8,8,1,0.16
12,4501022118,2,7,1,21443,2,1310,7,41,1320,1.00,10,6,1,0.16
13,4501022118,2,1,2,21444,1,1420,4,41,1425,1.00,5,12,1,0.16
14,4501022118,2,1,2,21444,2,1450,7,41,1455,1.00,5,12,1,0.16
15,4501022118,2,2,3,21445,1,1030,6,41,1045,3.60,15,14,1,0.58
16,4501022118,2,2,3,21445,2,1050,4,41,1115,5.50,25,13,1,0.89
17,4501022118,2,2,3,21445,3,1215,6,41,1240,5.50,25,13,1,0.89
18,4501022118,2,2,3,21445,4,1245,7,41,1257,3.60,12,18,1,0.58
19,4501022118,2,2,3,21445,5,1530,5,41,1550,6.90,20,21,1,1.11
20,4501022118,2,2,3,21445,6,1840,7,41,1855,6.90,15,28,1,1.11
21,4501022118,2,3,4,21446,1,1315,6,41,1325,2.80,10,17,1,0.45
22,4501022118,2,3,4,21446,2,1530,7,41,1545,2.80,15,11,1,0.45
23,4501022118,2,4,5,21447,1,1030,4,41,1105,12.60,35,22,1,2.03
24,4501022118,2,4,5,21447,2,1245,7,41,1315,12.40,30,25,1,2.00
25,4501022118,2,5,6,21448,1,1000,11,41,1025,25.10,25,60,1,4.04
26,4501022118,2,5,6,21448,2,1140,7,41,1210,25.60,30,51,1,4.12
27,4501022118,2,5,6,21448,3,1230,5,41,1240,2.20,10,13,1,0.35
28,4501022118,2,5,6,21448,4,1445,7,41,1500,2.20,15,9,1,0.35
29,4501022118,2,6,7,21449,1,1100,9,41,1900,736.00,480,92,1,118.50
30,4501022122,1,1,1,21437,1,630,6,41,730,30.00,60,30,1,4.83
31,4501022122,1,1,1,21437,2,745,7,41,836,30.00,51,35,1,4.83
32,4501022122,1,1,1,21437,3,1900,6,41,1930,30.00,30,60,1,4.83
33,4501022122,1,1,1,21437,4,1931,7,41,2000,30.00,29,62,1,4.83
34,4501022122,1,2,2,21438,1,630,6,41,730,30.00,60,30,1,4.83
35,4501022122,1,2,2,21438,2,735,7,41,830,30.00,55,33,1,4.83
36,4501022122,1,2,2,21438,3,1000,6,41,1030,15.00,30,30,1,2.42
37,4501022122,1,2,2,21438,4,1040,7,41,1115,15.00,35,26,1,2.42
38,4501022122,1,2,2,21438,5,1900,6,41,1935,30.00,35,51,1,4.83
39,4501022122,1,2,2,21438,6,1955,7,41,2030,30.00,35,51,1,4.83
40,4501022122,1,3,3,21439,1,630,6,41,715,30.00,45,40,1,4.83
41,4501022122,1,3,3,21439,2,740,7,41,825,30.00,45,40,1,4.83
42,4501022122,1,3,3,21439,3,1900,6,41,1930,30.00,30,60,1,4.83
43,4501022122,1,3,3,21439,4,2000,7,41,2030,30.00,30,60,1,4.83
44,4501022122,1,4,4,21440,1,700,6,41,730,30.00,30,60,1,4.83
45,4501022122,1,4,4,21440,2,731,7,41,800,30.00,29,62,1,4.83
68,4501022123,1,4,4,21440,3,1200,5,41,1245,30.00,45,40,0,4.80
69,4501022123,1,4,4,21440,4,2025,7,41,2110,30.00,45,40,0,4.80
70,4501022123,1,5,5,21441,1,1345,11,41,1355,5.00,10,30,0,0.80
71,4501022123,1,5,5,21441,2,1435,7,41,1450,5.00,15,20,0,0.80
106,4501022143,1,1,2,21479,3,1347,4,41,1426,24.00,39,37,1,3.86
107,4501022143,1,1,2,21479,4,1530,7,41,1610,26.00,40,39,1,4.19
110,4501022143,1,3,4,21481,1,1415,4,41,1445,26.00,30,52,1,4.19
111,4501022143,1,3,4,21481,2,1530,7,41,1600,26.00,30,52,1,4.19
119,4501022157,1,1,3,21479,1,930,5,41,1000,17.00,30,34,1,3.21
129,4501022157,1,4,6,21482,3,1610,11,41,1630,8.50,20,26,1,1.61
130,4501022157,1,4,6,21482,4,1710,7,41,1735,8.00,25,19,1,1.51
133,4501022157,1,5,7,21483,3,1350,5,41,1405,6.50,15,26,1,1.23
134,4501022157,1,5,7,21483,4,1525,7,41,1540,6.00,15,24,1,1.13
136,4501022157,2,7,2,21478,2,1735,7,41,1845,75.00,70,64,1,14.17
137,4501022157,2,1,3,21479,1,930,5,41,1000,17.00,30,34,1,3.21
138,4501022157,2,1,3,21479,2,1110,5,41,1130,6.00,20,18,1,1.13
139,4501022157,2,1,3,21479,3,1230,4,41,1245,6.00,15,24,1,1.13
140,4501022157,2,1,3,21479,4,1315,7,41,1400,18.00,45,24,1,3.40
141,4501022157,2,2,4,21480,1,930,4,41,935,1.10,5,13,1,0.21
142,4501022157,2,2,4,21480,2,940,7,41,945,1.20,5,14,1,0.23
143,4501022157,2,2,4,21480,3,1040,4,41,1120,17.00,40,26,1,3.21
144,4501022157,2,2,4,21480,4,1205,7,41,1245,17.00,40,26,1,3.21
145,4501022157,2,3,5,21481,1,1315,4,41,1350,20.10,35,34,1,3.80
146,4501022157,2,3,5,21481,2,1420,7,41,1505,20.10,45,27,1,3.80
147,4501022157,2,4,6,21482,1,1020,4,41,1125,25.00,65,23,1,4.72
148,4501022157,2,4,6,21482,2,1240,7,41,1345,25.10,65,23,1,4.74
151,4501022157,2,5,7,21483,1,935,11,41,1010,16.50,35,28,1,3.12
152,4501022157,2,5,7,21483,2,1050,7,41,1125,17.00,35,29,1,3.21
175,4501022161,2,4,2,21475,1,500,1,41,615,90.00,75,72,1,17.01
176,4501022161,2,4,2,21475,2,1530,7,41,1640,90.00,70,77,1,17.01
177,4501022161,2,4,2,21475,3,1820,5,41,1835,4.20,15,17,1,0.79
178,4501022161,2,4,2,21475,4,2045,7,41,2100,4.20,15,17,1,0.79
179,4501022161,2,5,3,21476,1,1300,4,41,1315,4.00,15,16,1,0.76
180,4501022161,2,5,3,21476,2,1330,7,41,1345,4.00,15,16,1,0.76
181,4501022161,2,5,3,21476,3,1445,11,41,1452,2.50,7,21,1,0.47
182,4501022161,2,5,3,21476,4,1630,4,41,1640,2.00,10,12,1,0.38
183,4501022161,2,5,3,21476,5,1730,7,41,1745,4.20,15,17,1,0.79
189,4501022161,2,1,6,21479,1,500,1,41,615,90.00,75,72,1,17.01
190,4501022161,2,1,6,21479,2,1530,7,41,1645,90.00,75,72,1,17.01
191,4501022161,2,2,7,21480,1,500,1,41,610,90.00,70,77,1,17.01
192,4501022161,2,2,7,21480,2,1535,7,41,1630,90.00,55,98,1,17.01
193,4501022161,2,2,7,21480,3,1840,5,41,1855,4.20,15,17,1,0.79
194,4501022161,2,2,7,21480,4,2055,7,41,2105,4.20,10,25,1,0.79
214,4501022162,2,4,1,21475,1,740,11,41,755,10.00,15,40,2,1.61
215,4501022162,2,4,1,21475,2,920,7,41,935,10.00,15,40,2,1.61
219,4501022162,2,5,2,21476,1,635,6,41,655,12.00,20,36,2,1.93
222,4501022162,2,5,2,21476,4,945,4,41,950,2.00,5,24,2,0.32
223,4501022162,2,5,2,21476,5,1025,7,41,1030,2.00,5,24,2,0.32
224,4501022162,2,5,2,21476,6,1325,6,41,1345,11.00,20,33,2,1.77
225,4501022162,2,5,2,21476,7,1346,7,41,1405,11.00,19,35,2,1.77
228,4501022162,2,1,5,21479,1,750,11,41,825,24.00,35,41,2,3.86
229,4501022162,2,1,5,21479,2,945,4,41,1030,22.00,45,29,2,3.54
230,4501022162,2,1,5,21479,3,1040,7,41,1045,2.00,5,24,2,0.32
231,4501022162,2,1,5,21479,4,1435,6,41,1442,1.50,7,13,2,0.24
232,4501022162,2,1,5,21479,5,1500,7,41,1515,1.80,15,7,2,0.29
237,4501022162,2,2,6,21480,1,740,11,41,755,10.00,15,40,2,1.61
238,4501022162,2,2,6,21480,2,900,7,41,915,10.00,15,40,2,1.61
243,4501022162,2,3,7,21481,2,1100,5,41,1110,8.00,10,48,2,1.29
244,4501022162,2,3,7,21481,3,1145,7,41,1150,8.00,5,96,2,1.29
245,4501022162,2,3,7,21481,4,1500,5,41,1505,1.20,5,14,2,0.19
246,4501022162,2,3,7,21481,5,1630,7,41,1635,1.20,5,14,2,0.19
247,4501022162,2,3,7,21481,6,1700,5,41,1710,5.00,10,30,2,0.81
248,4501022162,2,3,7,21481,7,1810,7,41,1820,5.00,10,30,2,0.81
278,4501022162,4,4,1,21475,5,1615,6,41,1625,8.00,10,48,1,1.29
279,4501022162,4,4,1,21475,6,1630,7,41,1640,8.00,10,48,1,1.29

In [ ]:
df_W = df_W_energy

* 1: to Work
* 2: Trip during Work
* 3: to education
* 4: shopping
* 5: entertainment
* 6: picking someone up
* 7: to home
* 8: misc
* 9: other stay than home
* 10: second home
* 11: misc private
* 77: roundtrip

charging at home, work or in public

In [30]:
# Count trip purposes
print(df_W.groupby('ZWECK').count())

          ID  PERSNR  WOTAG  BERTAG  DATUM   WNRT  ABZEIT  VMDIW  ANZEIT  \
ZWECK
1       3952    3952   3952    3952   3952   3952    3952   3952    3952
2       1419    1419   1419    1419   1419   1419    1419   1419    1419
3        200     200    200     200    200    200     200    200     200
4       4612    4612   4612    4612   4612   4612    4612   4612    4612
5       3368    3368   3368    3368   3368   3368    3368   3368    3368
6       2832    2832   2832    2832   2832   2832    2832   2832    2832
7      13516   13516  13516   13516  13516  13516   13516  13516   13516
9        301     301    301     301    301    301     301    301     301
10        48      48     48      48     48     48      48     48      48
11      3065    3065   3065    3065   3065   3065    3065   3065    3065
77         5       5      5       5      5      5       5      5       5

          KM  DAUER  SPEED  PKWNR  ENERGYCONS
ZWECK
1       3952   3952   3952   3952        3952
2       1419   1419   1419   1419        1419
3        200    200    200    200         200
4       4612   4612   4612   4612        4612
5       3368   3368   3368   3368        3368
6       2832   2832   2832   2832        2832
7      13516  13516  13516  13516       13516
9        301    301    301    301         301
10        48     48     48     48          48
11      3065   3065   3065   3065        3065
77         5      5      5      5           5

### Export data sets as Excel-file

In [35]:
df_HH.to_excel(r'C:\Users\joey_\Desktop\df_HH.xlsx', index = False)

In [36]:
df_TANK.to_excel(r'C:\Users\joey_\Desktop\df_TANK.xlsx', index = False)

In [37]:
df_W.to_excel(r'C:\Users\joey_\Desktop\df_W_JULY.xlsx', index = False)